### ISSUE TITLE
Couldn't download IntelliCode model

### ISSUE THREAD

**Issue by trobr** [MicrosoftDocs/intellicode#1]
* OS:Ubuntu 16.04
* Version: 1.25.1

I have install the Visual Studio IntelliCode extension,but when i enable the Microsoft Python Language Server,a error has occur

    Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

What might be the reason for this and how could i solution this?

**Comment by k7shanmugam** [comment]
Are you behind a proxy or a firewall? Can you share the log entries from the output window (select 'VS IntelliCode' in the dropdown)?

@vivlimmsft - fyi

**Comment by k7shanmugam** [comment]
Thanks. Are you able to reach the endpoint directly in your browser?

**Comment by trobr** [comment]
Yes, I can reach the endpoint in chrome @k7shanmugam

**Comment by k7shanmugam** [comment]
Are you using a proxy? Can you check your environment variables to see if you have set some for proxy? Also what does Chrome report for its proxy settings?

This is likely coming from some npm package we are using that doesn't handle the proxy settings.

**Comment by trobr** [comment]
Does the HTTP proxy set in Bash have an impact?I had try to close the proxy server and  proxy setting in system setting before.But i am forgot to change the bash proxy setting.I am going to change this and try again later.If is usefull,I'll feed it back.Thanks for your advice!

**Comment by trobr** [comment]
@k7shanmugam After I  modified the system environment variables it download success!You are right,Thanks!
