### ISSUE TITLE
autoComplete addBrackets was doesn't work 

### ISSUE THREAD

**Issue by Jarvis-GitHub** [MicrosoftDocs/intellicode#10]
**VS Code Version**: VS Code 1.27.0-insider
**OS Version**: WINDOWS 10
**Visual Studio IntelliCode Extension Version**: Visual Studio IntelliCode-Preview(1.0.3)
**Python Extension Version**: Python Extension Version:2018.7.1 (23 July 2018)
**Target Platform or Language**: Python 3.7

**Steps to Reproduce / Scenario:**

1. Select "Enable Visual Studio IntelliCode completions for Python
2.Select "True" For "python.autoComplete.addBrackets"
3.Type "print" or any function by IntelliSense
4.It doesn't add brackets after the function
![0](https://user-images.githubusercontent.com/42712612/44627301-045ca300-a95e-11e8-9158-07c9d838af6d.png)
![1](https://user-images.githubusercontent.com/42712612/44627302-04f53980-a95e-11e8-9cb9-dd4378b28fb6.png)
![2](https://user-images.githubusercontent.com/42712612/44627303-04f53980-a95e-11e8-96d7-9af3042639cf.png)

**Comment by gewarren** [comment]
@markw-t Can someone take a look at this?

**Comment by markw-t** [comment]
Sorry for the delay in looking at this issue @Jarvis-GitHub . I'd like to figure out if this is a Python language service issue or an IntelliCode issue. Can you try uninstalling the IntelliCode extension and see if the problem still persists? If it does, then this problem should be reported at https://github.com/Microsoft/vscode-python/issues/new instead.

Thanks
Mark

**Comment by markw-t** [comment]
Hi again @Jarvis-GitHub 

This is a known limitation on the new Python language service. It's being tracked already at https://github.com/Microsoft/vscode-python/issues/1772 

Thanks
Mark
