### ISSUE TITLE
Trigger parameter hints does not work for python class constructor

### ISSUE THREAD

**Issue by bengood362** [MicrosoftDocs/intellicode#101]
**Product and Version** [VS/VSCode]: VSCode 1.33.1
**OS Version** [macOS/Windows]: macOS High Sierra 10.13.5
**IntelliCode Extension Version**: 1.1.6
**Target Platform or Language** [e.g. Node.js]: python 3.6.5

**Steps to Reproduce / Scenario:**

1. Create any classes with constructor (__init__), e.g. as below
```
class SomeClass(object):
    def __init__(self, a, b, c, d=4):
        pass
    def p(self, a, b, c=4):
        pass
        
g = SomeClass()
g.p()
```
2. Move cursor to in between the constructor of SomeClass. 
3. Press CMD+shift+P to open the action menu, then choose "trigger parameter hints"
*** No hint is shown ***
4. Retry step 2 & step 3 with its instance method p, and it would shows the parameter hints `p(a, b, c=4)`, prove it is working for instance method.

**Comment by jkeech** [comment]
Does this only happen when IntelliCode is enabled? From the description, it sounds like an issue with the Python Language Server and would not be related to IntelliCode.

**Comment by bengood362** [comment]
Oh sorry, I thought this feature was given by IntelliCode. Issues not related, closed now.
