### ISSUE TITLE
Extension issue took 601ms to activate

### ISSUE THREAD

**Issue by rbadapanda** [MicrosoftDocs/intellicode#106]
- Issue Type: `Bug`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.7`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 288,
		"activateCallTime": 313,
		"activateResolvedTime": 3654,
		"activationEvent": "onLanguage:typescriptreact"
	},
	"runtimeErrors": []
}
```

**Comment by pgroene** [comment]
Can you give us information on what the bug exactly is. Your timing seem to be in the range we expect in 1.1.7.

**Comment by catycaldwell** [comment]
@rbadapanda are you still experiencing this issue?

**Comment by rbadapanda** [comment]
No. I have stopped using the extension so i don’t have any updates on it. 

Please feel free to close the issue. 

Thanks

**Comment by markw-t** [comment]
Thanks for letting us know - please open a new bug should you start using IntelliCode again and see any issues.
