### ISSUE TITLE
double prompting

### ISSUE THREAD

**Issue by chrisdias** [MicrosoftDocs/intellicode#107]
The IntelliCode extension prompts me to install the Python extension when I click on a Python file. Because VS Code will already prompt to install the Python extension, now I get two prompts:

![image](https://user-images.githubusercontent.com/1487073/60395667-3a972000-9b37-11e9-8e43-b0224874f338.png)

I suggest the IntelliCode extension does not prompt to install the Python extension, so the user only gets one prompt.

**Comment by markw-t** [comment]
Thanks @chrisdias - we agree. We'll work to remove the IntelliCode prompt here.

**Comment by WSLUser** [comment]
The top prompt should be removed but the verbage used in the top would be better than the verbage shown in the bottom prompt.

**Comment by qubitron** [comment]
@chrisdias is there ability to customize the wording for the bottom prompt? We have seen in user studies that a stronger language around why this extension is recommended (to get auto-completions, debugging, testing, linting, formatting, refactoring, etc..) would encourage more people to install it.

**Comment by chrisdias** [comment]
@qubitron Can you open a new issue in the `vscode` repo with suggested changes to the wording.

**Comment by jkeech** [comment]
@chrisdias, I'm working on this change now, but I'm not seeing the Python recommendation coming from VS Code. Any ideas why? I turned off the IntelliCode prompt, uninstalled Python, and opened a .py file, but now I'm not getting any prompts to install Python. This is in the extension development host, so I'm not sure if the recommendation logic is different there, but I do see at least one other recommended extension.

I'm hesitant to make this change if we are not guaranteed to have VS Code recommend the Python extension when editing .py files without the extension installed.

**Comment by chrisdias** [comment]
it looks like we don't prompt in the extension development host.  just build the extension, install the `.vsix` manually, and try it locally (outside of the extension development host).  it should prompt.

**Comment by jkeech** [comment]
Thanks, I confirmed that worked. The IntelliCode prompt recommending Python will be removed in 1.1.8.
