### ISSUE TITLE
VSCode version requirement in IntelliCode description misleading

### ISSUE THREAD

**Issue by mmjb** [MicrosoftDocs/intellicode#11]
**VS Code Version**: Any
**OS Version** [macOS/Windows]: Any
**Visual Studio IntelliCode Extension Version**: <= 1.0.3
**Python Extension Version**: Any
**Target Platform or Language** [e.g. Python]: n/a

**Steps to Reproduce / Scenario:**

1. Plugin description says "This extension is only applicable for the July release of Visual Studio Code".
2. However, Plugin works fine with any version after the July release.

**Comment by gewarren** [comment]
@markw-t fyi

**Comment by gewarren** [comment]
@abuchholtzau Can you take a look at this and the other IntelliCode issues, since Mark is out for a bit?

**Comment by abuchholtzau** [comment]
The marketplace page has already been updated to clarify this :)
