### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by zeljko-bulatovic** [MicrosoftDocs/intellicode#110]
- Issue Type: `Bug`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.7`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.36.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 74,
		"activateCallTime": 49,
		"activateResolvedTime": 1090,
		"activationEvent": "onLanguage:typescript"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'toString' of undefined"
		}
	]
}
```

**Comment by jkeech** [comment]
@zeljko-bulatovic, does this happen consistently? When does this error occur? I'm not able to reproduce this issue currently.

**Comment by catycaldwell** [comment]
@zeljko-bulatovic are you able to reproduce this bug?

**Comment by zeljko-bulatovic** [comment]
I was not aware that this issue was open! It seems that vscode opened it automatically in the background. I have no idea about it and how to check.

**Comment by markw-t** [comment]
Thanks for your response @zeljko-bulatovic . If IntelliCode seems to be working well for you at this point, we will close out this issue. 

Before we do so, please can you confirm that you're not seeing any problems with IntelliCode when you're coding (e.g. that you see the "starred" completions in your expected languages (for VS Code this is Python, Java, JS/TS, TSQL - see https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code )

Thanks
Mark
