### ISSUE TITLE
Duplicate notifications in VS Code

### ISSUE THREAD

**Issue by sana-ajani** [MicrosoftDocs/intellicode#111]
**Product and Version** [/VSCode]: 1.37.0-insiders
**OS Version** [macOS]: Mac
**IntelliCode Extension Version**: 1.1.7 
**Target Platform or Language** [e.g. Node.js]:Java

**Steps to Reproduce / Scenario:**

1. Have the intellicode extension installed, not the java extension
2. Open a java file and you see virtually the same notification about installing the Java extension from VS Code and Intellicode 

Can we avoid multiple notifications like this? Or defer to built-in VS Code notifications?

![Screen Shot 2019-07-18 at 10 03 29 AM](https://user-images.githubusercontent.com/9721254/61477154-7b6aa380-a943-11e9-8f17-c016c1f78960.png)

**Comment by jkeech** [comment]
We've recently done the same thing for Python in #107, so this seems reasonable. Is the Java extension pack recommended in all circumstances? E.g. is there anywhere the IntelliCode extension is recommending Java today where the Java extension pack is not currently recommended?

**Comment by sana-ajani** [comment]
I think it's only in the case where they open a .java file and don't have the java extension pack installed already.

**Comment by catycaldwell** [comment]
@sana-ajani are you still experiencing this bug? Or, can we cancel this?

**Comment by sana-ajani** [comment]
Not seeing this anymore.
