### ISSUE TITLE
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. New Update 1.1.8 

### ISSUE THREAD

**Issue by ryaugusta** [MicrosoftDocs/intellicode#113]
Seeing this error appear after I've updated to the newest version of vscode and newest version of Visual Studio Intellicode 

The output I am seeing is:
`Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
, (Error)
No model available for Java, cannot continue.`

I also tried uninstall / reinstall and also installing previous versions - but am seeing the same things.

I tried adding my proxy as well in environment variables but to no avail. 

All the best.

**Comment by vivlimmsft** [comment]
I checked our service logs but don't see any requests in the last 5 days where we returned response code 400.

Could you please try to access the following url through your proxy, and let me know what happens?

**Comment by ryaugusta** [comment]
Sure thing, I followed the link and it took me to a page with the following text:

`{"model":{"id":"45788CA1782FEF17F07049DB4764F5647A62","friendlyName":"Base (Java)","language":"java","analyzer":"intellisense-members"},"output":{"id":"975CC5EC71E347A9B047E779B175B7D3","modelId":"45788CA1782FEF17F07049DB4764F5647A62","targetedInputIds":[],"version":1556898495377,"status":"OutputReady","trainingResults":{"displayClasses":[]},"blob":{"schema":"azureBlobStorage","name":"Output_45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","azureBlobStorage":{"readSasToken":"https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3?sv=2018-03-28&sr=b&sig=FyGyKsGk9cSyZ3%2Bq5%2BWiIOMASo7HTZqReZJg1O2js3Y%3D&se=2019-07-25T18%3A04%3A34Z&sp=r"}},"created":"2019-05-03T15:48:15.3776333Z","updated":"2019-05-03T15:48:15.8082175Z"}}`

**Comment by ryaugusta** [comment]
I also removed the HTTP_Proxy environment variable and removed the NODE_TLS_REJECT_UNAUTHORIZED=0 environment variable and the output has changed to the following: 
`Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: self signed certificate in certificate chain, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: self signed certificate in certificate chain, (Error)
No model available for Java, cannot continue.`

Don't know if that changed anything

**Comment by vivlimmsft** [comment]
Which operating system are you using?

VSCode proxy support for extensions should be enabled by the `http.proxySupport` option, which I believe [is set to `override` by default](https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions). Can you check what it's set to?

Alternatively if that's not working, you can try setting these [proxy settings](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support): `http.proxy`, `http.proxyStrictSSL` and `http.proxyAuthorization`

**Comment by ryaugusta** [comment]
I'm using Windows 10. That `http.proxySupport` option is set to `override` on my side. I'll try setting those proxy settings in visual studio and see

**Comment by jaymanligas** [comment]
Got the same issue.

```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: self signed certificate in certificate chain, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: self signed certificate in certificate chain, (Error)
No model available for Java, cannot continue.
```

also I got this response when directly opening the link above from the browser

`{"model":{"id":"45788CA1782FEF17F07049DB4764F5647A62","friendlyName":"Base (Java)","language":"java","analyzer":"intellisense-members"},"output":{"id":"975CC5EC71E347A9B047E779B175B7D3","modelId":"45788CA1782FEF17F07049DB4764F5647A62","targetedInputIds":[],"version":1556898495377,"status":"OutputReady","trainingResults":{"displayClasses":[]},"blob":{"schema":"azureBlobStorage","name":"Output_45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","azureBlobStorage":{"readSasToken":"https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3?sv=2018-03-28&sr=b&sig=avNMniMBt4DPNulFqHuQXxCCPwWU7JxsGL75OL9bbMA%3D&se=2019-07-30T08%3A46%3A48Z&sp=r"}},"created":"2019-05-03T15:48:15.3776333Z","updated":"2019-05-03T15:48:15.8082175Z"}}`

btw, i'm behind enterprise proxy :(
anyone have solution for this?

**Comment by goateeya** [comment]
same problem here

**Comment by jimboowens** [comment]
same problem here. While I am behind an enterprise proxy as well, I left the network, restarted the machine and vscode, uninstalled and reinstalled Visual Studio Intellicode, and modified the settings.json from `"vsintellicode.modify.editor.suggestSelection": "automaticallyoverrodeDefaultValue",` to`"vsintellicode.modify.editor.suggestSelection": "enabled",`, and those all did not change the result.

**Comment by ryaugusta** [comment]
It looks like the proxy is what the issue is - however I can install many other extensions just fine. I'm not sure what the fix would be for this besides getting off of the proxy and installing the plugin but still I don't think that is a viable solution for all of us. Hopefully the team is looking into a fix.

**Comment by DavidObando** [comment]
Hi, the team is actively looking into solving this issue. We'll come back with an update as soon as we have one.

Thank you for the bug reports.

**Comment by DavidObando** [comment]
A few days ago we released an updated extension (version 1.1.9) to address this issue. Please make sure you take this update if you haven't yet, and do let us know if the issues persist.

**Comment by jubinjose** [comment]
Still same issue with 1.1.9

**Comment by sscde** [comment]
Same problem here!

**Comment by sanket-bhalerao** [comment]
is this the same issue ?
![image](https://user-images.githubusercontent.com/9264813/66561039-494d9400-eb76-11e9-8695-a198c318deab.png)

**Comment by samoretc** [comment]
Hi @sanket-bhalerao , this appears to be a different issue. I've created a new issue [here ](https://github.com/MicrosoftDocs/intellicode/issues/134) to track this bug.

**Comment by ClodoaldoPinto** [comment]
Same problem with version 1.2.0. No problems with the other extensions.

**Comment by kevlar2** [comment]
I have the same issue as above. [Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.] How can I fix this.

**Comment by samoretc** [comment]
@ClodoaldoPinto @kevlar2 Can you provide more details about your setup and your logs in the VSIntelliCode output window in VSCode? I think it may be a different issue.

**Comment by dsyer** [comment]
For me the problem was not a proxy it was a read-only directory where the extension is installed and is trying to create a cache. You can fix that by setting "vsintellicode.modelDownloadPath" explicitly to a writable directory in settings.json.

**Comment by jontat62** [comment]
Yes, for me it looked like a proxy issue, but in reality it was a file permission issue.  When I tried launching vscode as admin, the error disappeared, so I made the change suggested by @dsyer, and now the error is gone from user mode. Thanks!

**Comment by luigli** [comment]
My log:
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: tunneling socket could not be established, statusCode=407, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: tunneling socket could not be established, statusCode=407, (Error)
No model available for Java, cannot continue.

Environment:
VersiÃ³n: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Fecha: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-42-generic

I am under a bussiness proxy that ask me for user/password every time I enter vscode. Could it be possible that Intellicode service ignores proxy configuration when it tries to download models?
Thanks.

**Comment by catycaldwell** [comment]
@ryaugusta are you still encountering this issue?

**Comment by suryapratap** [comment]
I started getting this today morning

![image](https://user-images.githubusercontent.com/956538/92322734-b3a1d980-f050-11ea-95be-22a9f77ba31a.png)

**Comment by markw-t** [comment]
@suryapratap what language are you using when you see this message and can you give more details (eg what shows in your IntelliCode output pane in VS Code)? Did you update anything recently (VSCode, Intellicode or a Language you use?). Thanks!

**Comment by suryapratap** [comment]
@markw-t I was using TypeScript in an Angular 10 project, the popup has stopped as of today without any specific change on my part that can be attributed to this. There were no issues with connectivity yesterday so I do not think net connectivity was the issue.

**Comment by markw-t** [comment]
Thanks for letting us know and sorry for the inconvenience. If this recurs please take a look at the output window for IntelliCode and open a fresh report including that information, and we will take a look.

**Comment by Xiaoyuan18** [comment]
I always see "Couldn't download IntelliCode model. Please check your network connectivity or firewall settings"  these months! I read the reference webpage, and tried every suggestion , but still can't resolve the  problem

**Comment by Xiaoyuan18** [comment]
So, I want to ask,  whether it really reduce the effeciency when  "Couldn't download IntelliCode model. Please check your network connectivity or firewall settings" .

**Comment by yang-zhao** [comment]
This is really upsetting. Python debug failed to launch and I suspected it be the root cause.

**Comment by travisboss** [comment]
> For me the problem was not a proxy it was a read-only directory where the extension is installed and is trying to create a cache. You can fix that by setting "vsintellicode.modelDownloadPath" explicitly to a writable directory in settings.json.

This is what fixed it for me, the folder is inside of a docker container so I moved it to one of my path folders and was able to get it to work.

**Comment by kukuxiahuni** [comment]
check your http.proxy config. Mine is that.

**Comment by Xiaoyuan18** [comment]
您好！
&nbsp; &nbsp; &nbsp; 非常感谢您的提示！
&nbsp; &nbsp; &nbsp; 我分别安装了vs code 与vs code insiders 两个版本在自己手提电脑上。vs code 用的是user版，vs code insiders用的是系统版，前者自动装在了C盘，后者装在了D盘。前者可以自动下载IntelliCode model；后者就总是出错。感觉似乎应该不是proxy设置的问题。如果是proxy设置问题，两个都应该下载不了才对。
&nbsp; &nbsp; &nbsp;我只好把vs code insiders中的IntelliCode extension 给卸载了,使用了下载量较少的IntelliCode insider.
&nbsp; &nbsp; &nbsp;vs code的代码自动提示，是不是不依赖intellicode? 我卸载了IntelliCode与IntelliCode insider之后，仍可以使用代码自动提示。
&nbsp; &nbsp; &nbsp;究竟问题出在哪里，仍是一头雾水。
&nbsp; &nbsp; &nbsp;再次感谢您的指导。
&nbsp; &nbsp; &nbsp;祝：快乐！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;董晓远









董晓远
深圳社科院


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 凌晨0:01
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
主题:&nbsp;Re: [MicrosoftDocs/intellicode] Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. New Update 1.1.8  (#113)

&nbsp;



 
check your http.proxy config. Mine is that.

**Comment by Xiaoyuan18** [comment]
董晓远
深圳社科院


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 凌晨0:01
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
主题:&nbsp;Re: [MicrosoftDocs/intellicode] Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. New Update 1.1.8  (#113)

&nbsp;



 
check your http.proxy config. Mine is that.

**Comment by DavyDeDurpel** [comment]
I just installed the extension on a device outside the corporate network and I copied the 'cache' folder from that one to the corporate one.  Works like a charm.  You can find the cache folder inside C:\Users\<username>\.vscode\extensions\visualstudioexptteam.vscodeintellicode-<extension-version>

**Comment by renjieQ** [comment]
> For me the problem was not a proxy it was a read-only directory where the extension is installed and is trying to create a cache. You can fix that by setting "vsintellicode.modelDownloadPath" explicitly to a writable directory in settings.json.

thanks. It's work for me.

**Comment by ayim** [comment]
Looks like this is working now.

**Comment by kansenchu** [comment]
Hi guys,

I'm getting the following error while trying to download from behind a corporate proxy.

`Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Couldn't reach service Error Message: Socket is closed, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: Socket is closed, (Error)`

If I don't authenticate or don't put in the proxy I get 407 errors, so there's no problem with that. Any leads on what might cause the socket to close?

**Comment by ayim** [comment]
Reopening @vivlimmsft @osobeso @leti367 any idea?

**Comment by ayim** [comment]
@kansenchu looks like we had an outage, mind trying again to see if this works for you?

**Comment by kansenchu** [comment]
@ayim Nope, same error message. It could be something on my end but there aren't enough logs for me to figure out what's going on.

Right now I'm triggering the download by using VSCode's Reload Window function, is there a better way?

**Comment by ayim** [comment]
RIP. None at the moment from the product side other than the fact that we're doing some investigation around #102.

Not sure what language you're writing right now, but you could use our whole-line autocompletions extensions for Python/JS/TS for now - comes packaged with the model. https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions 
^ Certainly works better WITH the main extension though.

@leti367 @osobeso or @vivlimmsft will comment in the AM to help ya out with the main extension.

**Comment by kansenchu** [comment]
A download URL would really help if there's no security concerns on your end ><

**Comment by osobeso** [comment]
@kansenchu Sorry for the inconvenience. We were having intermittent issues with the server but it should be available now.

**Comment by kansenchu** [comment]
@osobeso No change on my end. It could be a problem on my side. If there's a way to get more logs out of vscode I could maybe try and figure it out. I'm trying to get the download URL now to see if the corporate proxy has it blocked for whatever reason.

**Comment by markvivv** [comment]
> For me the problem was not a proxy it was a read-only directory where the extension is installed and is trying to create a cache. You can fix that by setting "vsintellicode.modelDownloadPath" explicitly to a writable directory in settings.json.

Thinks! work for me.

按照这个方法解决了，配置几个位置：
1. vscode设置"http.proxySupport": "override"和"http.proxy": "socks5://127.0.0.1:xxxx"，解决下载的问题
2. 再设置"vsintellicode.modelDownloadPath": "/Users/xxxx/.vscode/vsintellicodemodels"，解决下载成功后提示文件系统只读的问题。错误原文：EROFS: read-only file system, open 'models.json', (Error)
3. 具体的错误原因，通过查看“输出”，选择 VS IntelliCode获得

**Comment by ayim** [comment]
Looks like there was a fix here.
