### ISSUE TITLE
如何更改提示的代码路径？

### ISSUE THREAD

**Issue by YupegLV** [MicrosoftDocs/intellicode#114]
**Product and Version** [VS/VSCode]: 1.36.1
**OS Version** [macOS/Windows]:windows 10.0.17134
**IntelliCode Extension Version**:  1.1.8
**Target Platform or Language** [e.g. Node.js]:python

**Steps to Reproduce / Scenario:**

如图，我只想路径从`OnmyojiScripts`开始，而不是从它的上两级`Onmyoji.Onmyoji_behavior.OnmyojiScripts`开始，应该如何配置？
![image](https://user-images.githubusercontent.com/11402876/61932392-dd678080-afb5-11e9-8911-c023ba0ed7e1.png)

**Comment by YupegLV** [comment]
Product：VSCODE

**Comment by DavidObando** [comment]
Hi YupegLV.

The issue you're showing doesn't appear to be related to IntelliCode. You may want to ensure you're using the Microsoft python language server first. If that's the case and you see issues please refer to the [language server issues page](https://github.com/Microsoft/python-language-server/issues).

**Comment by DavidObando** [comment]
I'll close this issue as it appears to be unrelated to IntelliCode. Please give us more comments if you'd like additional help. Thanks!
