### ISSUE TITLE
[VS Code] Argument completion recommendations for JavaScript

### ISSUE THREAD

**Issue by markw-t** [MicrosoftDocs/intellicode#118]
**Product and Version** [VS/VSCode]:VSCode
**Target Platform or Language** [e.g. Node.js]: JS

Please provide argument completion IntelliCode for JavaScript in VS Code

**Comment by catycaldwell** [comment]
Normalizing labels

**Comment by ayim** [comment]
We now have a form of this through whole line autocomplete in VS Code
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions
