### ISSUE TITLE
When using the Microsoft python language server, the output panel pops up automatically, causing the user to terminate subsequent input.

### ISSUE THREAD

**Issue by czfadmin** [MicrosoftDocs/intellicode#12]
Issue Type: <b>Bug</b>

When modifying a content on an existing python file, once I type dot after some objects, the Microsoft python language server will automatically pop the control panel and place the input focus on the output panel. Because I have to finish the relevant content in the back, but I don't want this unexpected automatic pop-up output panel to terminate my subsequent input behavior.You can add a configuration to let the user set this behavior.This situation will disappear when using Jedi.
##### When I didn't make any changes to my settings:
![python2](https://user-images.githubusercontent.com/13393959/45582384-5f404500-b8e1-11e8-954b-678d5404d6d9.gif)

##### When I use  jedi:
![python3](https://user-images.githubusercontent.com/13393959/45582273-623a3600-b8df-11e8-9d3d-c1b596adc4e4.gif)

Extension version: 1.0.3
VS Code version: Code - Insiders 1.28.0-insider (29e6dce4352db76d8956035990b8630580226588, 2018-09-14T08:23:30.210Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.38GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gewarren** [comment]
Same issue as #9? @markw-t fyi

**Comment by gewarren** [comment]
@jkeech Can someone look at this issue?

**Comment by markw-t** [comment]
Hi @czfadmin  . We believe this may be a problem with the Python language service itself. Please can you raise an issue at https://github.com/Microsoft/python-language-server/issues/  if you are still seeing this behavior?
