### ISSUE TITLE
IntelliCode not working with the Python extension's insiders builds (weekly or daily)

### ISSUE THREAD

**Issue by willfrey** [MicrosoftDocs/intellicode#122]
The latest release of the Python extension replaced the `python.jediEnabled` option with `python.languageServer`, which causes IntelliCode to complain about `python.jediEnabled` not being set since the option no longer exists.

**Product and Version:** VSCode 1.38.0-insider
**OS Version:**: macOS 10.14.16
**IntelliCode Extension Version:**  1.1.9
**Target Platform or Language:** Python

**Steps to Reproduce / Scenario:**

1. Install the Visual Studio Code Python extension
2. Set `"python.insidersChannel": "daily"` or `"python.insidersChannel": "weekly"` in `settings.json`
3. Reload Visual Studio Code if prompted by the Python extension
4. Install the IntelliCode extension
5. Observe that IntelliCode complains about being unable to set `python.jediEnabled`

Thanks for all your hard work! IntelliCode definitely makes my life easier :)

**Comment by willfrey** [comment]
IntelliCode is working again because the Python team reverted the change with https://github.com/microsoft/vscode-python/commit/b996f7a16e7b7821c04d94c92fbf587f80d381da.

Should I close this issue? This solves my problem for the short term.

**Comment by abuchholtzau** [comment]
I'll go ahead and close this! I just needed to confirm this was working for you again. Thank you for letting us know about the issue and glad we got a quick fix in for you :)

**Comment by rickstaa** [comment]
@abuchholtzau @willfrey  Just a quick heads-up, the problem described above is back due to a recent pull request on the [vscode-python](https://github.com/microsoft/vscode-python/pull/11834) repository. Maybe it is an idea to reopen it. Otherwise, I can open a new issue.

**Comment by MikhailArkhipov** [comment]
This is expected. IC is a separate product and 1.2.8 hasn't been release yet. I think if you just add `"python.jediEnabled": "false"`, 1.2.7 will work too. The setting may get grayed or squiggled, but IC most probably will work.

**Comment by rickstaa** [comment]
@MikhailArkhipov Thanks for the explanation, I already assumed that was the case. I will for now just ignore the error I get when having the greyed out `"python.jediEnabled": "false"` command in the settings.json can be ignored.
