### ISSUE TITLE
Feature Request -  intellisense force directed layout in context 

### ISSUE THREAD

**Issue by johndpope** [MicrosoftDocs/intellicode#123]
I know this is likely the 'wrong place' to write this up - and belongs in the vscode bucket.... 
but hear me out.

Feature Request
---------------

**Product and Version** [VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** any
**Steps to Reproduce / Scenario:**

1. When you type there's a square rectangle that pops down with one list of items.
This has augmented to full sentence prediction.

2. Consider however it would be more relevant to display / animate nodes using a force directed layout. 
Here is a  Force Directed Tree 
https://codepen.io/team/amcharts/pen/ZZObva
<img width="804" alt="Screen Shot 2019-10-05 at 4 37 41 am" src="https://user-images.githubusercontent.com/289994/66231467-ec8f4b00-e729-11e9-8f9c-194d96c5518b.png">

https://observablehq.com/@d3/force-directed-graph?collection=@d3/d3-force

WHY? The burden on user being shown irrelevant data could be reduced by hiding stuff based on predicted relevancy ( driven by AI - see mac app ai editor ) - the more relevant nodes could be (transitioned / repulsed / displayed (popped out) faster. Reducing burden of too many results being displayed until a delay time / milliseconds. The more fluent a coder is - the faster.
Other parameters to tweak and fine tune - including opacity, velocity, easing different sizes.

**Eager display of anticipated words / sentences** 
If ai can anticipate an entire matching sentence - rather than being confined to a single drop down list / this node layout gives flexibility to provide a list of nodes chained together. 
Eg. here's a full sentence which is saying 
I predict 1 result given the completing word.
<img width="598" alt="Screen Shot 2019-08-30 at 10 50 27 am" src="https://user-images.githubusercontent.com/289994/63985674-ffec3c80-cb13-11e9-873c-ca07259509c1.png">

But what if we have multiple / parallel sentences that are appropriate?
With the nodes - we can display 2 chains 
 
This is not entirely what I envisage - but it's a starting point.
(obviously the alignment of first node would be directly tied to the word you're typing.)
<img width="1216" alt="Screen Shot 2019-08-30 at 10 55 42 am" src="https://user-images.githubusercontent.com/289994/63985832-c6680100-cb14-11e9-82c7-36fc5e05547f.png">

When user types - 
nodes begin to populate with in context words ( display list as force directed layout)
more prominent complete chains appear to bubble out the side effectively showing a full sentence prediction. 
This navigation / traversal of bubbles using arrows would be critical to ux. 

→ | Rightwards Arrow / provide further predictions in this chain
← | Leftwards Arrow / bubble up / collapse node
↔ | Left-Right Arrow / dive deeper into a predicted chain
↕  navigate parallel "realities" prediction

repulsions / attractions would animate as user navigates to create amazing experience.

We break away from there being just 1 list to being able to provide canvas space of nodes. 
(larger ones perhaps more relevant -> more predictions)

**Comment by johndpope** [comment]
related - https://github.com/agermanidis/livepython/issues/14

**Comment by markw-t** [comment]
Reopening due to erroneous bot closure. Apologies for any confusion

**Comment by ayim** [comment]
I think our new extension addresses this. It does whole line autocompletes and interacts with the IntelliSense menu.
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions
