### ISSUE TITLE
Bug with VS Code Intellicode and Python. Again...

### ISSUE THREAD

**Issue by damnedOperator** [MicrosoftDocs/intellicode#124]
**Product and Version** [VS/VSCode]: VS Code
**OS Version** [macOS/Windows]: Ubuntu
**IntelliCode Extension Version**: 1.1.9
**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1. start vscode
2. try to open any python file.

VS Intellicode Output:
`Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/home/benjamin/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.9/cache/88630A1B4C077752096ECAA576B92C7D3FA1_BC98A65409D042A99DDAF47DC30E1530","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"BC98A65409D042A99DDAF47DC30E1530"}.
Error while activating Python: {}`

Tried to downgrade python. Still happening. Hav now reverted to Current.

**Comment by samoretc** [comment]
Thanks for reporting this issue. I have a few questions about it: 
- What version of VS Code are you using? 
- What version of the Python extension for VSCode are you using? 
- What version of python do you have installed? 
- Have you ever seen IntelliCode completions for python on VSCode? Did it only break after an update of our extension or of VSCode?

**Comment by damnedOperator** [comment]
> What version of VS Code are you using?

Last Stable from Website

> What version of the Python extension for VSCode are you using?
Current 

> What version of python do you have installed?
3.7.4

> Have you ever seen IntelliCode completions for python on VSCode? Did it only break after an update of our extension or of VSCode?
Yes, IC completions worked for some time before breaking permanently after the last 2 updates of VS Code

**Comment by patrys** [comment]
Same here with 1.2.0:

```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/Users/patrys/.vscode-insiders/extensions/visualstudioexptteam.vscodeintellicode-1.2.0/cache/88630A1B4C077752096ECAA576B92C7D3FA1_9BA695AD4C514C32A5D0AC9B02846CD7","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"9BA695AD4C514C32A5D0AC9B02846CD7"}.
Error while activating Python: {}
```

Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.11.47235-dev
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

Name: Visual Studio IntelliCode
Id: visualstudioexptteam.vscodeintellicode
Description: AI-assisted development
Version: 1.2.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

**Comment by morhimi** [comment]
Same here (VS Code Insiders):

```Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_9BA695AD4C514C32A5D0AC9B02846CD7?sv=2018-03-28&sr=b&sig=l3fqjcPRctk4WaxMWDz1mhe7f5usBaRq4HD1onadafE%3D&se=2019-12-08T13%3A23%3A36Z&sp=r
Download complete.
vs-intellicode-python was passed a model: {"modelPath":"/Users/morhimi/.vscode-insiders/extensions/visualstudioexptteam.vscodeintellicode-1.2.0/cache/88630A1B4C077752096ECAA576B92C7D3FA1_9BA695AD4C514C32A5D0AC9B02846CD7","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"9BA695AD4C514C32A5D0AC9B02846CD7"}.
Error while activating Python: {}```

**Comment by oailton** [comment]
I am facing the same problem, but it works with a previous version of the Python extension.

VS Intellicode Output:
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelId":"15708AE89896CA5DF1690433B7A8D93D28B7","modelPath":"c:\\Users\\aandrade\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.7\\cache\\15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9","outputId":"215F8B4FAB1F4663ABD624559FD205B9"}.
Error while activating Python: {"vslsStack":[{},{},{},{},{},{},{}]}



VSCode Stable
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Versions of Related Extensions
visualstudioexptteam.vscodeintellicode: 1.2.7
ms-python.python:
   last known good: 2020.4.76186
   error occurs with versions: 2020.5.78807 and 2020.5.80290

**Comment by MikhailArkhipov** [comment]
@damnedOperator - is this still a problem with Python extension 2020.8+? Might be same as #207

**Comment by damnedOperator** [comment]
As far as I observe, yes, sometimes. Reloading the Window via Command Palette works around that issue.

**Comment by j-i-m-s-t-e-r** [comment]
Same here.  Disabled and unistalled the Visual Studio IntelliCode extension and restarted code, still complains every time I open a py file.

Might have to resintall code.

What a PITA

**Comment by ayim** [comment]
@[damnedOperator](https://github.com/damnedOperator) @j-i-m-s-t-e-r  @damnedOperator @oailton @morhimi 
Have y'all been seeing this issue recently? Would love to hear from you if you have, please feel free to open a new issue.
