### ISSUE TITLE
Failing to Display Parameters or Arguments of Functions from Some Packages

### ISSUE THREAD

**Issue by AeneasZhu** [MicrosoftDocs/intellicode#126]
![image](https://user-images.githubusercontent.com/44701446/64971370-2d8a0180-d8da-11e9-83d0-04fca4b737c1.png)

Unlike Jedi, Intellicode cannot display positonal parameters on functions of some packages like sklearn, imblearn, mxlend, etc. Can this problem be solved?

**Comment by Anapo14** [comment]
Hello! I've filed a separate issue [here ](https://github.com/microsoft/python-language-server/issues/1546)that you can track.

Note: this is an issue related to the Python Language Server not intellicode.

**Comment by catycaldwell** [comment]
closed due to duplicate issue.
