### ISSUE TITLE
Question: which font does the screenshot used?

### ISSUE THREAD

**Issue by 520Chris** [MicrosoftDocs/intellicode#128]
The font that screenshot used is really perfect! Could tell me what it is?

**Comment by markw-t** [comment]
@520Chris we are not sure what screenshot you are referring to. Can you provide a link or copy? Did you intend to raise this as an issue for IntelliCode?

**Comment by 520Chris** [comment]
![image](https://user-images.githubusercontent.com/39628662/66546920-a1819780-eb70-11e9-918d-ff732b71fcda.png)
I am sorry for the late reply. The screenshot I meant is the image on the vscode marketplace.
