### ISSUE TITLE
Intellicode will disable ms-python.python

### ISSUE THREAD

**Issue by Kusina** [MicrosoftDocs/intellicode#13]
**VS Code Version**: 1.27.2
**OS Version** [macOS/Windows]: window 7
**Visual Studio IntelliCode Extension Version**: 1.0.4
**Python Extension Version**: 2018.8.0
**Target Platform or Language** [e.g. Python]: python

**Steps to Reproduce / Scenario:**

1. Install intellicode and then enable 
"ms python-language-server"
will make the python extension fail:
such as python.execInTerminal cannot found
and python.setinterpretor cannot found

After I uninstall intellicode everything is fine.

**Comment by gewarren** [comment]
@abuchholtzau Can you take a look at this one?

**Comment by gewarren** [comment]
@jkeech Can you take a look please?

**Comment by markw-t** [comment]
Hi @Kusina . We believe this may be a problem with the Python language service itself. Please can you raise an issue at https://github.com/Microsoft/python-language-server/issues/  if you are still seeing this behavior?
