### ISSUE TITLE
Fan art

### ISSUE THREAD

**Issue by legomushroom** [MicrosoftDocs/intellicode#130]
<img src="https://user-images.githubusercontent.com/1478800/65979880-f6176b00-e42a-11e9-902f-9f3256a4c543.png" width="640" />

Thank you for the great work! Go IntelliCode!

**Comment by pgroene** [comment]
Thank you for your feedback, we like that you like our work. If you have an suggestion to improve we like to hear it from you!

**Comment by markw-t** [comment]
:-) thanks @legomushroom :-)
