### ISSUE TITLE
Language Support for Java

### ISSUE THREAD

**Issue by laguz81** [MicrosoftDocs/intellicode#132]
**VSCode 1.38.1
**Windows 10 home
**IntelliCode Extension Version**:  1.1.9
**Target Platform or Language** [e.g. Node.js]: Java 

**Steps to Reproduce / Scenario:**

1. After update Not found IntelliCode
2. I follow https://code.visualstudio.com/docs/java/java-tutorial and not found

**Comment by markw-t** [comment]
Hi @laguz81 
Can I clarify what you're seeing - do you get any kind of completions for Java at all? Or are you just not seeing any IntelliCode "stars" for Java?

Are you seeing any error messages, whether in VS Code dialogs or in the VS Code output pane, when you open .java files? You can see the output pane for VS IntelliCode if you have the extension installed, by selecting View...Output Window, then selecting VS IntelliCode in the drop down at the right hand end of the Output pane - this should show messages about IntelliCode activities such as loading models etc. Similarly if language support for Java is running, you should see a Language Support for Java dropdown in the same window, which will show messages concerning Java support.

Thanks
Mark

**Comment by markw-t** [comment]
Hi @laguz81 - since I haven't heard back from you on the questions above we can't take any further action on this bug - if you are still seeing issues with IntelliCode Java support please can you re-open this bug with those details?

Thanks
Mark
