### ISSUE TITLE
Support for use of IntelliCode in Theia IDE

### ISSUE THREAD

**Issue by davemecha** [MicrosoftDocs/intellicode#136]
**Product and Version**: IntelliCode Extension
**Target Platform or Language**: Theia IDE

**Scenario:**

I'm using services like [GitPod](https://gitpod.io/) for developing. The service is based on [Theia IDE](https://theia-ide.org/) which has support of VS Code extensions. I tried to use IntelliCode on GitPod. Unfortunately the models don't get loaded and IntelliCode does not work. I found out, this might be due to licensing issues.

So I want to suggest to add support of Theia-based IDEs to IntelliCode. This could lead to a wider adoption of IntelliCode since there are many IDE projects, where Theia is the base project. (like GitPod, Eclipse Che, Google Cloud Shell)

**Comment by vivlimmsft** [comment]
We do not have any plans to extend the use of IntelliCode beyond Visual Studio, Visual Studio Code, Visual Studio Online, and Azure Data Studio at this time.

[Visual Studio Online](https://online.visualstudio.com/) entered public preview today, includes IntelliCode, and can be used on any device which has a web browser; please consider trying it.

**Comment by pidgeon777** [comment]
I'm also interested in Theia IDE compatibility.

**Comment by markw-t** [comment]
Hi @davemecha , @pidgeon777 . As @vivlimmsft mentioned, we have no plans to extend IntelliCode beyond Visual Studio, Visual Studio Code and [Visual Studio Codespaces](https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-codespaces/).  

I'm closing this issue for that reason, but encourage you to check out [CodeSpaces](https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-codespaces/).

Regards
Mark
