### ISSUE TITLE
Please use the latest version of vscode-extension-telemetry dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [MicrosoftDocs/intellicode#14]
This extension uses version 0.0.17 of `vscode-extension-telemtetry`  module.

The latest version of `vscode-extension-telemtetry` module (0.1.0) uses the latest version of `applicationinsights` module (1.0.6) which has the fix to prevent unnecessary patching of the require and other 3rd party modules. 

For more details, please see https://github.com/Microsoft/vscode-extension-telemetry/issues/16

**Comment by gewarren** [comment]
@markw-t fyi

**Comment by vivlimmsft** [comment]
Updated as of release 1.0.5.

**Comment by ramya-rao-a** [comment]
Hey @vivlimmsft,

Just to confirm, you have updated `vscode-extension-telemtetry` to 0.1.0, correct?
When I logged the issue originally I was suggesting 0.0.22 after which I updated the issue description to 0.1.0

**Comment by vivlimmsft** [comment]
No, it's currently to `0.0.22`. I will update `vscode-extension-telemetry` to `0.1.0` next release.

**Comment by vivlimmsft** [comment]
Fixed this back in VSCode IntelliCode 1.0.6
