### ISSUE TITLE
intellicode sometimes not working or take a long time

### ISSUE THREAD

**Issue by potoo0** [MicrosoftDocs/intellicode#140]
**Product and Version** [VS/VSCode]: VScode 1.40.0
**OS Version** [macOS/Windows]: win10 1903
**IntelliCode Extension Version**: 1.2.0
**Target Platform or Language** [e.g. Node.js]: Python 3.6.4

1. Intellicode sometimes not working:
![image](https://user-images.githubusercontent.com/34411681/68731257-67d9fb80-060a-11ea-875d-ad27e4f40b5c.png) *figure 1*

2. even intellicode can toggle suggest after a long time (approximately 3min at least), intellicode still cannot toggle suggest on python module.
![image](https://user-images.githubusercontent.com/34411681/68731706-f8650b80-060b-11ea-914c-372c31fed530.png)

![image](https://user-images.githubusercontent.com/34411681/68731692-ef743a00-060b-11ea-9e71-cb131b375a7e.png)

`setting.json`:
```
{
    "sync.gist": "xxx",
    "python.jediEnabled": false,
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "workbench.colorTheme": "Monokai Pro",
    "workbench.iconTheme": "Monokai Pro Icons",
    "window.zoomLevel": 0,
    "editor.fontSize": 18,
    "terminal.integrated.inheritEnv": false,
    "extensions.ignoreRecommendations": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": true,
    "python.dataScience.sendSelectionToInteractiveWindow": true,
}
```

**Comment by markw-t** [comment]
@potoo0 thanks for raising this issue. It seems like you are having general issues with IntelliSense completion in Python in VS Code; IntelliCode is a supplementary feature that provides recommendations (the "stars" that raise the most likely completions to the top of the list). The right place to raise general Python IntelliSense issues when using the new Python language server (which I see from your settings you are doing) is on the [Python Language Server](https://github.com/microsoft/python-language-server) repo issues list. They have a [troubleshooting guide](https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md) that can hopefully help you out. 

If you see problems with the IntelliCode "stars" once you have IntelliSense working, please do raise a new bug here!

Thanks
Mark

**Comment by potoo0** [comment]
Thanks.
