### ISSUE TITLE
Add a github action for team completions

### ISSUE THREAD

**Issue by catycaldwell** [MicrosoftDocs/intellicode#142]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. **[Referenced tweet](https://twitter.com/timheuer/status/1196863349377531904?s=20)**
2.

**Comment by catycaldwell** [comment]
Done. :)

**Comment by timheuer** [comment]
Nice!  Reference to doc? @catycaldwell

**Comment by catycaldwell** [comment]
OK! https://github.com/marketplace/actions/intellicode-team-completions
