### ISSUE TITLE
No prompted feedback provided when executing Training commands

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/intellicode#144]
**Product and Version** [VS/VSCode]: Visual Studio 16.4 Preview 5
**OS Version** [macOS/Windows]: Windows
**Target Platform or Language** [e.g. Node.js]: .NET Standard

**Steps to Reproduce / Scenario:**
Using: https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#repository-associated-team-models

1. Go to View...Other Windows...List IntelliCode Models
EXPECT:
Something popping up or window opening showing me the IntelliCode models
ACTUAL:
No feedback.  Have to know to look at Output window.  And then in the Output window I'm not sure what I'm looking at.

**Comment by catycaldwell** [comment]
Thanks for the feedback, @timheuer. We are optimizing for relatively cheap user experience since we don't anticipate many people needing to train their models often (i.e. most users will automatically acquire the model via their team's repo). Would it be more useful for us to automatically open the Output for you to track the IntelliCode training progress OR would you prefer for us to create another UI (i.e. retain the taxonomy of what Other Windows means in VS) specifically for displaying IntelliCode training commands/output?

**Comment by timheuer** [comment]
I would say at a minimum you need to give some user feedback.  Right now that user feedback is hidden.  Popping the output window is minbar and would have drawn my attention.  However within that is just a bunch of output with no explanation so I have to make assumptions.  Making that better is ideal.

We already have a window to potential to use (View...Other Windows...IntelliCode Model Management) which is where I would expect all these actions and results to be displayed.  Not sure why they aren't as that is where all my other models are and where I can create/retrain.

![image](https://user-images.githubusercontent.com/4821/69199152-045d3b80-0aec-11ea-921a-a2265d7cc78b.png)

**Comment by catycaldwell** [comment]
@timheuer, we are currently evaluating whether we should have this "Other Window" for model management, so this may not be a viable option.

**Comment by timheuer** [comment]
@catycaldwell ah that's interesting.  If that window goes away, I would say YES, I would expect a place to see what models I've created, creating, deleting, etc. other than multiple menu commands.

**Comment by catycaldwell** [comment]
@timheuer We've recently previewed our evolved user experience for Custom code completions in Visual Studio. Now, users are able to schedule auto-training models via a gold infobar as well as via the IntelliCode UI. On the IntelliCode UI, all of the other commands relating to the active workspace are available: Delete, List, and Re-train. The new experience removes the necessity for users to navigate to the IntelliCode UI via the View > Other Windows.
