### ISSUE TITLE
Documentation to understand Training output

### ISSUE THREAD

**Issue by catycaldwell** [MicrosoftDocs/intellicode#145]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. Go to Other Windows to train team completions on repo
2. View output and throw hands up to decipher output

**Comment by timheuer** [comment]
Just had to comment that I love Step 2 🤣
