### ISSUE TITLE
IntelliCode is installed automatically

### ISSUE THREAD

**Issue by ruffson** [MicrosoftDocs/intellicode#151]
Issue Type: <b>Bug</b>

Since what feels like a few months I encounter that when opening a new instance of vscode after updating,  "Visual Studio IntelliCode" is installed by default. Although it was not installed before. This is not the case with every launch of a new instance but probably only after having installed a new vscode version.

I don't want IntelliCode (right now). Is there a way to avoid this behaviour? I could not find any setting that would lead to this behaviour in vscode.

Extension version: 1.2.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (6.84GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by markw-t** [comment]
Hi @ruffson  - It may be that you have installed an extension pack that includes IntelliCode's VS Code extension - we are part of several popular ones for Java and Python developers. You can still disable or uninstall the IntelliCode extension in your extension manager if you don't want to use it right now. I would also love to hear more about what leads to you not wanting to use it right now, especially if there might be product improvements we can make to help; let me know here or directly at mwthomas at microsoft dot com.

**Comment by ruffson** [comment]
@markw-t Thank you for your reply and thank you for clearing this up. I will look into this!
The reason why I do not want to use this extension at this point is that I tried it before once and had a really horrible experience in terms of performance. And I am totally content with the setup I have and would rather not compromise on performance. I will give it another shot in the future but am happy to wait a little longer.

**Comment by markw-t** [comment]
Thanks for the info, @ruffson 

When you do give it another shot, I would really appreciate it if you'd drop me a line and let me know how it goes mwthomas at microsoft dot com. If you see any kind of perf issues at all we definitely want to know about it - if this happens please do raise a bug report here.  Out of interest, what sort of perf issues were you seeing? Delays in typing, delays in loading files, or something else? And what language were you seeing the issues in?

Thanks
Mark

**Comment by snuup** [comment]
It is impossible to use Visual Studio for anything without being forced to install Intellicode. *Please* make it possible to not use Intellicode, not being forced to install it, not reenabling it all the time after users disabled it. If I uninstall Intellicode asp.net or desktop development tools are all wiped out as well.

Thank you
