### ISSUE TITLE
Intellicode Swp & ram high usage

### ISSUE THREAD

**Issue by tejassrivastava** [MicrosoftDocs/intellicode#154]
Intellicode plugin hog up all the Swp space as well as a memory. For each new window, 12 new instance of Intellicode appears.

This causes vscode to crash as well as hangs the system.
This can be viewed by running htop.

Attaching images below for reference : 

![vscode_intellicode](https://user-images.githubusercontent.com/12116099/70062415-fb9c5780-160b-11ea-8ed7-5596b4e15d59.png)

![a](https://user-images.githubusercontent.com/12116099/70062475-18d12600-160c-11ea-891c-80b88c94a286.png)

Image after disabling intellicode : 

![b](https://user-images.githubusercontent.com/12116099/70063249-71ed8980-160d-11ea-9edc-e9beb2d0251a.png)

Environment:

OS: Ubuntu 19.10
vscode: v 1.40.2
intellicode: v 1.2.0

**Comment by markw-t** [comment]
@tejassrivastava are you still seeing this issue? Can you give more information about your repro (what language are you using for instance, and do you see this problem all the time?)

**Comment by ayim** [comment]
Going to close this for now. Customers can feel free to re-open if they encounter this
