### ISSUE TITLE
python problem:code analysis is in  progress...

### ISSUE THREAD

**Issue by fangaofeng** [MicrosoftDocs/intellicode#155]
Reporting a Problem
-------------------
django project :

when enter django modul or other modul, can not use code tips.
Always show :code analysis is in progress.., waiting for ten minuts and then code analysis is in progress..

**Product and Version** [VS/VSCode]: 1.40.2
**OS Version** [macOS/Windows]: win 10
**IntelliCode Extension Version**: 0.4.127.0
**Target Platform or Language** [e.g. Node.js]:12.4.0

![无标题](https://user-images.githubusercontent.com/15919475/70296368-61aff700-1825-11ea-8426-5a84fae5c454.png)

**Comment by vivlimmsft** [comment]
This isn't an IntelliCode issue, can you please reopen it on the python-language-server repo?
https://github.com/Microsoft/python-language-server/issues
