### ISSUE TITLE
Python(parser-16) error for use of if condition in fstring

### ISSUE THREAD

**Issue by yumasheta** [MicrosoftDocs/intellicode#160]
### Environment Data

    VS Code Version: 1.41.1
    OS: Linux x64 5.4.7-arch1-1
    Python Extension version: 2019.11.50794
    Visual Studio IntelliCode version: 1.2.2
    Python version: 3.8.1

### Description of the Problem

The following line of code produces two errors:
```python
f'{x if x == 1.0 else 0}'
```
```
unexpected token '=' Python(parser-16)
f-string: expecting '}' but found '1' Python(parser-16)
```

The use of fstrings as shown above is completely correct (syntax wise).

When using the default linting of the [vscode python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) with the 'jedi' engine, there is now error linted for the exact same line of code.

#### Remarks
Sorry for the edit. I hit enter unintentionally and the issue got posted before I finished writing.

**Comment by markw-t** [comment]
This appears to be an issue with the Python language service rather than with IntelliCode. 

Please can you file it at https://github.com/Microsoft/python-language-server/issues as this repo is for IntelliCode issues.

Thanks!

**Comment by yumasheta** [comment]
Filed the same issue at [IntelliCode issues](https://github.com/microsoft/python-language-server/issues/1862)
Thanks for the reply.

**Comment by markw-t** [comment]
Thanks. Closing this here as it's now tracked elsewhere. 

Thanks for using IntelliCode!
