### ISSUE TITLE
dotdotdot insert snippet bug

### ISSUE THREAD

**Issue by Norfeldt** [MicrosoftDocs/intellicode#161]
**Product and Version** [VS/VSCode]: 1.41.1
**OS Version** [macOS/Windows]: macOS
**IntelliCode Extension Version**: 1.2.3
**Target Platform or Language** [e.g. Node.js]: NodeJS

**Steps to Reproduce / Scenario:**

It keeps inserting these promises methods when trying to type a spread (`...`)

![dotdotdot issue](https://user-images.githubusercontent.com/678806/72393292-bc951200-3732-11ea-83e3-f4cf9c5bcd7f.gif)

**Comment by vivlimmsft** [comment]
Could you please attach a source file that we can use to reproduce this? I need the surrounding context so that I'll get the same recommendation for `.catch` that you're seeing.

**Comment by NorfeldtAbtion** [comment]
```
const Asana = require('asana');
const util = require('util');

// Using a PAT for basic authentication. This is reasonable to get
// started with, but Oauth is more secure and provides more features.

var client = Asana.Client.create().useAccessToken(process.env.ASANA_PAT);

client.users.me()
  .then(user => {
    const userId = user.gid;
    // The user's "default" workspace is the first one in the list, though
    // any user can have multiple workspaces so you can't always assume this
    // is the one you want to work with.
    const workspaceId = user.workspaces[0].gid;
    return client.tasks.findAll({
      assignee: userId,
      workspace: workspaceId,
      completed_since: 'now',
      opt_fields: 'id,name,assignee_status,completed'
    });
  })
  .then(response => {
    // There may be more pages of data, we could stream or return a promise
    // to request those here - for now, let's just return the first page
    // of items.
    return response.data;
  })
  .filter(task => {
    return task.assignee_status === 'today' ||
      task.assignee_status === 'new';
  })
  .then(list => {
    console.log(util.inspect(list, {
      colors: true,
      depth: null
    }));
  })
  .catch(e => {
    console.log(e);
  });
```

Try to make a spread in the `.then`

**Comment by NorfeldtAbtion** [comment]
> Could you please attach a source file that we can use to reproduce this? I need the surrounding context so that I'll get the same recommendation for `.catch` that you're seeing.

@vivlimmsft can you reproduce the same dotdotdot issue that I'm seeing?

**Comment by markw-t** [comment]
@vivlimmsft @minestarks @uniqueiniquity have you guys ever been able to reproduce @NorfeldtAbtion 's issue? @NorfeldtAbtion  are you still seeing it on recent builds of VS Code and IntelliCode?

**Comment by Norfeldt** [comment]
@markw-t Yes, I'm still seeing this bug.

I created a new `bug.js` on my desktop, restarted to update vscode (1.47.3), copy pasted the code and started typing

![Jul-28-2020 13-04-08](https://user-images.githubusercontent.com/678806/88657897-dd232900-d0d2-11ea-8922-1c995e6e2b7a.gif)

**Comment by markw-t** [comment]
@Norfeldt thanks for letting us know. Tagging @minestarks , @uniqueiniquity and @vivlimmsft to see this repro.

**Comment by uniqueiniquity** [comment]
Hi @Norfeldt,

Thank you for your patience on this! I've identified a fix and it should be available in a future update to the IntelliCode extension.

**Comment by Norfeldt** [comment]
It works 👌
