### ISSUE TITLE
No intellicode "output windows" after error 

### ISSUE THREAD

**Issue by ccharp** [MicrosoftDocs/intellicode#162]
**Product and Version** [VS/VSCode]: 1.36.1
**OS Version** [macOS/Windows]: macos 10.15.2
**IntelliCode Extension Version**: 1.2.4
**Target Platform or Language** [e.g. Node.js]: java

**Steps to Reproduce / Scenario:**

1. start remote ssh session
2. see error: "Sorry, something went wrong activating IntelliCode support for Java. Please check the "Language Support for Java" and "VS IntelliCode" output windows for details."

However, no "output windows" exist.

**Comment by vivlimmsft** [comment]
To show the output window, `View -> Output`
Then you can select "VS IntelliCode" and/or "Language Support for Java" from this combo box to switch to the window you want to look at.
![image](https://user-images.githubusercontent.com/27872315/72642415-2b37c280-3921-11ea-8c14-bb5ef02e354f.png)

**Comment by ccharp** [comment]
I see, yes, thank you. I was letting my frustration get the best of me.

If it is useful, while I debug, here is the actually error I am seeing:
`Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"/home/ccharpen/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.2.4/cache/45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
Java Extension fails to activate.
Error while activating Java: {}. If vscode-java failed to activate, try these troubleshooting steps: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting
`

**Comment by vivlimmsft** [comment]
Seems like the Java extension failed to activate, so IntelliCode wasn't able to ask it to load our plugin.

Do you see any errors in the "Language Support for Java" output window?

**Comment by mminhe** [comment]
Sorry; how was this issue fixed? I just ran into exactly the same issue with "VS IntelliCode" Output window showing the same message, and there is no "Language Support for Java" output window.
