### ISSUE TITLE
Quick fix to create a local variable

### ISSUE THREAD

**Issue by rustyx** [MicrosoftDocs/intellicode#163]
This is a request to implement quick fix / refactoring shortcuts for

* Create local variable
* Create field
* Create parameter

Like it is done in **Eclipse**:

![eclipse quick fixes java](https://rustyx.org/temp/eclipse-java-create-local-variable.gif)

##### Steps To Reproduce

1. Write a small program `int x = 1;  y = x;`
2. Place the cursor at `y`, press `Ctrl`-`.`
3. It should be possible to deduce and auto-fill the type of variable `y`.

##### Current Result

* Change modifiers to final where possible
* Move...

##### Expected Result

* Create local variable
* Create field
* Create parameter
* Change modifiers to final where possible
* Move...

##### Environment

- Visual Studio Code version: 1.41.1
- Java extension pack version: 0.8.1
- Visual Studio IntelliCode version: 1.2.4

**Comment by Eskibear** [comment]
![Screen Shot 2020-07-24 at 1 20 23 PM](https://user-images.githubusercontent.com/2351748/88362808-7939f100-cdb0-11ea-9270-fdf66ff7b3ec.png)

already supported in the latest java extension.

**Comment by markw-t** [comment]
@rustyx I'm pleased to report that [Visual Studio Code for Java Developers ](https://code.visualstudio.com/docs/java/java-tutorial) now supports these features! Install the latest version and check them out.

Regards
Mark
