### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by gopinath-ts** [MicrosoftDocs/intellicode#167]
Issue Type: <b>Bug</b>

not sure the reason behind unexpected failure

Extension version: 1.2.4
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by vivlimmsft** [comment]
Hi, can you please add more information and/or screenshots about what failure you're seeing?

**Comment by wlgrd** [comment]
Maybe this #5054? I keep struggling with that one

**Comment by wlgrd** [comment]
Maybe this https://github.com/microsoft/vscode-python/issues/5054 ? I keep battling with this one

**Comment by markw-t** [comment]
Hi @gopinath-ts - without any further info this is going to be difficult to pursue any further. I'm closing this bug; if you are still hitting this issue please can you give us some more info (e.g. contents of your VS Code IntelliCode output log, screenshot of the problem, details of language you were using at the time?) that will help us debug.

Thanks for using IntelliCode!
Mark
