### ISSUE TITLE
TypeScript and JavaScript language feature fails

### ISSUE THREAD

**Issue by justisGipson** [MicrosoftDocs/intellicode#168]
Issue Type: <b>Bug</b>

Extension constantly fails after latest VSC update

Error: The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

I know the error isn't related to Visual Studio Intellicode, but there's no option for the failing extension to be selected.

Extension version: 1.2.5
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by uniqueiniquity** [comment]
Hi @justisGipson, did you mean to close this issue?

If not, could you send repro steps for the issue? I'm not able to repro with the same VS Code and extension versions.

**Comment by justisGipson** [comment]
I did. The issue wasn't with the intellicode extension. Thanks.
