### ISSUE TITLE
No more suggestions after some update

### ISSUE THREAD

**Issue by crystalfp** [MicrosoftDocs/intellicode#169]
Issue Type: <b>Bug</b>

After upgrading VSCode and/or extensions (I don't remember) I have no more starred suggestions in Typescript source files.
To reproduce: type `console.` and in the autocompletition list there are no starred items and `log` is down in the list where usually is.
I'm using typescript from VSC.
Thanks for looking!
mario

Extension version: 1.2.5
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.38GB free)|
|Process Argv|--file-uri file:///d%3A/Projects/IdeaIgniterEnvironment/IdeaIgniterEnvironment.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>
<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
spellright|ban|3.0.50
github-markdown-preview|bie|0.0.2
markdown-footnotes|bie|0.0.7
markdown-yaml-preamble|bie|0.0.4
vscode-toggle-quotes|Bri|0.3.2
refactorix|chr|0.3.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.0.15
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.1
vscode-great-icons|emm|2.1.47
vscode-todo-plus|fab|4.14.1
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.167
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.21.0
prettify-json|moh|0.0.3
tab-cycle|mpo|1.0.1
notepadplusplus-keybindings|ms-|1.0.5
leaper|Onl|0.6.0
vscode-jscpd|pau|0.3.4
vscode-versionlens|pfl|0.24.0
bib|phr|0.3.0
vscode-javascript-booster|sbu|0.11.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.2
unique-window-colors|stu|1.0.51
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.5
highlight-bad-chars|wen|0.0.3
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.7.0

(2 theme extensions excluded)

</details>

**Comment by uniqueiniquity** [comment]
Thanks for reporting the issue! I'm not able to naively reproduce with VS Code 1.42.1 and IntelliCode 1.2.5 on Windows. Could you please repro the issue, select "TypeScript: Open TS Server log" from the command palette, and attach the resulting file here?

**Comment by crystalfp** [comment]
Solved.

The problem was that clicking on the typescript version shows no version selected and (see below) the version in use is from my project node_modules (also at version 2.7.5). When I selected "Use VS' code version 2.7.5" the stars reappear!

Typescript log output:
```
«Launching VSCode»
[Info  - 08:31:46.108] Using tsserver from: d:\Projects\<my project>\node_modules\typescript\lib
[Info  - 08:31:46.212] <syntax> Forking...
[Info  - 08:31:46.219] <syntax> Starting...
[Info  - 08:31:46.221] <semantic> Forking...
[Info  - 08:31:46.227] <semantic> Starting...
«Discovered no ts version selected and changed to VSC provided one»
[Info  - 08:33:03.804] Killing TS Server
[Info  - 08:33:03.805] Using tsserver from: c:\Users\Mario Valle\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 08:33:03.812] <syntax> Forking...
[Info  - 08:33:03.820] <syntax> Starting...
[Info  - 08:33:03.824] <semantic> Forking...
[Info  - 08:33:03.831] <semantic> Starting...
```
I think a note should be added in the extension's documentation stating that it works only with VSCode provided typescript (or fixing why it does not works with other typescripts same or more recent version).
Thanks!
mario
