### ISSUE TITLE
Symbol (function/method) identification is incorrect

### ISSUE THREAD

**Issue by bharath144** [MicrosoftDocs/intellicode#17]
Issue Type: <b>Bug</b>

If a method or function is decorated, when that method is looked up, the location is shown incorrectly. 

### This works
def some_func()
  ...

### This doesn't
@some_decorator()
def some_func()
  ...

Some other line in the code gets highligted when the method is selected from the list (Ctrl + Shift + O). Also the method is incorrectly identified as a dictionary.

Extension version: 1.0.5
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz (4 x 1998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (11.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

**Comment by markw-t** [comment]
Hi @bharath144  - thanks for raising this issue.

The problem you're describing is actually with the new Python Language Service - please can you raise it at  https://github.com/Microsoft/python-language-server ?

Thanks

**Comment by bharath144** [comment]
Hello,

I wasn't aware of that. I chose the option to report a bug from VS Code directly (by selecting the extension) and that got me here. I have reported a bug there. 

Should this bug be marked invalid or something like that?

Best,
Bharath

> Hi @bharath144 - thanks for raising this issue.
> 
> The problem you're describing is actually with the new Python Language Service - please can you raise it at https://github.com/Microsoft/python-language-server ?
> 
> Thanks

**Comment by markw-t** [comment]
Thanks @bharath144 . I'll close this bug out, assuming you've reported with Python already, at https://github.com/Microsoft/python-language-server/issues/
