### ISSUE TITLE
IntelliCode breaks code completion for JavaDoc on methods

### ISSUE THREAD

**Issue by beckermarc** [MicrosoftDocs/intellicode#170]
IntelliCode breaks code completion for JavaDoc on methods.
It looks like it is a regression of an already fixed bug https://github.com/MicrosoftDocs/intellicode/issues/72

After disabling IntelliCode in my workspace code completion of such comments work as expected.

How to reproduce: 
Create a java file with
```
/**|  Javadoc completion no longer works here
public static void main(String[] args) {}
```

Versions used:
visualstudioexptteam.vscodeintellicode: 1.2.5
redhat.java: 0,57,0

**Comment by Eskibear** [comment]
<img width="448" alt="Screen Shot 2020-02-24 at 10 05 58 AM" src="https://user-images.githubusercontent.com/2351748/75124926-57e3b480-56ed-11ea-9edf-aca27380e526.png">

I cannot reproduce it. Could you follow [this guide](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) to check the log, and attach the response for command "java.intellicode.completion"?

E.g. see below
<details>
<summary> my request/response</summary>
<pre><code>

[Trace - 10:10:28 AM] Sending request 'workspace/executeCommand - (319)'.
Params: {
    "command": "java.intellicode.completion",
    "arguments": [
        {
            "textDocument": {
                "uri": "file:///path-to-file/Main.java"
            },
            "position": {
                "line": 10,
                "character": 6
            },
            "context": {
                "triggerKind": 1,
                "triggerCharacter": "*"
            }
        }
    ]
}

[Trace - 10:10:28 AM] Received response 'workspace/executeCommand - (319)' in 595ms.
Result: {
    "isIncomplete": false,
    "items": [
        {
            "label": "Javadoc comment",
            "kind": 14,
            "documentation": " * @param args\n",
            "sortText": "999999999",
            "filterText": "Javadoc comment",
            "insertTextFormat": 2,
            "textEdit": {
                "range": {
                    "start": {
                        "line": 10,
                        "character": 6
                    },
                    "end": {
                        "line": 10,
                        "character": 6
                    }
                },
                "newText": "\n * ${0}\n * @param args\n"
            },
            "data": {
                "rid": "0",
                "uri": "file:///path-to-file/Main.java",
                "pid": "0"
            }
        }
    ]
}

</code></pre>
</details>

**Comment by beckermarc** [comment]
Sorry, I was wrong. It is actually working. I was just pressing enter to fast, before the suggestion for the completion showed up. Maybe enabling IntelliCode affects the performance of such code suggestions and that's why it "worked" after disabling IntelliCode.
