### ISSUE TITLE
Can't find cached model in the offline mode

### ISSUE THREAD

**Issue by alkaideemo** [MicrosoftDocs/intellicode#172]
Issue Type: <b>Bug</b>

*My vscode and extensions work well with the Internet. But if I cut off my Internet, I got the error message:*
Couldn't reach service Error Message: connect ECONNREFUSED 127.0.0.1:1080, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.

*I checked the cached models, it has been downloaded in my computer.*

Extension version: 1.2.5
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 6.1.7601

**Comment by patrick984** [comment]
I have the exact same issue. 

Extension Version 1.2.6
VS Code version: 1.43.1
OS Version: Windows_NT x64 10.0.18363

**Comment by ayim** [comment]
@patrick984 @alkaideemo thanks for filing this issue.
We'd love to hear from you if you're still seeing problems - feel free to file a new bug!
