### ISSUE TITLE
intellicode does not working on anonymous class method (Java)

### ISSUE THREAD

**Issue by adamvscele** [MicrosoftDocs/intellicode#173]
![image](https://user-images.githubusercontent.com/6405610/75602112-198b3280-5afd-11ea-9e33-93ac4fbb48a1.png)
when I select “initialValue” method,Intellicode generates these:
![image](https://user-images.githubusercontent.com/6405610/75602154-8dc5d600-5afd-11ea-944f-9a108f672ea2.png)
Oh！MyGod，what's Wrong?

**Comment by Eskibear** [comment]
I can reproduce it, but it's not an IntelliCode issue. After disabling IntelliCode, it's the same.

**Comment by adamvscele** [comment]
It's may be VSCode's problem ? Can you solve the problem，It's so  inconvenient

**Comment by Eskibear** [comment]
I've created an issue in the correct place, you can track it there.

**Comment by adamvscele** [comment]
Okay，Thank you
