### ISSUE TITLE
not working in VSCODE /win10 64bit/python ，IntelliCode deep Learning model enabled

### ISSUE THREAD

**Issue by trotsky1997** [MicrosoftDocs/intellicode#175]
in VSCODE /win10 64bit/python ，IntelliCode deep Learning model enabled and disabled：

the python language server report:

[Error - 上午2:01:11] Exception in IntelliCode extension for Microsoft Python Language Server: System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Boolean overwriteFiles)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaModelLoader.LoadModel(String modelPath, ILogger logger, IDictionary`2& tokenIdMap, IList`1& tokens, InferenceSession& session, PythiaModelMetaData& modelMetaData)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.<LoadModel>b__18_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(IDocumentAnalysis analysis, CompletionList completionList, SourceLocation location, Int32 recommendataionLimit, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtension.HandleCompletionAsync(IDocumentAnalysis analysis, SourceLocation location, CompletionList completionList, CancellationToken token)
[Error - 上午2:01:11] For more information about IntelliCode deep learning model, see https://aka.ms/intellicode/vscode-experiments

**Comment by osobeso** [comment]
Hi @trotsky1997 
It seems something went wrong with the downloaded model, as it might be corrupted.
Could you please provide us with your VS IntelliCode models cache folder so we can inspect further?

This is located in the following path:
%USERPROFILE%\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.5\cache

Current version is 1.2.5 but this can change for you, so please just send us whatever version you have cached.

Once you find the cache, please send it to us for inspection.
You can also try deleting the cache folder and try loading it again to see if the error persists.

Regards!
Oscar.

**Comment by frostime** [comment]
I met with the same problem. I check the path %USERPROFILE%\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.5\cache，and got some files under the directory:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2020/3/7     13:38        1818049 15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F                                                  4663ABD624559FD205B9
-a----         2020/3/9      0:05          64962 45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E3                                                  47A9B047E779B175B7D3
-a----         2020/3/9     21:00           1136 models.json
```
I open the `model.json`, and check the content:
```json
[
    {
        "analyzerName": "intellisense-members-lstm",
        "languageName": "python",
        "identity": {
            "modelId": "15708AE89896CA5DF1690433B7A8D93D28B7",
            "outputId": "215F8B4FAB1F4663ABD624559FD205B9",
            "modifiedTimeUtc": "2019-12-13T22:18:51.237Z"
        },
        "filePath": "c:\\Users\\ZuoYiping\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.6\\cache\\15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9",
        "lastAccessTimeUtc": "2020-03-09T12:57:33.079Z"
    },
    {
        "analyzerName": "intellisense-members",
        "languageName": "java",
        "identity": {
            "modelId": "45788CA1782FEF17F07049DB4764F5647A62",
            "outputId": "975CC5EC71E347A9B047E779B175B7D3",
            "modifiedTimeUtc": "2019-05-03T15:48:15.808Z"
        },
        "filePath": "c:\\Users\\ZuoYiping\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.6\\cache\\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3",
        "lastAccessTimeUtc": "2020-03-09T07:24:45.607Z"
    }
]
```
Although everything looks just ok,  I stilll got the `System.IO.InvalidDataException` once I type something in the editor, and the Intellisense dosn't work as well as I wish, it failed to offer enough help when I try do write a tensorflow program for exmaple.

![tmp](https://user-images.githubusercontent.com/27268127/76218083-882f6500-624e-11ea-9176-565d020ae4fa.gif)

**Comment by osobeso** [comment]
@frostime Hi, thanks for the information provided.
The size of the python model seems odd, as it should be around 30 MB, yours seems to be around 18, so my best guess it's that it probably had an issue while downloading.

Could you try deleting it and re-opening VSCode to download it again?
File name should be '15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9' 
Regards!

**Comment by dafengz** [comment]
@osobeso 
Dear sir, is it possible to downloading the python model file manually? Every time when I open vscode,  the status-bar at the bottom would display “Downloading Intellicode models: Downloading Intellicode models”. But it never succeed.

![Status-bar shoot](https://user-images.githubusercontent.com/58198611/76480604-2dfaf380-644a-11ea-8eda-371b1be78bec.png)

![model folder shoot](https://user-images.githubusercontent.com/58198611/76480711-83370500-644a-11ea-9baf-c3bb4df5b642.png)

**Comment by trotsky1997** [comment]
> Hi @trotsky1997
> It seems something went wrong with the downloaded model, as it might be corrupted.
> Could you please provide us with your VS IntelliCode models cache folder so we can inspect further?
> 
> This is located in the following path:
> %USERPROFILE%\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.5\cache
> 
> Current version is 1.2.5 but this can change for you, so please just send us whatever version you have cached.
> 
> Once you find the cache, please send it to us for inspection.
> You can also try deleting the cache folder and try loading it again to see if the error persists.
> 
> Regards!
> Oscar.

I find the ultimate method to figure that ,Because of the interrupt in model‘s downloading，the model file was corrupt，So the python language server report a failure when it unzip the model file (ZipArchive).
Now it's the method to figure that,just delete all the files in the cache folder 
[C:\Users\\ **your username** \\.vscode\extensions\christian-kohler.path-intellisense-1.4.2/cache/ ]
,than reload the VScode, VS intellicode would redownload the model file again,after its completion,the problem would be vanish.
BUT! if an interrupt happend again in model‘s downloading,you should delete those files again,and retry.it may cost many times if you were in a bad net envoirment .


My advice to this problem is **add a validating process to your plugin,when the model file have been downloaded,Just validating its md5 or crc code to ensure its integrity** to avoid this problem.
Thanks for your great work!
It's working fine in my IDE now.

**Comment by trotsky1997** [comment]
> @frostime Hi, thanks for the information provided.
> The size of the python model seems odd, as it should be around 30 MB, yours seems to be around 18, so my best guess it's that it probably had an issue while downloading.
> 
> Could you try deleting it and re-opening VSCode to download it again?
> File name should be '15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9'
> 
> PS. We just updated to V 1.2.6 so probably your folder structure has changed
> 
> Regards!

The model.json should also be deleted.

**Comment by ayim** [comment]
Looks like this was resolved. @dafengz @trotsky1997 let us know if this is not the case.
