### ISSUE TITLE
为什么下载microsoft python language server特别慢？

### ISSUE THREAD

**Issue by skenoy** [MicrosoftDocs/intellicode#176]
为什么下载microsoft python language server特别慢？用的100M带宽，必须要科学上网吗？？？？？？？？？？？？？？？？

Extension version: 1.2.6
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by markw-t** [comment]
Hi @skenoy 

this seems to be a question regarding download performance of the Python language server - please can you refer the issue to https://github.com/Microsoft/python-language-server/issues ?

Thanks
Mark Wilson-Thomas
Program Manager, Visual Studio IntelliCode

**Comment by yahkun** [comment]
You should set the proxy in vscode settings!
