### ISSUE TITLE
Support for complete offline mode

### ISSUE THREAD

**Issue by ccarv** [MicrosoftDocs/intellicode#177]
**Product and Version**: 1.41.0
**OS Version**: macOS
**IntelliCode Extension Version**: 1.2.6
**Target Platform or Language**: Java

**Steps to Reproduce / Scenario:**

1. Navigate to `.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.6/`
2. Locate model

One of my contracts computer is completely offline. I do not have means of downloading extensions directly via the Marketplace. I had to migrate my extensions from one machine to the other. Everything works great except for the one that matters; the intellicode extension.

The model is unable to download and thus does not provide any form of autocompletion. I have looked at multiple issues with similar scenarios and notice references to a "model" blob file. I cannot find the model anywhere on my MacBook. Where can I locate this file so that I can migrate it over?

**Comment by trotsky1997** [comment]
Copy your cache/model.json to your new computer.

**Comment by markw-t** [comment]
#102 covers this case
