### ISSUE TITLE
Intellicode not showing suggestion 

### ISSUE THREAD

**Issue by babul7154** [MicrosoftDocs/intellicode#180]
**Product and Version** [VS/VSCode]:1.43.2
**OS Version** [macOS/Windows]:window 10 x64(1909)
**IntelliCode Extension Version**: 1.2.6
**Target Platform or Language** [e.g. Node.js]:Python 3.7.3 64 bit

**Steps to Reproduce / Scenario:**

1.import numpy as np
2.x=x = np.array([1, 2, 3])
please goto to this link for more info
https://github.com/microsoft/python-language-server/issues/1976

**Comment by catycaldwell** [comment]
Hi @babul7154, thank you for providing this feedback. I'm one of the Program Managers on IntelliCode and currently investigating your issue. Could you let me know which Python Language Server is active? 

You can find the active Python Language Server by heading to **Settings** (the gear in bottom left of Visual Studio Code). 

![image](https://user-images.githubusercontent.com/908768/78044795-fcc76200-7329-11ea-9cd8-88299e857dea.png)

**Comment by babul7154** [comment]
I am using Microsoft Python language server.
![language server](https://user-images.githubusercontent.com/46845524/78097263-78dcab00-73f9-11ea-94a8-6b5709f8661a.PNG)
![python](https://user-images.githubusercontent.com/46845524/78097267-7b3f0500-73f9-11ea-99dc-08917b6ec587.PNG)

**Comment by MikhailArkhipov** [comment]
@babul7154 - have you tried new Pylance language server? https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance.

**Comment by pJoengw** [comment]
> @babul7154 - have you tried new Pylance language server? https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance.

I have used Pylance,  but I have the same error like above

**Comment by MikhailArkhipov** [comment]
@babul7154 - if you are not getting completions with Pylance, then there won't be any IntelliCode suggestions. IntelliCode is not a completion engine, it works over Pylance or Microsoft server completions. I would suggest filing issue with Pylance at https://github.com/microsoft/pylance-release.

This does not seem to be IntelliCode issue, but rather the underlying language server issue.

**Comment by ayim** [comment]
Going to close this for now, since Microsoft and Jedi language servers are deprecated.
Customers are welcome to re-open if they're continuing to experience with Pylance
