### ISSUE TITLE
No suggestion for method returning 'self'

### ISSUE THREAD

**Issue by PeSoski** [MicrosoftDocs/intellicode#181]
**Product and Version** : VSCode 1.43.2
**OS Version**: Windows
**IntelliCode Extension Version**:  1.2.6
**Target Platform or Language**: Python

Hi, i have simple class:
```
class simpleA():
    def __init_(self):
        ...
 
    def method1(self):
        print 'hello'
        return self

    def method2(self)
        print 'world'
        return self
```

example:
`simpleA().` -> suggestion: method1/method2
`simpleA().method1().` -> no suggestions ;(

Is there chance to show suggestionst for methods returning `self`?

**Comment by XCMer** [comment]
It does seem to work for me. Do you have both IntelliCode and the Python extensions installed and enabled?

**Comment by PeSoski** [comment]
![image](https://user-images.githubusercontent.com/14888147/79438487-dcf39780-7fd3-11ea-80c9-36d27f716b38.png)

hmm ... 
can you check it inside class :P

```
class simpleA():
   . . .
    def run_all_methods(self)
        self.method1().method2()
```

**Comment by ayim** [comment]
Hi, consider trying the IntelliCode Completions extension.
It should be able to assist here.
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions
