### ISSUE TITLE
Unable to suggest field name in the presence of annotation and compilation errors

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [MicrosoftDocs/intellicode#182]
**Product and Version**: VSCode 1.43.2
**OS Version**: Linux x64 5.4.28-1-MANJARO
**IntelliCode Extension Version**: 1.2.6
**Target Platform or Language**: Java

**Steps to Reproduce / Scenario:**

1. Create a class with a method and with an annotation on it. Do some syntax typo on that method.
2. Add a new field on the class and wait for the field name suggestion.
3. IntelliCode will not be able to suggest the field name.

If you comment out the annotation, it will suggest the field name just fine.

1. Create a class with a method without any annotation on it. Do some syntax typo on that method.
2. Add a new field on the class and wait for the field name suggestion.
3. IntelliCode will suggest the field name just fine.

Here is a gif showing the issue:

![autocomplete](https://user-images.githubusercontent.com/12160864/78182625-f7a70780-743c-11ea-9dc1-451598246302.gif)

**Comment by Eskibear** [comment]
By disabling IntelliCode, I can still reproduce the issue. Suppose to be a bug in upstream project https://github.com/redhat-developer/vscode-java

Could you help open an issue there?

**Comment by rafaelrenanpacheco** [comment]
Hello @Eskibear!

Indeed this problem is not related to IntelliCode, I disabled the extension as well and the problem continues. I'll report this issue on vscode-java repo.

Thanks!
