### ISSUE TITLE
 inconsistent  command emphasizing

### ISSUE THREAD

**Issue by bergano65** [MicrosoftDocs/intellicode#184]
[Enter feedback here]

Open the IntelliCode page by choosing View > Other Windows > IntelliCode Model Management.

Team completions is a preview feature for C# and is disabled by default. It can be enabled through Tools > Options > IntelliCode > C# team models for completions.

 command chains should be bold as remaining article are

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2089e9f-f405-f6a4-2bf2-9da8acfe2885
* Version Independent ID: 56ce5868-6ade-0d11-0038-068ffbcd6841
* Content: [IntelliSense based on your code - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models)
* Content Source: [docs/custom-models.md](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/custom-models.md)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @markw-t
* Microsoft Alias: **mwthomas**

**Comment by markw-t** [comment]
Tagging @catycaldwell who now owns IntelliCode completions (inc model management)
