### ISSUE TITLE
Make Intellicode optional and easy to opt out

### ISSUE THREAD

**Issue by snuup** [MicrosoftDocs/intellicode#185]
Installing Visual Studio more or less forces installing Intellicode. There is no reason to bundle intellicode that strong. Please make it optional and easy to opt out.

Thank you for providing VS community edition for free.

**Comment by markw-t** [comment]
We have changed the way IntelliCode setup works in more recent editions of Visual Studio, and you can now uncheck IntelliCode in the individual components tab of setup before installing if you want to opt out. Hope this helps!
