### ISSUE TITLE
autocomplete for variables and functions inside console.log()

### ISSUE THREAD

**Issue by hefayed** [MicrosoftDocs/intellicode#189]
Hi,

I have a simple question which I couldn't find an answer for , with javascript , Intellisense works perfectly, however I can't seem to find a reason why autocomplete for variables and functions inside console.log() sometimes it works and sometime it doesnt and I dont know why.

Any idea or a pointer to a setting to make it work will be appreciated ?

Regards,
Hesham

**Comment by hefayed** [comment]
Hi,

My settings.json is below

{
  "editor.cursorStyle": "block",
    "editor.wordWrap": "wordWrapColumn",
    "liveServer.settings.CustomBrowser": "chrome",
    "liveServer.settings.donotShowInfoMsg": true,
    "code-runner.runInTerminal": true,
    "window.zoomLevel": 1,
    "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontFamily": "'Hack Nerd Font'",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "code-runner.saveAllFilesBeforeRun": true,
    "code-runner.saveFileBeforeRun": true,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": false,
    "eslint.alwaysShowStatus": true,
    "editor.tabSize": 2,
    "files.autoSave": "afterDelay",
    "editor.suggestSelection": "first",
    "editor.snippetSuggestions": "top",
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.colorCustomizations": {
      "terminal.background":"#131212",
      "terminal.foreground":"#dddad6",
      "terminal.ansiBlack":"#1D2021",
      "terminal.ansiBrightBlack":"#665C54",
      "terminal.ansiBrightBlue":"#0D6678",
      "terminal.ansiBrightCyan":"#8BA59B",
      "terminal.ansiBrightGreen":"#237e02",
      "terminal.ansiBrightMagenta":"#8F4673",
      "terminal.ansiBrightRed":"#FB543F",
      "terminal.ansiBrightWhite":"#FDF4C1",
      "terminal.ansiBrightYellow":"#FAC03B",
      "terminal.ansiCyan":"#8BA59B",
      "terminal.ansiGreen":"#95C085",
      "terminal.ansiMagenta":"#8F4673",
      "terminal.ansiRed":"#FB543F",
      "terminal.ansiWhite":"#A89984",
      "terminal.ansiYellow":"#FAC03B" 
    },
    "jshint.lintHTML": true,
    "jshint.options": {
    
    },
    
    "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": false,
      "editor.quickSuggestionsDelay": 5
    },
    "workbench.editorAssociations": [
    
    ],
    "editor.fontLigatures": true,
    "typescript.tsserver.maxTsServerMemory": 4096,
    "vsintellicode.java.completionsEnabled": false,
    "typescript.surveys.enabled": false,
    "typescript.suggest.completeFunctionCalls": false,
    "typescript.format.enable": false,
    "javascript.validate.enable": false,
    "color-highlight.languages": [

      "*"
    ],
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "kite.showWelcomeNotificationOnStartup": false,
    "kite.pollingInterval": 10,
    "files.associations": {
      
    
    },
  }

**Comment by uniqueiniquity** [comment]
Hi Hesham,

Thank you for reporting this issue!
Could you please provide steps for what you are trying and what you expect to happen?

Thanks!

**Comment by hefayed** [comment]
Hi,

Thank you for reaching out , autocomplete works everywhere except in side a console.log see screen shot

![Screen Shot 2020-04-23 at 2 19 35 PM](https://user-images.githubusercontent.com/13040034/80150822-e8176c00-856d-11ea-95a3-716c0caca214.png)

![Screen Shot 2020-04-23 at 2 20 10 PM](https://user-images.githubusercontent.com/13040034/80150842-f2d20100-856d-11ea-84b7-9b99fb24922a.png)


Regards,
Hesham

**Comment by uniqueiniquity** [comment]
Thank you for the screenshots!
I recommend filing this issue on https://github.com/microsoft/vscode - they will be able to help more with this particular issue.

**Comment by hefayed** [comment]
The below change fix the problem.

"editor.suggest.snippetsPreventQuickSuggestions": false,

**Comment by rohitvishwakarma1819** [comment]
> The below change fix the problem.
> 
> "editor.suggest.snippetsPreventQuickSuggestions": false,

Didn't worked @uniqueiniquity
