### ISSUE TITLE
library functions auto completion

### ISSUE THREAD

**Issue by fsrmlgd** [MicrosoftDocs/intellicode#190]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.Some library functions auto completion is absent in the recommened list

**Comment by ayim** [comment]
@fsrmlgd are the libraries that you're looking for autocompletions from installed and imported?
Let us know if you're still experiencing issues, thanks!

**Comment by ayim** [comment]
Hi @fsrmlgd would love to hear back from you!
Feel free to reopen the issue
