### ISSUE TITLE
IntelliCode causes two linters to be used in Python 3.8.2 on Linux

### ISSUE THREAD

**Issue by wickedjargon** [MicrosoftDocs/intellicode#193]
**Product and Version** [VS/VSCode]: 1.45.0
**OS Version** [macOS/Windows]: Xubuntu 20.04 LTS 
**IntelliCode Extension Version**: 1.2.7
**Target Platform or Language**: Python 3.8.2

**Steps to Reproduce / Scenario:**

1. Install VS Code
2. Install IntelliCode Extension
3. Install Python Extension and set your linter to Pylint (installation of pylint required)
3. IntelliCode extension will automatically add the following to your settings.json file:
`"python.jediEnabled": false,`
This will cause you to have two linters enabled:

![image](https://user-images.githubusercontent.com/11734208/81787367-ebe44180-94ce-11ea-92a3-e1954d29ff9f.png)
Notice, in this image, there are two linters (Pylint and Python). 

Removing the 

`"python.jediEnabled": false,`

from the settings.json file and uninstalling IntelliCode resolves the issue.

**Comment by savannahostrowski** [comment]
Hey @wickedjargon!

Thanks for the feedback. 

By using `python.jediEnabled: false`, you are using the Microsoft Python Language Server as your choice language server. This language server is the responsible for producing the warning level diagnostic on the `test` variable ('Python'). With pylint also being used here, it is expected that duplicate problems could be surfaced. Both of these tools produce diagnostics and so this is not a bug.

One final note: One difference here is that pylint provides both logical and stylistic linting diagnostics, whereas the language server is focused on logical linting.

**Comment by wickedjargon** [comment]
I see what you're saying now. The default behavior is for VS Code to recommend to use pylint and also (once this extension is installed) to use the Microsoft Language Server as a linter. 

Something should be done to avoid this, like add Microsoft Language Server on the linter list.

**Comment by savannahostrowski** [comment]
Thanks again for this suggestion. I'll bring it to my team for further discussion!
