### ISSUE TITLE
Typos in a couple menu options

### ISSUE THREAD

**Issue by wsheemsft** [MicrosoftDocs/intellicode#194]
1. Using VS 2019 16.5.5, "Create a model by going to View &gt; Other Windows &gt; Train IntelliCode model on this repository" should be "Create a model by going to View &gt; Other Windows &gt; IntelliCode Model Management"

2. "Enable the following settings in Tools &gt; Option &gt; IntelliCode" should be "Enable the following settings in Tools &gt; Options &gt; IntelliCode" (options is plural)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d08137ac-1df7-cd5a-dfae-0c9be61b6743
* Version Independent ID: 3b907828-7d0f-26fb-71f0-d84d30e64a92
* Content: [Visual Studio IntelliCode team completions - Quickstart - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/quickstart-team-completions#feedback)
* Content Source: [docs/quickstart-team-completions.md](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/quickstart-team-completions.md)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @catycaldwell
* Microsoft Alias: **ccaldwel**

**Comment by vivlimmsft** [comment]
> Using VS 2019 16.5.5, "Create a model by going to View > Other Windows > Train IntelliCode model on this repository" should be "Create a model by going to View > Other Windows > IntelliCode Model Management"

This is not correct-- that is a different model training flow. We're working towards consolidating them, but right now we have two confusingly parallel ways to train models.

**Comment by wsheemsft** [comment]
Understood.  My mistake was in Tools -> Options -> IntelliCode where I interpreted the value of "Default" to be "Enabled".  Did not realize it was a tri-state.  Setting it to enabled exposed the menu option from the documentation.
