### ISSUE TITLE
Error while activating Python

### ISSUE THREAD

**Issue by nbkgit** [MicrosoftDocs/intellicode#196]
After starting VS code i get this error message from intellicode.

Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelId":"15708AE89896CA5DF1690433B7A8D93D28B7","modelPath":"c:\\Users\\Pedro\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.7\\cache\\15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9","outputId":"215F8B4FAB1F4663ABD624559FD205B9"}.
Error while activating Python: {}

**Comment by savannahostrowski** [comment]
Hey @nbkgit!

Thanks for reaching out. It sounds like the Python extension may not have started.
Can you confirm if the Python extension successfully activated? 

Also, can you provide me with your Python settings:
- Interpreter version
- Extension version
- python.languageServer setting value (and version)

**Comment by nbkgit** [comment]
Extensuion version : visualstudioexptteam.vscodeintellicode-1.2.7

python.languageServer Says default microsoft without version  

the python extension is version 2020.5.80290

I can't tell you if it is now installed correctly.

It was some 1-2 updates ago, when is´ still could debug my code

but know i have also another python related problem, which i have also made an issue out. see https://github.com/tht13/Python-vscode/issues/51

**Comment by nbkgit** [comment]
I posted the log in my other maybe this helps here too https://github.com/tht13/Python-vscode/issues/51#issuecomment-635000588

**Comment by savannahostrowski** [comment]
Thanks for the info! 

I think that this is likely a Python extension-related issue so to simplify tracking this issue, I'd suggest filing an issue to the [official python-vscode repo](https://github.com/microsoft/vscode-python) with the activation issues you are describing, as it looks like you filed that issue to a fork of the extension.

**Comment by nbkgit** [comment]
Thx to savannahostrowski 
After some intensive research and experiment i found the solution
https://github.com/tht13/Python-vscode/issues/51#issuecomment-639092724
