### ISSUE TITLE
Not identifying modules when installed after VSC starts

### ISSUE THREAD

**Issue by yiannis-had** [MicrosoftDocs/intellicode#197]
Issue Type: <b>Bug</b>

- Start VSC
- Load up a python file
- Install a new package
- Won't be identified by Intellicode

Extension version: 1.2.7
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (25.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yiannis-had** [comment]
It's still happening :(

**Comment by ayim** [comment]
Hey @yiannis-had, are you still running into this issue?
Would love to hear from you if you are, feel free to file a new bug!
