### ISSUE TITLE
Intellicode don't show Openpyxl sugestions

### ISSUE THREAD

**Issue by Blotuxs** [MicrosoftDocs/intellicode#199]
Hi

About a month ago Intellicode showed me recommendations for the Openpyxl library in Python. And since a few days ago it does not show all the recommendations (As seen in the image it does not show the Cell recommendation or others).

Try reinstalling Visual Studio Code, Openpyxl, Python and Intellicode but it doesn't work.

Try to delete the Extensions folder and download it again.

Settings:
"python.jediEnabled": false
"python.languageServer": "Microsoft"

I would appreciate any recommendation. Thank, in advance.
![Screenshot (3)](https://user-images.githubusercontent.com/66394989/83702938-845c7600-a5e4-11ea-9130-b3eb7c81f05d.png)

**Comment by Blotuxs** [comment]
Update:

If I dont click on "Enable it and Reload Windows", appear all the suggestions

![Captura de pantalla (9)](https://user-images.githubusercontent.com/66394989/84925734-bb309280-b0a0-11ea-9885-d0eeb65e797d.png)

**Comment by luabud** [comment]
Hi @Blotuxs, this seems to be an issue in the Python extension so I opened an issue on the other repo 😊.

**Comment by markw-t** [comment]
@Blotuxs I'm closing this issue assuming @luabud 's python#12422 covers it. If it doesn't, please let us know!

Thanks
Mark
