### ISSUE TITLE
supporting other languages

### ISSUE THREAD

**Issue by aytacozkan** [MicrosoftDocs/intellicode#2]
will you support other languages such as  java, golang and javascript?

**Comment by k7shanmugam** [comment]
Yes, we are looking into other languages. It is more of an experiment first to see if there is enough data for a given language to learn the patterns and see if the model can make predictions that are better than the default suggestions. If the results are good, we will certainly bring them online.

**Comment by markw-t** [comment]
As @k7shanmugam said, we're keeping our eye on other languages and will have more to say about this as we make progress. I'm closing this issue as I think we've answered the question :-)

Do let us know if there are particular languages beyond the ones listed that you're keen to see included.

Thanks !
Mark
