### ISSUE TITLE
Repeated suggestions

### ISSUE THREAD

**Issue by paterasMSFT** [MicrosoftDocs/intellicode#20]
**VS Code Version**: 1.29.1
**VS Code Inellicode Version**: 1.1.0
**OS Version** [macOS/Windows]: Windows 10
**Target Platform or Language** [e.g. Python]: TypeScript 3.1.4

Seeing many of the same suggestion:

![image](https://user-images.githubusercontent.com/35780775/49532681-16b67900-f88b-11e8-8594-6e22f11dc8c3.png)

They're all repeated exactly 10 times, except stack, which has 9 "stack"s and a "stack?":

![image](https://user-images.githubusercontent.com/35780775/49532976-c7bd1380-f88b-11e8-807b-8e8f23e85577.png)

Not sure how to specifically repro. Just installed the extension and this is the first suggestion I've gotten. Very large code base.

Type type in question is the TypeScript Error interface:

![image](https://user-images.githubusercontent.com/35780775/49533018-e7543c00-f88b-11e8-8edd-e95881cfaa45.png)

![image](https://user-images.githubusercontent.com/35780775/49533079-17034400-f88c-11e8-8769-efd412fecd69.png)

Hope that helps! Thanks for including TypeScript. Really excited about Intellicode, and happy to have the preview.

**Comment by minestarks** [comment]
Thanks for the report. Do you have a lot of `tsconfig.json`s in your project, by any chance? I wonder if the IntelliCode plugin is getting loaded separately for each project.

**Comment by paterasMSFT** [comment]
Yes. There dozens of tsconfig.json files. I'v sent you a message on Teams, if you want to see anything specific.

**Comment by minestarks** [comment]
I'm still trying to hit a repro with your project but haven't been able to. Please feel free to send me logs if ever you hit it again.

**Comment by markw-t** [comment]
@paterasMSFT have you seen this issue again? If not, could you close this issue?
