### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MHDFahz** [MicrosoftDocs/intellicode#200]
intelliCode wasn't able to apply the user setting 'python.jediEnabled': 'false' automatically, please manually set it.
![Screenshot 2020-06-04 at 11 50 07 PM](https://user-images.githubusercontent.com/42516446/83796144-29974d00-a6be-11ea-8aeb-14e337513249.png)

**Comment by MikhailArkhipov** [comment]
@MHDFahz - the setting is no longer needed, it has been deprecated. `python.languageServer` is the setting that controls language engine selection. Thanks.

**Comment by ayim** [comment]
This seems to relate to jedi, which is now deprecated in lieu of Pylance
