### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by joepie91** [MicrosoftDocs/intellicode#201]
According to [the FAQ](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq):

> With IntelliCode, the completion list suggests the most likely correct API for a developer to use rather than presenting a simple alphabetical list of members. To provide this dynamic list, IntelliCode uses the developer's current code context and patterns based on thousands of highly rated, open-source projects on GitHub. The results form a model that predicts the most likely and most relevant API calls.

This means that the prediction model is a derived work from the open-source projects that it was trained on. However, all of the popular open-source licenses require attribution and license reproduction at the very least, and I am unable to find this attribution or any of the licensing information for the IntelliCode model.

Additionally, while this is difficult to establish until the above point is resolved, it is likely that some of the projects that this model was derived from, are licensed under the GPL or another copyleft license. In that case, the source files for the derived work itself (ie. the model) need to be made available under a compatible open-source license. This does not currently appear to be the case, and #31 suggests that the model is explicitly proprietary.

**Comment by catycaldwell** [comment]
Hi @joepie91,  Intellicode learns from thousands of repositories and creates machine learning models from that analysis.  When IntelliCode presents code recommendations, it is drawing those recommendations from the knowledge and models it has distilled based on that analysis.  Since IntelliCode draws from that knowledge and not any particular codebase, the requirements from open source licenses like MIT and GPL don’t apply in this context.

**Comment by joepie91** [comment]
I'm going to respond to your original, pre-editing message here first and foremost:

>  When IntelliCode presents code recommendations, it is drawing those recommendations from the knowledge and models it has distilled based on that analysis. Since IntelliCode draws from that knowledge and not any particular codebase, the requirements from open source licenses like MIT and GPL don’t apply in this context.

I do not believe this to be true. If I were to copy-paste and modify code from many different open-source projects into my own project, that doesn't somehow magically exempt me from my obligations under licenses like the MIT or GPL license; it just means that I have obligations towards *more* people. I do not see why that would be different here - it is clearly a derivative work.

Copyright protection is generally applied based on individual creativity and insight. IntelliCode derives from this creativity and insight to produce its recommendations. This makes it a derivative work.

It's also easy to reason about *how* you can determine that it derives from this creativity and insight; if it didn't, then it would have worked fine algorithmically without ever being trained on any human input through open-source projects. Yet this human input was apparently needed. This means that the work it derives from falls under copyright laws, and therefore the license obligations need to be fulfilled. Adding "machine learning" into the mix doesn't change that - it's still a derivative work, just with more steps.

And addressing the post-edit response:

> IntelliCode distils the coding wisdom of the community by finding common patterns repeatedly used by developers and learns from those patterns to develop machine learning models for particular coding contexts. IntelliCode generates suggestions based on patterns that are common across many repos and not specific code from any one repo.

This seems to be alluding to some form of "prior art" making copyright irrelevant. To my knowledge, prior art is only applicable to patents.

To draw an analogy: if I were to modify and publish (or even sell) a proprietary Microsoft-published application, even if equivalent open-source software exists, I would very likely still be legally threatened by Microsoft's lawyers. Even if the same kind of software has also been built by many other companies. Therefore, I do not find this argument credible.

---

All of this, of course, is just the legal perspective, and from an ethical perspective it's sort of moot. Microsoft is presenting itself as an open-source-supportive company - but in the meantime work that's derived from thousands of open-source projects is being kept proprietary, and concerns about this are trivially dismissed. That's not a great look.

**Comment by will-crawford** [comment]
A better analogy: if you learnt to code by reading through 1500 or so open source repositories, should your knowledge (based on those repositories), when used to write new code, subject that code automatically to a copyleft licence? Which? To a composite of all of them?

While it may be argued that Microsoft "owe" someone, somewhere, something for the use of that code in training their model, I'm sure that a lot of those programmers who learnt from "open source" examples over their lifetime, still consider their own brains and thoughts somewhat proprietary and mostly still charge for their time when using that knowledge...

**Comment by towen** [comment]
When Microsoft bought GitHub, they thought they were buying all of the open source projects contained therein.
Embrace, Extend...
