### ISSUE TITLE
Intellicode not showing starred suggestions (TS/JS)

### ISSUE THREAD

**Issue by Shinigami92** [MicrosoftDocs/intellicode#204]
Followup of #191 

@osobeso Please note that I have this issue with my MacOS **and** my Windows 10

This was on Windows: https://github.com/MicrosoftDocs/intellicode/issues/191#issuecomment-648102630

**Comment by uniqueiniquity** [comment]
Hi @Shinigami92,
Thanks for reporting this!
When the JS/TS file is open where you expect the results, could you please run the "Open TS Server Log" command with Ctrl+Shift+P?
I'm interested in the third line of the file, which should include the phrase `Arguments:`.
Could you share that line here?

**Comment by uniqueiniquity** [comment]
Actually, if you're willing to share that whole file, that would be best for further investigation, though you may want to review the content to ensure you're willing to share.

**Comment by Shinigami92** [comment]
<img src="https://user-images.githubusercontent.com/7195563/87124210-9e930f00-c288-11ea-9d57-9dbac66c76db.png" width="300px" />

```
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

Third line:
```
Info 2    [8:29:52.245] Arguments: E:\Program Files\Microsoft VS Code\Code.exe d:\Shinigami\Documents\Projects\HTMLHint\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\SHINIG~1\AppData\Local\Temp\vscode-typescript\b2f93df3309fb66ccac7\tscancellation-653b1fba7cbbe0591065.tmp* --logVerbosity verbose --logFile c:\Users\Shinigami\AppData\Roaming\Code\logs\20200710T082921\exthost1\vscode.typescript-language-features\tsserver-log-0VHcQw\tsserver.log --globalPlugins typescript-vscode-sh-plugin,typescript-styled-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations e:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:\Users\Shinigami\.vscode\extensions\jpoissonnier.vscode-styled-components-0.0.29 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

File: [tsserver.log](https://github.com/MicrosoftDocs/intellicode/files/4901416/tsserver.log)

Please keep a look at and below line 121 ⚠️ 
```
Info 48   [8:29:52.877] Failed to load module '@vsintellicode/typescript-intellicode-plugin' from ...
...
```

_I'll publish another log with my Mac in a few minutes_

**Comment by Shinigami92** [comment]
<img src="https://user-images.githubusercontent.com/7195563/87124780-aa330580-c289-11ea-814e-1bbae4f92ce7.png" width="300px" />

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Third line:
```
Info 2    [8:43:19.942] Arguments: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/christopher/OpenSource/HTMLHint/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/ym/y13zvdp55p99ycbl2sz33rp80000gn/T/vscode-typescript501/5cd7f81de79b001f0bf5/tscancellation-286683f1129f27cb3d00.tmp* --logVerbosity verbose --logFile /Users/christopher/Library/Application Support/Code/logs/20200710T084312/exthost1/vscode.typescript-language-features/tsserver-log-u6QHi4/tsserver.log --globalPlugins typescript-vscode-sh-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
```

File: [tsserver.log](https://github.com/MicrosoftDocs/intellicode/files/4901489/tsserver.log)

Please keep a look at and below line 108 ⚠️ 
```
Info 37   [8:43:20.92] Failed to load module '@vsintellicode/typescript-intellicode-plugin' from ...
...
```

**Comment by uniqueiniquity** [comment]
Thanks so much for the logs, @Shinigami92!
The issue is what I expected; we have a long-standing issue that IntelliCode doesn't work when using the TypeScript Language Server from your project directory (as opposed to the copy that VS Code provides). See https://github.com/MicrosoftDocs/intellicode/issues/62 for another issue tracking this.

I apologize for us having not addressed this sooner. I should have some time in the next few weeks to see if we can get this fixed. Thank you for letting us know that you're encountering this!

**Comment by Shinigami92** [comment]
Oh!! Yes this could definitely be the error!
I mostly use the `typescript.tsdk` from the project instead of VSCode's one.

I will sub/watch #62

**Comment by nonameolsson** [comment]
Hey! Just wanted to see if there has been any update on this?

**Comment by uniqueiniquity** [comment]
@nonameolsson Thanks for checking in! Unfortunately, we haven't been able to address this yet.

**Comment by ayim** [comment]
Hey folks, if you're still encountering TS related issues, we'd love for you to reopen a new bug
