### ISSUE TITLE
Please provide AI support for python language server Jedi

### ISSUE THREAD

**Issue by CatNofishing** [MicrosoftDocs/intellicode#205]
Jedi is a very good intelligent completion library for Python, but currently the plugin only supports LSP (Microsoft Python Language Server). If you can provide AI support for Jedi, this will enhance the Python programming experience (because PLS is not very stable at the moment) , I prefer Jedi)

**Comment by MikhailArkhipov** [comment]
@CatNofishing - IntelliCode also supports new `Pylance` language server https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance. Have you tried it? Thanks.

**Comment by CatNofishing** [comment]
@MikhailArkhipov   I tried it, but I did not find that it has special support for pylance😂

**Comment by markw-t** [comment]
@CatNofishing - I'm assuming you mean that you are not seeing IntelliCode stars in your completion list when you install IntelliCode for VS Code alongside the Pylance language server, for cases where you would have seen them before under the MPLS? Can you confirm and give examples please? That will help us track things down. It would also be useful to see the contents of your  VS IntelliCode output window (you can see this by switching to the Output tab in VS Code and switching the drop down to "VS IntelliCode"). This will give diagnostic information about the success or failure of loading IntelliCode for your case.

Thanks!

**Comment by orlando-oli** [comment]
I agree. It should definitely support Jedi as well.

**Comment by orlando-oli** [comment]
I agree! The more the merrier :) 
Jedi is great!

**Comment by orlando-oli** [comment]
I agree, Jedi is great. I'd love to see it working with intellicode!
