### ISSUE TITLE
Could not load extension When I install pylance

### ISSUE THREAD

**Issue by MHDFahz** [MicrosoftDocs/intellicode#207]
**Product and Version** [VS/VSCode insider]:
**OS Version** [macOS]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [python]:

error message
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

**Comment by MHDFahz** [comment]
![Screenshot 2020-07-04 at 3 49 16 PM](https://user-images.githubusercontent.com/42516446/86510516-f60b2800-be0d-11ea-8454-6abbcac852ac.png)

**Comment by markw-t** [comment]
tagging @luabud @savannahostrowski to see this issue. Are you still seeing this problem @MHDFahz ?

**Comment by savannahostrowski** [comment]
Hey @MHDFahz. Could you tell me what version of Pylance you are running? The latest is 2020.7.1.

**Comment by catycaldwell** [comment]
@savannahostrowski

**Comment by MikhailArkhipov** [comment]
@MHDFahz - Are you still experiencing issue with Python extension 2020.8.*? There were improvements in the Python extension that were supposed to address this issue. Thanks.

**Comment by ayim** [comment]
Hey @MHDFahz are you still running into this issue?
Would love to hear from you if you are, feel free to file a new bug!
