### ISSUE TITLE
IntelliCode suggestions should be always first

### ISSUE THREAD

**Issue by svipas** [MicrosoftDocs/intellicode#21]
**VS Code Version**: 1.29.1
**OS Version** [macOS/Windows]: macOS latest
**Visual Studio IntelliCode Extension Version**: 1.1.0
**Python Extension Version**: -
**Target Platform or Language** [e.g. Python]: JavaScript / TypeScript

<hr>

### TypeScript
![image](https://user-images.githubusercontent.com/10441177/49567865-b16c9180-f937-11e8-9ef6-415f0c506a63.png)

As you can see `has` shouldn't be first.

![image](https://user-images.githubusercontent.com/10441177/49567995-35bf1480-f938-11e8-9d08-bb2e894b8768.png)

As you can see I typed `p` which should give me `push` first, but it gave me `pop` instead. Same is in JS.

### JavaScript
![image](https://user-images.githubusercontent.com/10441177/49567939-00b2c200-f938-11e8-8c3c-1d940618f0c7.png)

In JS it's even worse :(

**Comment by svipben** [comment]
Seems problem is with `Locality Bonus` setting if it's enabled order is not as good as supposed to be. So if I'm right then everything seems fine with this extension and the problems are from VS Code itself. To be 100% sure can someone from the team test and if everything is OK they can easily close this issue.
