### ISSUE TITLE
python: no suggestions, model loaded but couldn't retreive data from experimentation service

### ISSUE THREAD

**Issue by karenc3** [MicrosoftDocs/intellicode#210]
Hi,
This happens on my work laptop which uses a proxy to connect to the internet. My issue is very similar to #4 and I've followed the suggestions mentioned there. I was able to download the model but there are two issues:

1. Suggestions don't work
2. This is what the output window logs for VS IntelliCode

> Could not retrieve data from Experimentation service: Error: connect ECONNREFUSED 127.0.0.1:443
> Language server is set to Microsoft.
> Acquiring model 'intellisense-members' for python
> Querying IntelliCode service for available models.
> vs-intellicode-python was passed a model: {}.
> Cached model is up to date.

I think 'Could not retrieve data from Experimentation service' might be impacting the retrieval of suggestions but I might be wrong. Please assist if anyone has seen/faced this issue before. 

Edit: This is my `settings.json`. I've just removed the `http.proxy` setting while pasting here. 

```
{
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
  "workbench.iconTheme": "Monokai Pro (Filter Spectrum) Icons",
  "workbench.colorTheme": "Monokai Pro (Filter Spectrum)",
  "editor.fontSize": 16,
  "debug.console.fontSize": 20,
  "editor.fontWeight": "400",
  "editor.snippetSuggestions": "none",
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "python.languageServer": "Microsoft", 
  "editor.tabSize": 2,
  "editor.renderWhitespace": "boundary",
  "editor.rulers": [
      100
  ],
  "editor.wordWrapColumn": 100,
  "editor.minimap.enabled": false,
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
  "python.linting.enabled": true,
  "python.linting.lintOnSave": true,
  "python.linting.flake8Args": [
      "--ignore=E111, E114"
],
}
```

**Comment by ayim** [comment]
Hi @karenc3, if you're still experiencing this issue, would you mind opening a new issue?
