### ISSUE TITLE
when start java project show ‘’Sorry, something went wrong activating IntelliCode support for Java. Please check the "Language Support for Java" and "VS IntelliCode" output windows for details.”

### ISSUE THREAD

**Issue by moxue361** [MicrosoftDocs/intellicode#212]
when start java project show ‘’Sorry, something went wrong activating IntelliCode support for Java. Please check the "Language Support for Java" and "VS IntelliCode" output windows for details.”

**Comment by vanderloureiro** [comment]
I had the same problem today, I managed to solve it now by installing an old version of _Language Support for Java (TM) by Red Hat_

EXTENSIONS: INSTALLED -> manager icon over the extension -> Install Another Version...

in my case I installed version 0.63.0 ( 1 month ago )

**Comment by Eskibear** [comment]
> Please check the "Language Support for Java" and "VS IntelliCode" output windows for details.”

Can you check above output windows and attach the logs here?

**Comment by CortesKe** [comment]
same problem today

Here is my VS IntelliCode output window

> Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"c:\\Users\\User\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.9\\cache\\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
Java Extension fails to activate.

**Comment by Eskibear** [comment]
> Java Extension fails to activate.

For some reason, extension `redhat.java` was not activated. Follow-ups:
- what's the type of your project? Maven or Gradle or simple a folder containing .java source files? 
- check output window "Log (Extension Host), search for any logs containing `redhat.java`. 
- check if there are output windows named "Language Support for Java" and "Language Support for Java (Syntax Server)
  - if true, check if there's any error message inside

**Comment by moxue361** [comment]
> same problem today
> 
> Here is my VS IntelliCode output window
> 
> > Acquiring model 'intellisense-members' for java
> > Querying IntelliCode service for available models.
> > Cached model is up to date.
> > vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"c:\Users\User\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.9\cache\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
> > Java Extension fails to activate.

Excuse me, can you tell me where this output windows is?Why can't I find it?

**Comment by CortesKe** [comment]
> > same problem today
> > Here is my VS IntelliCode output window
> > > Acquiring model 'intellisense-members' for java
> > > Querying IntelliCode service for available models.
> > > Cached model is up to date.
> > > vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"c:\Users\User.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.9\cache\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
> > > Java Extension fails to activate.
> 
> Excuse me, can you tell me where this output windows is?Why can't I find it?

on Left-up, "View" -> "Output"
Choose the "VS intellicode" window

**Comment by Eskibear** [comment]
@CortesKe @moxue361 BTW, what's your JDK version? In the latest version of java extension, it requires Java 11 to start itself. See [CHANGELOG.md#0650-july-22nd-2020](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#0650-july-22nd-2020)

**Comment by CortesKe** [comment]
@Eskibear Maybe redhat.java is the reason because it updated yesterday.
My maven project worked fine few days ago.

I try to install Java 11 and I have  jdk-11.0.8 directory under C:\Program Files\Java
I also set the environment variables.

But I can't find the jre 11 and the version of Java is still old.

Any suggestions?

**Comment by Eskibear** [comment]
- set `java.home` (vscode setting) to  "C:\Program Files\Java\jdk-11.0.8". 
- and if you still want your project to compile with java 8, follow [this wiki page](https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#do-i-need-to-migrate-my-projects-to-java-11)

**Comment by CortesKe** [comment]
> * set `java.home` (vscode setting) to  "C:\Program Files\Java\jdk-11.0.8".
> * and if you still want your project to compile with java 8, follow [this wiki page](https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#do-i-need-to-migrate-my-projects-to-java-11)

Thanks for the suggestions.

**Comment by moxue361** [comment]
> I had the same problem today, I managed to solve it now by installing an old version of _Language Support for Java (TM) by Red Hat_
> 
> EXTENSIONS: INSTALLED -> manager icon over the extension -> Install Another Version...
> 
> in my case I installed version 0.63.0 ( 1 month ago )

yes，thanks，i have solved it by this way

**Comment by moxue361** [comment]
> > Java Extension fails to activate.
> 
> For some reason, extension `redhat.java` was not activated. Follow-ups:
> 
> * what's the type of your project? Maven or Gradle or simple a folder containing .java source files?
> * check output window "Log (Extension Host), search for any logs containing `redhat.java`.
> * check if there are output windows named "Language Support for Java" and "Language Support for Java (Syntax Server)
>   
>   * if true, check if there's any error message inside

have solved it，because of the new version of red hat,thank you

**Comment by catycaldwell** [comment]
Closing as this was resolved based on @moxue361 latest comment.

**Comment by Nizvan018** [comment]
> I had the same problem today, I managed to solve it now by installing an old version of _Language Support for Java (TM) by Red Hat_
> 
> EXTENSIONS: INSTALLED -> manager icon over the extension -> Install Another Version...
> 
> in my case I installed version 0.63.0 ( 1 month ago )

Yeap, it works!

**Comment by Kobsharon** [comment]
Shifting to java 11 it worked for me. If you have settings.json then

"java.home": "/usr/lib/jvm/java-11-openjdk-amd64
