### ISSUE TITLE
JAVA: Sorry, something went wrong activating IntelliCode support for Java

### ISSUE THREAD

**Issue by Postavshik** [MicrosoftDocs/intellicode#213]
It just happened yesterday on both of my computers, personal and work Mac laptop. 

**Product and Version** [VS/VSCode]: VC Code 1.47.2
**OS Version** [macOS/Windows]: Reproducible on macOS Catalina 10.15.5 and macOS Mojave 10.14.6
**IntelliCode Extension Version**: v1.2.9
**Language Support for Java(TM) by Red Hat Extension**: v0.65.0
**Target Platform or Language** [e.g. Node.js]: Java 1.8.0_231

**Steps to Reproduce / Scenario:**

1. Open VS Code
2. Open any Java class, the error message pop up in the bottom right corner
<img width="458" alt="Extension: Visual Studio IntelliCode — schedulingapi 2020-07-25 12-06-47" src="https://user-images.githubusercontent.com/21285622/88462222-6fc38e00-ce6f-11ea-88c1-d0bbb1c4a47b.png">

**Comment by bonthaladeepu7** [comment]
I guess you need to update java to its recent version in Red Hat java extension.

**Comment by Postavshik** [comment]
Yes, you right. Update to Java 11 fixed the issue. Thank you!
