### ISSUE TITLE
IntelliCode not working with Remote-SSH

### ISSUE THREAD

**Issue by vaibhavad** [MicrosoftDocs/intellicode#214]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

- VSCode Version: 1.47.2
- OS Version: Linux 4.15.0-45-generic #48~16.04.1-Ubuntu
- IntelliCode Extension Version: 1.2.9
- Target Language: Python

The system is behind an institute proxy, HTTPS_PROXY is set correctly and check certificates has been disabled. wget www.google.com is successful

Steps to Reproduce:

1. Launch VS Code
2. Open a remote VSCode instance using Remote SSH extension

Output log of VS IntelliCode

```
Could not retrieve data from Experimentation service: Error: Request failed with status code 503
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at u._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:717
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error while activating Python: {}
```

**Comment by catycaldwell** [comment]
@savannahostrowski

**Comment by MikhailArkhipov** [comment]
@vaibhavad - what version of the Python extension you are using? There were changes in 2020.8+ which I believe, should have addressed the issue. Please let us know if you are still having problems with 2020.8+. Thanks.

**Comment by luisfergromo** [comment]
Same over here, Python v2020.11.371526539 and Visual Studio IntelliCode v1.2.10

<img width="1392" alt="Captura de Pantalla 2020-11-25 a la(s) 7 17 28 p m" src="https://user-images.githubusercontent.com/1296939/100296850-de664480-2f52-11eb-9c9f-4d535dc99498.png">
<img width="764" alt="Captura de Pantalla 2020-11-25 a la(s) 7 17 55 p m" src="https://user-images.githubusercontent.com/1296939/100296880-ee7e2400-2f52-11eb-8f6c-7bfb31d29807.png">

**Comment by luisfergromo** [comment]
**Not working with python v2020.9.+**

Tested and works fine with Python 2020.8.109390

**Comment by ayim** [comment]
@luisfergromo thanks for filing this issue.
I know it's been a while!
We'd love to hear from you if you're still seeing issues, feel free to file a new issue with us.
