### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for Java. Please check the "Language Support for Java" and "VS IntelliCode" output windows for details.

### ISSUE THREAD

**Issue by xiaoyanmo** [MicrosoftDocs/intellicode#215]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
**Steps to Reproduce / Scenario:**

1.Sorry, something went wrong activating IntelliCode support for Java. Please check the "Language Support for Java" and "VS IntelliCode" output windows for details.
2.Java 11 or more recent is required to run. Please download and install a recent JDK

**Comment by Eskibear** [comment]
The latest release of VS Code Java requires Java 11 to run.

please follow https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

**Comment by markw-t** [comment]
Per @Eskibear 's comment above, closing this item.

**Comment by xiaoyanmo** [comment]
> VS Code Java的最新版本要求Java 11才能运行。
> 
> 请关注[redhat-developer / vscode-java＃1543（评论）](https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692)

Thanks♪(･ω･)ﾉ，我使用的是java8，我想屏蔽这个错误信息

**Comment by teukurijal** [comment]
https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-669895753
it's work for me

**Comment by Kobsharon** [comment]
Shifting to java 11 it worked for me. If you have settings.json then

    "java.home": "/usr/lib/jvm/java-11-openjdk-amd64
