### ISSUE TITLE
Telemetry in Visual Studio Code Clarification

### ISSUE THREAD

**Issue by ADataGMan** [MicrosoftDocs/intellicode#217]
**Product and Version** [VS/VSCode]: VSCode 1.47.3 User Edition
**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**: 1.2.9
**Target Platform or Language** [e.g. Node.js]: Typescript

**Steps to Reproduce / Scenario:**

I'm trying to understand if Intellicode for Visual Studio Code reports telemetry with ```"telemetry.enableTelemetry": false,``` ? Based on the documentation on https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code, I'm still not sure how to disable telemetry for my work device. 

I would assume it does based on https://github.com/MicrosoftDocs/intellicode/issues/14, however I would appreciate it if I could get confirmation, and see the documentation updated.

**Comment by osobeso** [comment]
Hi @ADataGMan thanks for reaching out.
The answer is yes, we support that flag and you can disable IntelliCode telemetry logs by setting that flag to be false.

Regards,
Oscar.

**Comment by markw-t** [comment]
assigning to @catycaldwell to look at adding this info to the docs per suggestion.

**Comment by markw-t** [comment]
This is documented in https://docs.microsoft.com/en-us/visualstudio/intellicode/overview#telemetry "In Visual Studio Code, you can disable telemetry reporting by following these instructions." which links to the vscode FAQ on disabling telemetry.

Hope this helps.
