### ISSUE TITLE
Problems downloading IntelliCode model

### ISSUE THREAD

**Issue by richbon75** [MicrosoftDocs/intellicode#218]
**Product and Version** [VS/VSCode]: 1.48.0
**OS Version** [macOS/Windows]: Windows_NT x64 10.0.17134  (Windows 10)
**IntelliCode Extension Version**:  Visual Studio Intellicode v1.2.10
**Target Platform or Language** [e.g. Node.js]: Python 3

**Steps to Reproduce / Scenario:**

1. Start VS Code
2. Open .py file
3. Stare in horror at the pop-up "Couldn't download IntelliCode model. Please check your network connectivity or firewall settings."

Every time I open a python file I get the pop-up message: "Couldn't download IntelliCode model. Please check your network connectivity or firewall settings."

This is what I see in the VS IntelliCode output window:
```
Could not retrieve data from Experimentation service: Error: Client network socket disconnected before secure TLS connection was established
Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established, (Error)
No deep learning model available for Python, fall back to the default model.
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established, (Error)
No model available for Python, cannot continue.
```

This is almost certainly related to the company proxy and may be similar to this issue:  [Couldn't download IntelliCode model (PROXY SSL issue)](https://github.com/MicrosoftDocs/intellicode/issues/157) although the actual messages I see in the VS IntelliCode output are slightly different.

I work at a big company that pushes all of our internet traffic through an authenticated proxy that also does a MITM-style replacement of the SSL certificates.

If I do nothing, VS Code can't connect to the Extensions Marketplace, or download IntelliCode models.

If I set these settings, both Extensions Marketplace and IntelliCode still don't work:
```
"http.proxy": "https://ourproxy.mycompany.com:8080",
"http.proxyAuthorization": "Authorization: Basic <myb64encodedcreds>",
```

But if I do _either_ of the following things, then **Extensions Marketplace starts working** , but downloading IntelliCode models is still broken:
```
set this setting in settings.json:
"http.proxy": "https://myuser:mypass@ourproxy.mycompany.com:8080",

*or*

set this environment variable:
HTTPS_PROXY=https://myuser:mypass@ourproxy.mycompany.com:8080
```

I've tried setting `http.proxySupport` to on, off, and override, but none of them seem to change anything.

I've also experimented with `http.proxyStrictSSL` but it doesn't seem to change anything - I just leave it set to "false" for now.

I've even tried following the [manual IntelliCode model retrieval steps](https://github.com/MicrosoftDocs/intellicode/issues/4#issuecomment-450935237), but that doesn't seem to work either.  Are those instructions still accurate?  I am able to download the model file, but IntelliCode doesn't seem to recognize it as a cached model.

I've tried uninstalling and reinstalling both the Python and Visual Studio IntelliCode extensions.

Any other ideas?

**Comment by richbon75** [comment]
I was able to get it to work temporarily by installing Fiddler and letting it act as a proxy to our proxy.  I then set:
```
"http.proxy": "https://localhost:8888",
```
in settings.json and then when I reopened vscode, I got this in the VS IntelliCode output:
```
Language server is set to Microsoft.
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_9BA695AD4C514C32A5D0AC9B02846CD7?sv=2018-03-28&sr=b&sig=TM5XnGi4qdwie7LJ1ePJinxYRCmGk1Exbc6YQlvqi%2Bg%3D&se=2020-08-17T20%3A13%3A59Z&sp=r
Download complete.
```
After closing Fiddler and changing settings.json back to my normal setting of
```
"http.proxy": "https://myuser:mypass@ourproxy.mycompany.com:8080",
```
The VS IntelliCode output now says:
```
Could not retrieve data from Experimentation service: Error: Client network socket disconnected before secure TLS connection was established
Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: Client network socket disconnected before secure TLS connection was established, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
Recent model was found in cache.
```
So at least it's now finding a recent model in the cache so I can use it, and at least I know what to do now when I need to update it.  But the issue still exists under normal usage.

**Comment by osobeso** [comment]
Hi @richbon75 thanks for the feedback.
As you mention this are proxy related issues.
Good to know that you were able to temporaly bypass the proxy and download a model, IntelliCode should be working properly for you now by using that cached model.

You can try setting the [Http Proxy environment variable](https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables) to your proxy and check if that fixes the issue for you.

Also there's many other solutions you could attempt that have been suggested before on [similar proxy related issues](https://github.com/MicrosoftDocs/intellicode/issues/4).

Let us know if that fixes your problem.

Thanks!

**Comment by ayim** [comment]
@richbon75 thanks for giving IntelliCode a try.

Are you still using IntelliCode these days?
Did HTTP proxy environment variable work for you?

**Comment by richbon75** [comment]
@ayim - I no longer work at the company with that restrictive proxy, so I can't test from within that network anymore.  It's working fine in my current environment, so it is ok to close this issue.  Thanks for your attention.

**Comment by osobeso** [comment]
@Dragaan Thanks for bringing this up, it seems some regions are still affected. looking into it.

**Comment by osobeso** [comment]
@Dragaan services have been restored and should be up and running on all regions. Please try again and let us know if you're still experiencing any issues.
