### ISSUE TITLE
It doesn't work on existing project, but works with a new one

### ISSUE THREAD

**Issue by svipben** [MicrosoftDocs/intellicode#22]
**VS Code Version**: 1.29.1
**OS Version** [macOS/Windows]: macOS latest
**Visual Studio IntelliCode Extension Version**: 1.1.0
**Python Extension Version**: -
**Target Platform or Language** [e.g. Python]: JS & TS

If I use it on my existing project it doesn't work, I simply don't get `star` icon near suggestions and order is alphabetical in JS or TS. But if I create a new project and create a new file for e.g. `index.js` or `index.ts` it works.

My `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2015",
    "jsx": "react-native",
    "noEmit": true,
    "moduleResolution": "node",
    "allowJs": true,
    "importHelpers": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "rootDir": "./src",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ],
    "sourceMap": true
  },
  "exclude": [
    "node_modules",
    "android",
    "ios",
    "coverage",
    "src/native-base-theme"
  ],
  "include": [
    "src/**/*",
    "typings/**/*"
  ]
}
```

VS IntelliCode output:

```
Acquiring model 'JSIntelliCode-Completions'  with schema version between [1, 1]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/JSIntelliCode/models/latest?declaredName=Completions&minSchemaVersion=1&maxSchemaVersion=1
Cached model is up to date.
```

**Comment by svipben** [comment]
What is really weird if I open a new untitled file in the existing project and set language as JavaScript I don't get any AI based suggestions, but if I open a new VS Code instance and open a new untitled file I get the AI based suggestions.

**Comment by jkeech** [comment]
@minestarks

**Comment by minestarks** [comment]
Thanks @svipben , I'm looking into this. If you could attach a tsserver log ("TypeScript: Open TS Server Log" from the command palette) that would be really helpful for me to root cause.

**Comment by minestarks** [comment]
@svipben could you see if this solution resolves it for you? https://github.com/MicrosoftDocs/intellicode/issues/23#issuecomment-445059609

**Comment by svipben** [comment]
@minestarks You're right if I change to use VS Code TS version it works fine instead of workspace version.
