### ISSUE TITLE
Can't uninstall IntelliCode linter

### ISSUE THREAD

**Issue by webkaiyo** [MicrosoftDocs/intellicode#220]
**Product and Version** [VS/VSCode]: VSCode 1.48.0
**OS Version** [macOS/Windows]: Windows 10
**IntelliCode Extension Version**: 1.2.10
**Target Platform or Language** [e.g. Node.js]: Python 3.8

I actually have uninstalled IntelliCode but the linter still there. How can I disable this linter?
![image](https://user-images.githubusercontent.com/40964817/90767930-58d45800-e2c4-11ea-8afc-35c42a6f3e14.png)

**Comment by markw-t** [comment]
Since this is a question about how to configure the Python extension's linters, it would be better to ask it on https://github.com/Microsoft/vscode-python/issues rather than here on the IntelliCode repository.

We are interested to understand why you decided to uninstall IntelliCode and would like to hear more there - can you give us some insights?

Thanks
Mark

**Comment by webkaiyo** [comment]
Hey, @markw-t. Thank you for the fast answer. I decided to uninstall IntelliCode because I don't like linters, simple as that. I'll ask this in the right repository, thanks again for your time.

**Comment by markw-t** [comment]
Thanks for your quick answer. We don't actually do anything that could be described as linting in IntelliCode for Python - our only capability there at present is IntelliCode Completions (where we offer a starred suggestion - see [here](https://docs.microsoft.com/en-us/visualstudio/intellicode/overview#context-aware-code-completions) for details. For other languages (specifically C#) we are reaching into what could be described as linter/analyzer functionality like [IntelliCode Suggestions](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-suggestions). Did you get chance to try the completions capability? 

Thanks
Mark

**Comment by webkaiyo** [comment]
Hi, @markw-t. Thank you for the fast answer. I really like the IntelliCode's completions capability. The only reason that made me uninstall IntelliCode is the linter.
