### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by haikalmol** [MicrosoftDocs/intellicode#221]
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.2.10`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Karl\VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by markw-t** [comment]
@KarlHeinzNSJ1623 plesae can you provide some further details to help us undertstand this issue:
1. Please attach or post the C:\Users\Karl\VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt file with a link so we can inspect?
2. Please let us know which language you were editing in when you saw the problem?

Thanks!
Mark

**Comment by ayim** [comment]
@haikalmol thanks for opening this issue!
If you're continuing to experience performance issues, please let us know and reopen this bug!
-A
