### ISSUE TITLE
Can't find "Train IntelliCode model on this repository" menu

### ISSUE THREAD

**Issue by artemious7** [MicrosoftDocs/intellicode#225]
In VS 16.7.3 I can't find the View > Other Windows > Train IntelliCode model on this repository menu. I have the IntelliCode extension v2.2.733.31896 enabled. I can only find View > Other Windows > IntelliCode suggestions window. I have my C# repository opened and it's on Git. Is the documentation missing some piece of information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2089e9f-f405-f6a4-2bf2-9da8acfe2885
* Version Independent ID: 56ce5868-6ade-0d11-0038-068ffbcd6841
* Content: [IntelliSense based on your code - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models)
* Content Source: [docs/custom-models.md](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/custom-models.md)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @markw-t
* Microsoft Alias: **mwthomas**

**Comment by DavidObando** [comment]
Hi @artemious7, for Visual Studio 16.7 you need to enable the feature in Tools -> Options -> IntelliCode:
```
Requirements:
  - The repository must not already have a repository-associated model already trained on it.
  - The repository must be under Git source control.
  - You must enable the following settings in Tools > Options > IntelliCode.
    - C# or C++ team models for completions
    - Acquire team models for completions
```
Also, may I suggest to instead create your team model using our [Azure DevOps pipeline task](https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#automatically-create-and-retrain-a-model-in-azure-pipelines), or our [GitHub action](https://devblogs.microsoft.com/visualstudio/github-action-intellicode/)?

**Comment by usmanchaudary** [comment]
i am not able to find intellicode feature in tools -> options anywhere, neither visual studio is suggesting me to enable it by default,. 
my visual studio is updated.

**Comment by markw-t** [comment]
@usmanchaudary please can you check that IntelliCode is installed on your Visual Studio instance? Visit the Visual Studio installer and click Modify on your instance. You should see tabs including an Individual Components tab, which you can search. Make sure that IntelliCode is checked:
![image](https://user-images.githubusercontent.com/12836119/113425851-69cf6680-9387-11eb-82b2-e9360fd88651.png)

If it is not, check it and update. If it is, check that IntelliCode is enabled in your installation via the Extensions Manager (Extensions - Manage Extensions in Visual Studio):
![image](https://user-images.githubusercontent.com/12836119/113426064-c5015900-9387-11eb-8c8a-44b6368e630c.png)
If the Visual Studio IntelliCode extension is enabled, you should be able to visit tools-options and search for IntelliCode options:
![image](https://user-images.githubusercontent.com/12836119/113426216-fed25f80-9387-11eb-8106-a7f8caedad59.png)

If you've checked all of the above and still don't see IntelliCode in your tools options, it's possible there's a problem with your Visual Studio installation.

Once there, check for the options @DavidObando mentioned above being enabled:

    - C# or C++ team models for completions
    - Acquire team models for completions
    
![image](https://user-images.githubusercontent.com/12836119/113426335-2aede080-9388-11eb-8161-7c55cb26a524.png)

Then, when you open a solution with a supported project in it, you should be prompted to create a model. You can also manually check settings for training for a given solution through the View - Other Windows - IntelliCode pane, which has a checkbox to accept license terms to train.

https://docs.microsoft.com/en-us/visualstudio/intellicode/quickstart-team-completions#train-models-for-team-completions has more information.

Hope that helps!

**Comment by usmanchaudary** [comment]
@markw-t thank you very much for your detailed response.. problem resolved. 
thanks again

**Comment by markw-t** [comment]
Thanks for letting me know it worked @usmanchaudary ! 

Please do let us have any other feedback on your experience with IntelliCode, good or bad, we are always looking to improve!
