### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

### ISSUE THREAD

**Issue by MananPyJava** [MicrosoftDocs/intellicode#232]
Vscode
os: windows 10 pro
language: python 3.7

every time i open Visual Studio Code, it shows me this error:
![image](https://user-images.githubusercontent.com/67302570/95413138-4bdcf800-0948-11eb-92d6-0d2276a35c4d.png)

Also, it does not detect any of my python interpreters.
The issue is seen from the past 2 weeks. 
The issue is not shown while using Java or C++

**Comment by MikhailArkhipov** [comment]
Please specify what language server do you use. Please provide log output that appears in the following Output windows:

- Python
- Python Language Server or Pylance
- VS IntelliCode

Thanks

**Comment by MananPyJava** [comment]
i am using microsoft server. actually i am a newbie in coding, can you tell me where i can see the output window

**Comment by markw-t** [comment]
For reference for anyone else reading this thread, you can find the output window in Visual Studio Code using the VS Code menus, like this: 

1) View - Output   (or use the Ctrl+Shift+ U keyboard shortcut in the standard keybindings to toggle it on/off)

2) Once you're there, you should notice a drop down in the top right of the output pane, which lists the different sources of output your copy of VS Code has loaded up. If you have a python file loaded and the language server is on, that will include Python, Python Language server or PyLance. If IntelliCode is loaded then VS IntelliCode will show. Select one of these to see what output it has shown. For instance when a file containing Python is loaded in VS Code, and you have IntelliCode, you'll see logs of what IntellICode is doing in the VS IntelliCode pane (things like "acquring model" etc) which can be helpful for diagnosis of issues.

These windows often contain important messages from extensions and language services, so they are a good place to look when things go wrong in general.

Hope that helps

**Comment by markw-t** [comment]
@MananPyJava is your issue resolved? I see you closed it...
