### ISSUE TITLE
Customized Download Plan

### ISSUE THREAD

**Issue by 517030910405** [MicrosoftDocs/intellicode#233]
**Product and Version** [VS/VSCode]: VSCode 1.49.3
**OS Version** [macOS/Windows]: Windows_NT x64 10.0.18362
**IntelliCode Extension Version**: 1.2.10
**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1. Open a folder. 
2. It starts downloading the model. 

However, the network is very unstable when I am at home. And I only want it to download when I am in my office. 
After a download failure, the extension does not work. 

Will there be a customized download plan? Thanks

**Comment by DavidObando** [comment]
The IntelliCode team is looking into this.

**Comment by ayim** [comment]
Hey! Tracking this issue in #102 now
