### ISSUE TITLE
linting python 3.9

### ISSUE THREAD

**Issue by knbsilva** [MicrosoftDocs/intellicode#235]
Issue Type: <b>Bug</b>

The linting not working in Python 3.9, when i use the later version working normally.

Extension version: 1.2.10
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.22GB free)|
|Process Argv|--crash-reporter-id 10e63888-c07a-46a3-8c95-8195d09fc0d9|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MikhailArkhipov** [comment]
Are you using `Microsoft` language server or `Pylance`? If it is former, 3.9 was added https://github.com/microsoft/python-language-server/pull/2128 last week. The build is not in stable channel yet. We are going to promote it by the end of this week. 

You can also try new Pylance server, it supports 3.9 right now.

**Comment by knbsilva** [comment]
Hello @MikhailArkhipov 
I'm using Microsoft Language server, i didn't know about Pylance i will install right now.
Thank you for feedback, regards.
