### ISSUE TITLE
IntelliCode models

### ISSUE THREAD

**Issue by vengotimahesh143** [MicrosoftDocs/intellicode#236]
Issue Type: <b>Bug</b>

Downloading IntelliCode models: Downloading IntelliCode models: 8432/33580 KB it has stopped here 

Extension version: 1.2.10
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.24GB free)|
|Process Argv|--crash-reporter-id 19367546-1d87-43f1-a3dd-49402386e015|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DavidObando** [comment]
Hi @vengotimahesh143, can you provide us with the following information:
  - What language or languages were you using when this happened?
  - Do you have the IntelliCode window output for the time around this error happening? If so, can you share it with us.

**Comment by ayim** [comment]
@vengotimahesh143 have you still been seeing this issue? Would love to hear from you if you have - feel free to open a new issue!
