### ISSUE TITLE
Intellicode for Python

### ISSUE THREAD

**Issue by apxitekt0r** [MicrosoftDocs/intellicode#237]
I have a problem with intellicode for Python on vscode in Ubuntu for raspberry arm64.
So when I try to use vscode like non root user intellicode didn't work.
But when I use vscode with root intellicode work.
I trying to reinstall extensions and vs code but problem is still exist.

What I need to do to use intellicode for Python without root privileges?

**Comment by DavidObando** [comment]
Thank you for reporting @apxitekt0r, we're investigating.

**Comment by brian316** [comment]
I have the same issue, but when I added the user to root and reinstalled the vscode server it still does not work

**Comment by MikhailArkhipov** [comment]
Could you please provide log output from VS IntelliCode tab. Thanks.

**Comment by brian316** [comment]
I dont see a tab

**Comment by MikhailArkhipov** [comment]
I mean this one

![image](https://user-images.githubusercontent.com/12820357/96621840-fb598900-12bd-11eb-9212-f358a8a5fd0e.png)

**Comment by MikhailArkhipov** [comment]
What is in the `Python Language Server` section? Also, have you tried `Pylance` language server?

**Comment by brian316** [comment]
I dont see the language server
![image](https://user-images.githubusercontent.com/3878246/96622501-de718580-12be-11eb-835a-c80c871e5600.png)

**Comment by MikhailArkhipov** [comment]
What is in the `Python` section then

**Comment by brian316** [comment]
I installed pylance and it seems to be working now

**Comment by MikhailArkhipov** [comment]
@apxitekt0r  - what happens in your case?

**Comment by apxitekt0r** [comment]
> @apxitekt0r  - what happens in your case?

So when I edited the settings.jason and change "python.languageServer":"" it's start to work.

**Comment by MikhailArkhipov** [comment]
OK then, I guess we can close?

**Comment by apxitekt0r** [comment]
> OK then, I guess we can close?

I think yes.
Спасибо, Михаил!

**Comment by MikhailArkhipov** [comment]
Пожалуйста :-)

**Comment by DavidObando** [comment]
Closing as resolved. In the Raspberry Pi people should move to use Pylance as their language server in order to re-enable completions (IntelliSense).
