### ISSUE TITLE
Can't download Java intellisense-members

### ISSUE THREAD

**Issue by rcketscientist** [MicrosoftDocs/intellicode#238]
**Product and Version** [VS/VSCode]: 1.50.1
**OS Version** [macOS/Windows]: Windows (local), RHEL7 (server)
**IntelliCode Extension Version**: 1.2.10

**Steps to Reproduce / Scenario:**

1. Open a java project on a remote-ssh server.  Local is online, server is _offline_.

Receive this error:

```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: getaddrinfo ENOTFOUND prod.intellicode.vsengsaas.visualstudio.com, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: getaddrinfo ENOTFOUND prod.intellicode.vsengsaas.visualstudio.com, (Error)
No model available for Java, cannot continue.
```

**Comment by DavidObando** [comment]
Hi @rcketscientist, thank you for the report. We need some additional information:
  1. When you say "server is offline", do you mean that the RHEL7 server doesn't have a connection to the Internet, being unable to `ping prod.intellicode.vsengsaas.visualstudio.com`?
  2. If the server can be online (connected to the Internet), do you still see this issue?

**Comment by rcketscientist** [comment]
The server is air-gapped, so no ability to connect to set things up.  In some cases (ts, c++) this has seemed to either be part of the extension, or forwarded from the connected client (intellisense works without an error).  Java seems to be the exception.

**Comment by ayim** [comment]
Heyo! I'm tracking this scenario in a broader issue
https://github.com/MicrosoftDocs/intellicode/issues/347
