### ISSUE TITLE
[Question] Adding support for Eclipse

### ISSUE THREAD

**Issue by gayanper** [MicrosoftDocs/intellicode#239]
Hi,
I'm a eclipse user and i do like to integrate your intellicode support for Eclipse. I saw, after decompiling the jdtls jar inside the extension that you have plugged into eclipse jdtls, we could do a similar integration into eclipse as a completion provider as well. So if you can provide me information how to download the models and if there is a possibility to reuse the model parsers i would really like to get this support into Eclipse.

**Comment by catycaldwell** [comment]
Hi @gayanper, thank you for the question and your interest in IntelliCode. We currently only provide language support in Visual Studio and Visual Studio Code, and are not pursuing extending to additional IDEs at this point. Feature requests are always welcome, but we do ask that you abide by our license terms against reverse engineering, decompiling, and disassembling the IntelliCode extension. Thanks.

**Comment by gayanper** [comment]
Understand, that the same reason i did try to do any integration based on your implementation and report this question to if these things can be open sourced, so that community can do integrations into other editors like the coolest LSP from Microsoft. For example TabNine has the ability to be integrated like that.
