### ISSUE TITLE
Typescript React support

### ISSUE THREAD

**Issue by aexol** [MicrosoftDocs/intellicode#24]
Can you add typescript react support for typescript only. Right now when I am inside .tsx file Intellicode doesn't work. Only in .ts files.

**Comment by svipben** [comment]
If I'm right the same goes for `.jsx` too.

**Comment by aexol** [comment]
yeah

**Comment by jkeech** [comment]
@minestarks Can you take a look a this? I'm able to see IntelliCode suggestions inside of a `.jsx` file as shown below:

![image](https://user-images.githubusercontent.com/746020/49600936-55a30800-f939-11e8-97ca-46ebf3d0d254.png)

**Comment by minestarks** [comment]
@aexol @svipben  to make sure I understand -- you see suggestions in `.js` and `.ts` files, but not in `.tsx` or `.jsx` files?

**Comment by aexol** [comment]
Yes I am able to see suggestions on React, but when I use other libs I cant. I might have overestimated intellicode support. There was a package doing intellisense based on what you've written before. Intellicode is hardcoded?

**Comment by aexol** [comment]
@minestarks

**Comment by minestarks** [comment]
It's trained on projects that use common libraries, and the model is static regardless of the contents of your project. We are certainly looking into making it smarter! (Check out our C# support for an example of how IntelliCode trains on your project).

May I ask what libs you're not seeing support for? I can vet our training coverage to make sure we include enough data for popular libraries.

**Comment by aexol** [comment]
Haha my own libs :) Sure I'll wait for that feature. There was a guy I dont remember the name but it might be `https://tabnine.com/` this. I haven't use that yet but you may test it.

**Comment by jkeech** [comment]
Thanks @aexol. I'm going to close this issue since the underlying issue is not with React or tsx/jsx files, but rather that IntelliCode currently does not support training custom models on your own libraries/code.

Feel free to 👍 #26 for this feature.
