### ISSUE TITLE
Code lens does not show references on const arrow functions (Typescript)

### ISSUE THREAD

**Issue by Hmve** [MicrosoftDocs/intellicode#240]
**Product and Version** [VS/VSCode]: 1.50.1
**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**: v.1.2.10
**Target Platform or Language** [e.g. Node.js]: typescript

**Steps to Reproduce / Scenario:**

1. create an empty file e.g. test.ts
2. write code as follows:

```javascript
const foo = () => {
  console.log('do something');
};

const bar = () => {
  foo();
};`

function foo2() {
  console.log('do something');
}

function bar2() {
  foo2();
}
```
3. Result:
![image](https://user-images.githubusercontent.com/73341358/97001667-0c61fe80-1539-11eb-9789-0895bbd6d041.png)

for "normal" functions references will be shown for const arrow functions not.
Are there any suggestions?

**Comment by minestarks** [comment]
@hmve this appears to be a VS Code issue rather than something specific to the IntelliCode extension. Could you report at https://github.com/microsoft/vscode instead? Thanks!

**Comment by Hmve** [comment]
I will post it there. Thanks for your replay!
