### ISSUE TITLE
activate error on Raspberry Pi 4

### ISSUE THREAD

**Issue by Ben-Faessler** [MicrosoftDocs/intellicode#243]
I want to use VS Code on my Raspberry Pi 4 with Raspberry Pi OS 32 Bit.
But wen I open a python file comes a error:
Beim Aktivieren der IntelliCode-Unterstützung für Python ist leider ein Problem aufgetreten. Weitere Informationen finden Sie in den Ausgabefenstern "Python" und "VS IntelliCode".
Can you fix this?

**Comment by vivlimmsft** [comment]
The IntelliCode deep learning python model depends on [an external library, ONNXRuntime](https://www.npmjs.com/package/onnxruntime), which doesn't provide supported Linux ARM binaries.

The currently supported architectures for the deep learning model are:
* Windows x86, x64, ARM
* MacOS x64
* Linux x64

If you are using _Microsoft Python Language Server_, you can fall back to the non-deep learning python model by setting `"vsintellicode.features.python.deepLearning": "disabled"`. If you are using Pylance, only the deep learning model is supported, so you won't be able to use Python + IntelliCode together on your Raspberry Pi.
