### ISSUE TITLE
Intellicode does not allow users to disable it

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/intellicode#244]
![ic](https://user-images.githubusercontent.com/2473545/98252144-5ba42800-1f58-11eb-9bb6-bfd609d4384e.png)

**Steps to Reproduce / Scenario:**
When a user does not have Pylance installed, and     "python.languageServer" is configured to "Jedi", intellicode will ask users to install the "microsoft language server". There is no option to permanently disable this prompt. There is no option to disable Intellicode for this language. 
The only option if I don't want intellicode is to click "later", which to microsoft means "keep prompting and annoying me". 

There should be a button to permanently disable intellicode for prompting me to install "microsoft language server".

**Comment by catycaldwell** [comment]
@savannahostrowski

**Comment by savannahostrowski** [comment]
@catycaldwell On the Pylance side, we fixed this in 2020.11.1 - see microsoft/pylance-release#568 (@phgmacedo filed a similar bug on our release repo).

**Comment by catycaldwell** [comment]
Thanks @savannahostrowski - let's sync on next steps here.

**Comment by vivlimmsft** [comment]
BTW -- there is an option to disable IntelliCode for Python:
```
"vsintellicode.python.completionsEnabled": false
```
