### ISSUE TITLE
Cannot download IntelliCode model

### ISSUE THREAD

**Issue by Andrey-Yur** [MicrosoftDocs/intellicode#245]
Issue Type: <b>Bug</b>

При открытии VS code появляется ошибка / I have been getting this error after starting of VS code:

Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

Extension version: 1.2.10
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.25GB free)|
|Process Argv|--crash-reporter-id 60ffbab3-cfc5-4f22-be68-01ee4342ca56|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by catycaldwell** [comment]
Hi @Andrey-Yur , it appears that IntelliCode cannot download a model from our cloud service due to firewall or other network connectivity issue. Can you confirm that this isn't the issue?

**Comment by Andrey-Yur** [comment]
Hi, I didn’t find any block addresses in the firewall also turning off could not solve this problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vivlimmsft** [comment]
Can you please attach the contents of your "VS IntelliCode" output window?

**Comment by Andrey-Yur** [comment]
> Can you please attach the contents of your "VS IntelliCode" output window?

![Untitled](https://user-images.githubusercontent.com/62293778/99726890-8b414d00-2a8d-11eb-86b5-645bdb4532f4.jpg)

**Comment by Andrey-Yur** [comment]
> > Can you please attach the contents of your "VS IntelliCode" output window?

![Untitled](https://user-images.githubusercontent.com/62293778/99727098-dc514100-2a8d-11eb-946c-d806e8752982.jpg)

**Comment by Andrey-Yur** [comment]
> Can you please attach the contents of your "VS IntelliCode" output window?

![Untitled](https://user-images.githubusercontent.com/62293778/99727198-fb4fd300-2a8d-11eb-91c3-3e5fdb4ee788.jpg)

**Comment by vivlimmsft** [comment]
Sorry, by output window I meant:

1. ctrl+shift+p: `View: Toggle Output`
2. pick "VS IntelliCode" from this box:
![image](https://user-images.githubusercontent.com/27872315/99733751-802ef280-2a76-11eb-8102-6336f688e25a.png)
3. attach the text from that output window

**Comment by Andrey-Yur** [comment]
> Sorry, by output window I meant:
> 
> 1. ctrl+shift+p: `View: Toggle Output`
> 2. pick "VS IntelliCode" from this box:
>    ![image](https://user-images.githubusercontent.com/27872315/99733751-802ef280-2a76-11eb-8102-6336f688e25a.png)
> 3. attach the text from that output window

Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_1A3F919CD5B7725108B03C349630A1C82B03_4A84987F2428442A9EC84563BB2BC063?sv=2018-03-28&sr=b&sig=dHz6VMyFq%2BTLaJiouMB8%2F%2FW%2FA%2B%2Bgv6slpwNGPJXY%2FeA%3D&se=2020-11-19T21%3A34%3A06Z&sp=r
Download complete.
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: EPERM: operation not permitted, open 'C:\Program Files\Microsoft VS Code\models.json', (Error)

**Comment by Andrey-Yur** [comment]
![image](https://user-images.githubusercontent.com/62293778/99739280-c8fca080-2aa2-11eb-97b4-841b7758a8b5.png)

**Comment by Andrey-Yur** [comment]
It looks like that VS Code can not /has no right to download into this C:\Program Files\Microsoft VS Code directory.

**Comment by ayim** [comment]
@Andrey-Yur have you seen this problem repeat itself?
Would love to hear from you if it has - feel free to open a new issue!

-A
