### ISSUE TITLE
not responding on my vs code can not debug 

### ISSUE THREAD

**Issue by SBurk7** [MicrosoftDocs/intellicode#246]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:** 

1.
2.

**Comment by catycaldwell** [comment]
@Sburk, is IntelliCode causing VS Code to be not responsive?

**Comment by ayim** [comment]
Hey @SBurk7, we'd love to hear from you if you're still seeing any IntelliCode related issues.
Feel free to open a new thread.
