### ISSUE TITLE
IntelliCode SQL model file doesn't exist

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/intellicode#247]
**Product and Version** [VS/VSCode]: Azure Data Studio 1.24
**OS Version** [macOS/Windows]: Windows 10 2004
**IntelliCode Extension Version**: 1.2.1
**Target Platform or Language** [e.g. Node.js]: T-SQL

**Steps to Reproduce / Scenario:**

1. Open Azure Data Studio
2. Get Error

Error presented at the bottom is:
> Sorry, something went wrong activating IntelliCode support for SQL. Please check the "MSSQL" and "VS IntelliCode" output windows for details.

The MSSQL output window is blank. VS IntelliCode presents the following:
```none
Acquiring model 'intellisense-members' for sql
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-SQL was passed a model: {"modelPath":"/home/thom/.azuredatastudio/extensions/visualstudioexptteam.vscodeintellicode-1.2.1/cache/99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C","modelId":"99136CA159AB897D942412E976015B8C9EC2","outputId":"6D6727BA7E6347BE9124EF572943AC5C"}.
IntelliCode SQL model file doesn't exist in /home/thom/.azuredatastudio/extensions/visualstudioexptteam.vscodeintellicode-1.2.1/cache/99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C.
Error while activating SQL: {"errno":-4058,"syscall":"access","code":"ENOENT","path":"/home/thom/.azuredatastudio/extensions/visualstudioexptteam.vscodeintellicode-1.2.1/cache/99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C"}
```
I have tried disabling and re-enabling the extension, and uninstalling and reinstalling (closing the application between each time).

**Comment by vivlimmsft** [comment]
Please update your IntelliCode extension to the latest (currently 1.2.10) and restart Azure Data Studio.

If it's still showing the same error, please attach the contents of `/home/thom/.azuredatastudio/extensions/visualstudioexptteam.vscodeintellicode-1.2.10/cache/models.json`, and a list of files inside `/home/thom/.azuredatastudio/extensions/visualstudioexptteam.vscodeintellicode-1.2.10`. (note the version number of these paths is 1.2.10, so after you update the extension)

**Comment by LarnuUK** [comment]
@vivlimmsft 1.2.1 is the version that is available in ADS; you need to update your repository for me to update to 1.2.10.

**Comment by LarnuUK** [comment]
Hmm, I think I see the issue; that's a linux path (`/home/thom`) but I'm using Windows. That's... odd.

**Comment by LarnuUK** [comment]
Thanks for the comment, @vivlimmsft . I've fixed it, by uninstalling the extensiomn, deleting the folder `visualstudioexptteam.vscodeintellicode-1.2.1` in the `.azuredatastudio\extensions\` folder and then redownloading.

Though, I would still really appreciate if you can push 1.2.10 for ADS please! :)
