### ISSUE TITLE
IntelliCode is not appearing in the VSCode marketplace

### ISSUE THREAD

**Issue by joeytwiddle** [MicrosoftDocs/intellicode#248]
**Steps to Reproduce / Scenario:**

1. Ctrl-P in Code, and paste `ext install VisualStudioExptTeam.vscodeintellicode`
2. The marketplace search opens in the sidebar, but "No extensions found."
3. The same if I just search for "IntelliCode"

**Caveats:**

- I am running Code - OSS, not VSCode
- I am running on Linux

Is the extension not available for one of those?

If so, I think that could be mentioned in the FAQ, or on the [extension page](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode).

**Full details of my Code - OSS build and environment:**

Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-23T22:26:38.399Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.152-1-MANJARO

----

Edit: The extension page suggests that the extension is available for VSCode, which is what confused me.

![Screenshot_20201209_135808](https://user-images.githubusercontent.com/911799/101591194-e92ada00-3a26-11eb-89b0-b81d8a134eda.png)

**Comment by catycaldwell** [comment]
Hi, @joeytwiddle, IntelliCode is not available for Code.  We do mention this on the Marketplace page noted in the screenshot below AND it is included as part of our license which is linked from the marketplace page. 

![image](https://user-images.githubusercontent.com/908768/99717347-25899c80-2a5e-11eb-8c4f-0bc7469da6a5.png)

**Comment by ayim** [comment]
The extension is available: https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode
