### ISSUE TITLE
README: privacy practices need documentation

### ISSUE THREAD

**Issue by ronjouch** [MicrosoftDocs/intellicode#25]
The VSCode extension readme doesn't have a single sentence about your privacy / data-usage & collection practices.

Looking at the [Visual Studio (not VS Code) IntelliCode FAQ](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq#q-what-makes-ai-assisted-intellisense-powered-by-intellicode-better-than-regular-intellisense), I read that:

> *"IntelliCode uses the developer's current code context and patterns based on thousands of highly rated, open-source projects on GitHub. The results form a model that predicts the most likely and most relevant API calls."*

and paragraph [Q. What happens when my model is trained, and what data is sent to Microsoft?](https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-model-faq#what-is-sent) says:

> *"To train a model based on your code, the IntelliCode extension extracts only those elements of the code that are needed to create a model for recommending completion values. For example, it extracts the names of classes and methods and how often they're called in different circumstances. The extracted data is transmitted to the IntelliCode service, which uses machine learning algorithms to train a model for your code. It then returns the model to your computer where it's merged with the base model."*
>
> *"We don’t track your keystrokes or extract the values of literals (such as strings) from your code, nor do we extract whole expressions or statements. All communication with the IntelliCode service is over HTTPS. For more information, see Q. How secure is this?."*

Is it the same for the VSCode extension? What does *"current code context"* mean? What data does the extension send? Code? A binary representation? How often? The FAQ entries should be repeated, complemented, or at least linked to in the README.

**Visual Studio IntelliCode Extension Version**: 1.1.0

**Comment by jkeech** [comment]
Thanks for your interest in IntelliCode! The VS Code extension does not include any custom model support, which is why the readme doesn't reference it today. Custom models are currently limited to C# in the VS extension.

If you train a C# custom model, you can directly view the data that is being sent to the IntelliCode service. See https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-model-faq#q-can-i-see-the-data-that-is-sent-to-microsoft for more details.

In short, we do not send your raw source code or compiled binaries. We analyze the code and extract some minimal type information which is needed to build the model. Training is manual and you are in full control -- the process only happens when you click the Train/Retrain button in the VS extension UI. We are interested in feedback around whether an automated retraining solution would be helpful for keeping the model fresh (as part of a CI build for example). You are welcome to try out the training process on a sample codebase to get a sense for what happens prior to using it for your other repos. We recommend some sample apps to try here: https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-model-faq#-q-is-there-a-way-to-try-this-out-without-using-my-own-codebase.

**Comment by abuchholtzau** [comment]
We've updated our general FAQs to be more clear about what we collect and added links to this explanation in both of the VS and VS Code pages.

**Comment by ronjouch** [comment]
Thanks for the followup, @abuchholtzau . Link: https://docs.microsoft.com/en-us/visualstudio/intellicode/faq#-q-what-about-privacy-are-you-sending-my-code-to-the-cloud-what-customer-data-is-being-sent-to-microsoft . Archiving here the text as of today 2018-12-17:

> ## Q: What about privacy? Are you sending my code to the cloud? What customer data is being sent to Microsoft?[](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq#-q-what-about-privacy-are-you-sending-my-code-to-the-cloud-what-customer-data-is-being-sent-to-microsoft)
> 
> Developers are invited to experience Visual Studio IntelliCode today as an experimental preview extension. The purpose of the extension is to enable developers to test IntelliCode's capabilities and to provide feedback to the product team.
> 
> We capture some anonymized usage and error-reporting data from the extension to help improve the product. No user-defined code is sent to Microsoft, but we collect information about your use of the IntelliCode results.
> 
> For base model suggestions, which are open-source or .NET types and members, we capture whether you selected an IntelliCode suggestion and log the name of the suggestion in order to monitor and improve the base model.
> 
> For custom models, we only capture whether you selected an IntelliCode suggestion and do not log your user-defined types or methods.
> 
> In Visual Studio, developers can opt out of the [Visual Studio Experience Improvement Program](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-experience-improvement-program), which turns off data collection for the IntelliCode extension too. From the menu bar, select **Help** \> **Send Feedback** \> **Settings**. In the **Visual Studio Experience Improvement Program** dialog, select **No, I would not like to participate** and then select **OK**.
> 
> In Visual Studio Code, developers can turn off sending usage data to Microsoft by following [these instructions](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting).
> 
> The IntelliCode extension may periodically ask the developer to complete a survey, which again is anonymized. Users can sign up for news and a future private preview, but are not currently required to do so to use the experimental extension.
> 
> If you use the new capability to create models that learn patterns from your own C# code, you need to [sign in to Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/signing-in-to-visual-studio) to be able to use the preview model training service. The training service collects only the minimum data that's required to create the model. Microsoft keeps the trained models secured to your account so only you and those you choose to share them with can access them. Your model and what it’s learned about your code stays private to you. For more information, see [What is sent to Microsoft to create my model](https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-model-faq#what-is-sent).
