### ISSUE TITLE
autocompleting stopped in JS file both for directory paths and exported variables across files

### ISSUE THREAD

**Issue by bolamsydhom** [MicrosoftDocs/intellicode#250]
<!--

Reporting a Problem
-------------------
To report a problem with IntelliCode for Visual Studio, please use the "Report a Problem..." feature built into the tool.
To report a problem with IntelliCode for Visual Studio Code, you're in the right place. Please copy and paste any details that are visible in the Output window logs for VS-IntelliCode and the lanuage you're using.

If your issue relates to Python IntelliSense using the new Python Language Service rather than to IntelliCode recommendations, please report it at https://github.com/Microsoft/vscode-python/issues/new. Include any details in the Output window logs for Python.

1. directories no longer auto completed 
![image](https://user-images.githubusercontent.com/45564999/99665846-d69a3200-2a72-11eb-833f-01a001a6268a.png)

2.

**Comment by catycaldwell** [comment]
@bolamsydhom, please provide more information for me to properly triage this issue.

**Comment by bolamsydhom** [comment]
I am using vscode on MacOs I just updated the OS to BigSur and since that intelsense is not working fine at all. no more completing modules in import sentence nor the path of directories nor variables names of any other methods in JS

**Comment by catycaldwell** [comment]
Thanks @bolamsydhom for providing this information. Adding @vivlimmsft to help with triage.

**Comment by ayim** [comment]
@[bolamsydhom](https://github.com/bolamsydhom) we'd love to hear from you if you're still experiencing issues.
Please feel free to open a new issues!
