### ISSUE TITLE
optional senses

### ISSUE THREAD

**Issue by TGauthier2011** [MicrosoftDocs/intellicode#251]
I'm using VSCode in Windows 10 with extension Visual Studio IntelliCode v1.2.10 for Python, with Python 3.9 installed.

**I would like to see to see option's too:
 A- resize the inteli window that pop's up with suggestions
 B- cancel the inteli window via .json settings, on certain parameters 
     such as the print function, as I do not need a window the size of 
     half my screen popping up telling me all the options I have using 
     the print function.
Thank you!
You all rock!** 
![Screenshot 2020-11-19 200021](https://user-images.githubusercontent.com/55168844/99756420-fbf26480-2aa1-11eb-89a0-e122905a2ad1.jpg)

**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by catycaldwell** [comment]
Hi @TGauthier2011, the above screenshot is of IntelliSense in Visual Studio Code not IntelliCode, the stars on items you get at the top of your IntelliSense completions list. As you mentioned the settings.json file is the right location for customizing IntelliSense, however, you are not currently able to customize WHEN to show/not show the IntelliSense window on certain parameters.

For more information, you should check out [IntelliSense in VS Code](https://code.visualstudio.com/docs/editor/intellisense). 

Please let me know if the IntelliCode team can help you further? 

Cheers,
Caty, Program Manager
