### ISSUE TITLE
intellicode not working for python

### ISSUE THREAD

**Issue by eldad-el** [MicrosoftDocs/intellicode#253]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by tonydattolo** [comment]
same issue

**Comment by catycaldwell** [comment]
@tonydattolo  and @eldad-el, Which version of IntelliCode extension are you using for VS Code? Also, can you let me know which version of the Python Language Service you are using? You can find this information in the settings.json file for IntelliCode and the Python extensions.

**Comment by FunnyBones** [comment]
I just ran into the same thing on the latest Visual Studio Insiders build (1.53.0). I tried multiple ways of installing python, reinstalling intellisense, etc. What seemed to work was I deleted the .vscode folder in the directory I was in, and presto. 

I looked at what the settings.json file had in it and it was a hard link, so to speak, to an old interpreter version. 

Hope this helps someone.

**Comment by markw-t** [comment]
Hey @tonydattolo @eldad-el  - can you give some further details on what exactly you are seeing please? It will help us to have the following:
1.  Versions of IntelliCode extension and VS Code, as well as the Python Language Service (is it Microsoft Python LS , PyLance or Jedi?)
2. What do you see in the IntelliCode output window when you try and use IntelliCode? You can see this window under  View...Output by selecting the "VS IntelliCode item in the drop down at the end of the Output pane: 
![image](https://user-images.githubusercontent.com/12836119/109861522-3c6e8c00-7c14-11eb-93dc-fe6f1b8c4315.png)

We won't be able to make any progress without this info so anything you can share will be helpful

Thanks a lot!
Mark

**Comment by tonydattolo** [comment]
@markw-t 
sorry, should've updated. it worked after a computer restart
i think at the time I was messing with a few different intellisense tools, the default one, pylance, and kite runner

**Comment by markw-t** [comment]
Thanks @tonydattolo; glad it's working now for you and that a restart fixed it :-)

@eldad-el since we don't have details I can't tell if you were suffering the same issue as Tony; I'll close this issue but if you have the details above please feel free to re-open with them!
