### ISSUE TITLE
Intellicode not working - Authentication error while using Visual Studio IntelliCode Team Model Training

### ISSUE THREAD

**Issue by ShaikSaheb** [MicrosoftDocs/intellicode#254]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by catycaldwell** [comment]
@ShaikSaheb, thanks for leaving an issue. Could you update with more information about what you're seeing so the team can help investigate your issue?

**Comment by markw-t** [comment]
Removing doc-bug label. 

@ShaikSaheb we are currently unable to take further action on this problem without additional information on what exactly you are seeing and when it shows up. If you are still seeing this problem please can you re-open with details of the problem being seen, when you see it, and the contents of your VS IntelliCode Output pane when the problem occurs, so we can investigate?

Thanks!
