### ISSUE TITLE
Intellicode not working typescript

### ISSUE THREAD

**Issue by Poumm** [MicrosoftDocs/intellicode#255]
Intellicode stopped working.

I'm on the same project as some co-worker and it works fine with them.

I've spent time trying many things to get it to work. 
At last, I've tried to remove everything and restart from fresh.

**Steps to Reproduce / Scenario:**

 - clear my usersetting.
 - uninstall every extension.
 - turn off user sync in vscode.
 - delete my .vscode and every file link to vscode in my appData.

Then : 

 - install vs-code from a newly downloaded installer here : https://code.visualstudio.com/download
 - start it
 - try some simple suggestions like '' 'toto'.sub " in a .tsx file in my project.
 - I've only got the default suggestions from vscode
 - install intellicode
 - try some simple suggestions like '' 'toto'.sub " in a .tsx file in my project
 - I've only got the default suggestion from vscode

After this : 

 - I've tried some other simple suggestion like using a typed object and trying to get his fields, but nothing
 - I've tried to fix it myself  following the FAQ link then going for the troubleshot section here : 
https://docs.microsoft.com/fr-fr/visualstudio/intellicode/intellicode-visual-studio-code#troubleshoot

It didn't help much but provided 2 more links : 
 - https://code.visualstudio.com/docs/editor/intellisense#_troubleshooting
 - https://code.visualstudio.com/docs/languages/javascript#_intellisense

Only things I've already tried. So, I'm out of options.

** My confing **

**Product and Version** [VS/VSCode]: 1.51.1(system setup)
**OS Version** [macOS/Windows]: windows 10
**IntelliCode Extension Version**:  v1.2.10
**Target Platform or Language** [e.g. Node.js]: typescript

userSetting in vscode : 
```
{
    "window.zoomLevel": -1,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
}
```

workspace settings : 
```
{
  "typescript.tsdk": "node_modules\\typescript\\lib",
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    { "language": "typescript", "autoFix": true },
    { "language": "typescriptreact", "autoFix": true }
  ]
}
```

Thanks for reading, I hope for some help.

**Comment by DavidObando** [comment]
Hi @Poumm, can you try to reproduce the issue and copy the logs that IntelliCode produces in the output window in VSCode?
![image](https://user-images.githubusercontent.com/950290/100773548-e04a6080-33b5-11eb-9b89-0b5c581392df.png)

**Comment by Poumm** [comment]
Hello, 

unfortunately the only log I got is. 

```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
```

**Comment by Poumm** [comment]
I manage to make it work. 

I just discovered that vscode keep files in `C:\Users\{user}\AppData\Roaming\Code`.

Deleting this folder finally let me reset my vscode environment. 

After this intellicode works fine.

Sorry for the trouble, I was out of options, so I call for help. 

I'll close the issue since it wasn't  something in intellicode from the beginning.

Keep up the good work ! bye.
