### ISSUE TITLE
Intellicode not activating for Angular project - error in Developer tools

### ISSUE THREAD

**Issue by jtsom** [MicrosoftDocs/intellicode#256]
When opening an Angular project in VS Code,  VS Intellicode produces an error in the developer tools debugger console:
```
abstractExtensionService.ts:717 Activating extension 'VisualStudioExptTeam.vscodeintellicode' failed: [VisualStudioExptTeam.vscodeintellicode]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api VisualStudioExptTeam.vscodeintellicode.
```

There is nothing in the Output window for Intellicode, there isn't even a selection for it in the dropdown.

**Product and Version** [VS/VSCode]:
```
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
**OS Version** [macOS/Windows]: WIndows 10
**IntelliCode Extension Version**: 1.2.10
**Target Platform or Language** [e.g. Node.js]:
Angular / Typescript
**Steps to Reproduce / Scenario:**

1. Open angular project
2. open various files in the project, hovering over the code.
3. Open developer Tools, see error.

**Comment by DavidObando** [comment]
Thank you for the report. We're actively working to get this resolved. It's currently only affecting VSCode Insiders, and using the regular (blue icon) VSCode shouldn't present you with this problem. We'll make sure to notify you when an update is available and this is resolved.

**Comment by leti367** [comment]
This is caused by vscode issue [111913](https://github.com/microsoft/vscode/issues/111913). Will update compiler version to fix it. Thanks!
