### ISSUE TITLE
Not working even after restarting VSC

### ISSUE THREAD

**Issue by LoopGlitch26** [MicrosoftDocs/intellicode#257]
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

**Comment by LoopGlitch26** [comment]
for python

**Comment by antonioscervan** [comment]
What's your VS Code version? I was having the same problem and solved it by updating from 1.50 to 1.52

**Comment by catycaldwell** [comment]
@LoopGlitch26, can you share more details of your setup environment - VS Code extension version, Python language server, OS?

**Comment by LoopGlitch26** [comment]
VSC version 1.50, python extension from vscode? and macOS

**Comment by markw-t** [comment]
Are you still seeing this issue @LoopGlitch26 ? There have been several releases of the new Pylance extension since this bug was raised and I wanted to verify.

**Comment by LoopGlitch26** [comment]
I updated my VSC version and so far I don't see any more issues.

**Comment by markw-t** [comment]
Thanks for the rapid reply, glad to hear that you are no longer experiencing problems. I'll close this item in that case, but please do reach out and let us know if you're experiencing any problems with IntelliCode again. I would also love to hear any feedback you may have about IntelliCode overall - good and bad. Are there things you wish it would do for you that it does not? Feel free to contact me directly mwthomas at microsoft dot com.
