### ISSUE TITLE
Error in activation of vs intellicode

### ISSUE THREAD

**Issue by m00ke5h** [MicrosoftDocs/intellicode#259]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. In VS IntelliCode output window:
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Error while activating Python: {}

2.In Python output window:
Error 2020-12-22 09:52:06: sendStartupTelemetry() failed. [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi

**Comment by catycaldwell** [comment]
Adding @savannahostrowski, @jakebailey for their investigation. 

@M-ar-sh-h, can you share more environment information, Python extension version, OS, and VS Code version?

**Comment by ayim** [comment]
Hey @m00ke5h, we'd love to head from you if you're still seeing this issue.
Feel free to start a new thread if you are!
