### ISSUE TITLE
[VS Code] Support for custom models in TS/JS

### ISSUE THREAD

**Issue by 2percentsilk** [MicrosoftDocs/intellicode#26]
**Target Platform or Language** [e.g. Python]: JavaScript/TypeScript

**Steps to Reproduce / Scenario:**
Bring custom model training for TS/JS to the IntelliCode extension for VS Code.

**Comment by JacobCallahan** [comment]
Any update on this? Is there a certain amount of positive votes needed to get this implemented?

**Comment by catycaldwell** [comment]
Normalizing the label to Product feedback

**Comment by aheater18** [comment]
Are there any updates on this? It looked like an exciting idea, I'm curious if it will be implemented.

**Comment by ayim** [comment]
Hey folks, we've implemented a deep learning model for C# in VS and C# Dev Kit for VSCode, along with Python in VSCode. This should address the ask here!

https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
