### ISSUE TITLE
Intellicode not working for python

### ISSUE THREAD

**Issue by aabdou5** [MicrosoftDocs/intellicode#261]
Issue Type: <b>Bug</b>

Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

Extension version: 1.2.10
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.60GB free)|
|Process Argv|--crash-reporter-id 53469439-9a52-4000-9e35-4c902962a5df|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by catycaldwell** [comment]
@aabdou5, Thank you for providing such great detail on your environment. This was helpful. Could you try updating to the latest VS Code version to determine if this is still an issue?

**Comment by aabdou5** [comment]
> @aabdou5, Thank you for providing such great detail on your environment. This was helpful. Could you try updating to the latest VS Code version to determine if this is still an issue?

I have updated VS Code, it works well now, thank you.

**Comment by ayim** [comment]
Closing since this works for the customer
