### ISSUE TITLE
Activating Anaconda Environment 

### ISSUE THREAD

**Issue by D35-doctor** [MicrosoftDocs/intellicode#265]
<!--
For the past few weeks I successfully installed Anaconda as well as its essential components such as navigator to my computer. However, when practicing with anaconda especially with the "Hello World" sequence, I received an error saying I need to activate anaconda environment. The problem is that I tried to activate the anaconda environment, but which do I need to apply and activate so I practice with the code such as "Hello World" and other things. 

What I am saying in two questions:
1. What environments or additional apps should I include in my Anaconda including navigator?
2. To activate my Anaconda environment, where should I put this command: "conda activate myenv" and " myenv" in terms of replacement?

-------------------
T
1.
2.

**Comment by markw-t** [comment]
Closing this as there's not enough info for us to work on this problem.

If you are still seeing a problem please can you provide more detail? From the description this may not be an IntelliCode problem and is more likely to be Python related?

Thanks
Mark
