### ISSUE TITLE
something went wrong activating IntelliCode support for Python+ Error while activating Python: {}

### ISSUE THREAD

**Issue by MoElaSec** [MicrosoftDocs/intellicode#266]
**Product and Version** : VSCode
**OS Version** : Windows
**IntelliCode Extension Version**:  v1.2.10
**Target Platform or Language** : Python 3.9 (I used to have 3.8 and same problem happened)

**Steps to Reproduce / Scenario:**

1.Open VS-Code
2. Wait for extensions to load

No this's different from this issue [#57](https://github.com/MicrosoftDocs/intellicode/issues/57)
non of what's said there or other similar issues fixed my problem the main difference is in the output as there's no info just stops and say:  **Error while activating Python: {}**

- VS IntelliCode Output:
![image](https://user-images.githubusercontent.com/48570596/104447202-e5a1ea00-55b4-11eb-86d4-f9b540e7c73d.png)

- the bottom of the long Python Output:
![image](https://user-images.githubusercontent.com/48570596/104447383-2863c200-55b5-11eb-8b44-b772c99b8be6.png)

I have many similar Errors similar to the one shown above, this is a text for the complete output:

[python_output.txt](https://github.com/MicrosoftDocs/intellicode/files/5808331/python_output.txt)

- for reference this's all the python available on my Windows PC:
![image](https://user-images.githubusercontent.com/48570596/104448324-71684600-55b6-11eb-9c90-7e873f7fec55.png)

**Comment by MoElaSec** [comment]
So I wasn't able to solve the problem but due to the fact I must work with flask for the time being I did the following:
- **TLDR: worked with Jedi and abandoned IntelliCode**😊
1. Disabled Visual Studio IntelliCode
2.  in settings.json I wrote:
**``` "python.languageServer": "Jedi", ```**
3. VS-Code prompts me that I should reload the python server so I clicked re-load.

& now everything is fine:
![image](https://user-images.githubusercontent.com/48570596/104452708-ceff9100-55bc-11eb-9cbf-f61dcff90ba8.png)

**Comment by markw-t** [comment]
@savannahostrowski please can you take a look at this issue?

**Comment by jakebailey** [comment]
The error trace here seems to say that your VS Code version is too low. Can you upgrade to at least VS Code 1.51? (Your original post did not provide the VS Code version you are using.)

**Comment by markw-t** [comment]
@MoElaSec did you have a chance to try @jakebailey 's advice?  Are you running VS Code 1.51 or higher?

**Comment by MoElaSec** [comment]
Yeah after I asked the Q a time went by and I run the latest VSCode ver still got the same issue but as I said earlier stopped using the extension.
Got caught it in project to worry about something basic like this.

**Comment by markw-t** [comment]
OK, thanks for getting back to us, and appreciate the info @MoElaSec . @jakebailey any further follow up steps possible here?

**Comment by jakebailey** [comment]
The next version of the Python extension correctly indicates its minimum version of VS Code to prevent installing it on incompatible versions, but if the issue was not fixed by updating, then we'd need a new stack trace to see what's going on.

**Comment by jakebailey** [comment]
For reference, the info would be the "Python" output logs that you had screenshooted in the original issue (as well as the VS Code version in use).

**Comment by estringfellow** [comment]
Hi Jake,
I am experiencing the same issue. In case it's helpful, please find the stack trace from the "Python" output log below.
I'd prefer to not abandon Intellicode and go with another solution, so I appreciate any insights you might have here!
Please let me know if you require any additional info on my behalf.
Thanks!

[Python Intellicode stack trace error.txt](https://github.com/MicrosoftDocs/intellicode/files/6004457/Python.Intellicode.stack.trace.error.txt)

**Comment by estringfellow** [comment]
I think I fixed it - after upgrading VSCode, there wasn't a Python interpreter selected by default for some reason. I selected a Python interpreter and that seems to have fixed the problem. I'm not getting the same error message when loading VSCode or in the Python logs. 
Thanks!

**Comment by keg247** [comment]
I have the same issue while running VS Code 1.54.1.  Everything worked fine in 1.52.1, but failed as soon as I updated to 1.54.1.  Python output attached.

[python_output.txt](https://github.com/MicrosoftDocs/intellicode/files/6119436/python_output.txt)

**Comment by markw-t** [comment]
tagging @jakebailey to see @keg247 's new output

**Comment by jakebailey** [comment]
I don't think this is related to the other users in this thread. IIRC there was some mutual bugfixes that went out for both VS Code and the Python extension to resolve some proposed API problems. @luabud or @karthiknadig may recall better if this applies.

```
Error 2021-03-10 15:25:14: Failed to start language server, Class name = r, completed in 269ms, has a falsy return value, Arg 1: <Uri:d:\KEG\Documents\Portable Apps\WinPython64-3830\notebooks\Deeplearning_AI\1 Neural Networks and Deep Learning\Programming Assignments\Week 2\Logistic Regression With A Neural Network Mindset v6a\lr_utils.py>, Arg 2: {"architecture":3,"path":"D:\\KEG\\Documents\\Portable Apps\\WinPython64-3830\\python-3.8.3.amd64\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.3-final","major":3,"minor":8,"patch":3,"prerelease":["final"],"build":[],"version":"3.8.3-final"},"sysVersion":"3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]","sysPrefix":"D:\\KEG\\Documents\\Portable Apps\\WinPython64-3830\\python-3.8.3.amd64","fileHash":"425155e78dccb89e30aa161d5100c8e3d9c2c73c22e05543437878168cde45e380fb7aa61a50e8113c06a3d66edd527aa0733ed017ba8cd0f6a44e04b3c01123","envType":"Unknown","displayName":"Python 3.8.3 64-bit"}, Return Value: undefined [Error: [nullExtensionDescription]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api nullExtensionDescription
```

But, I do not know who is enabling that proposed API. "nullExtensionDescription" does not appear in the Python extension, the Pylance extension, nor in the language server client.

**Comment by jakebailey** [comment]
The message implies some extension has a null description, but none in the Python stack is missing the property in their package.json...

**Comment by Paril** [comment]
Just noting that this is still an issue. Can't get it to work with Pylance on latest Insiders VSCode.

**Comment by Z3ROD4RK** [comment]
I just ran into this issue ....for one minute its working ..I close vs code for like 2mins, I return and now I have this problem that won't let me do anything ! Help?

**Comment by markw-t** [comment]
Tagging @luabud and @savannahostrowski to see if we can gather more info to help diagnose and solve this

**Comment by markw-t** [comment]
@Paril @Z3ROD4RK it would be very helpful for us to see the logs associated with the failing sessions you are both seeing.

To view these, please bring up the Python output window (View menu... Output... and select Python in the drop down at the right hand end), then paste the entire log into a text file and attach to this bug. They should have diagnostic information and stack traces for the failures you are seeing which will help our team diagnose correctly.

Thanks!

**Comment by FazeelUsmani** [comment]
### Intellisense is not working


Unable to navigate in VS code python file. Yesterday, it was working fine, but don't know what happened today. Tried several things but no use.

Here's the error message:
[intellisense and Python error image](https://files.slack.com/files-pri/T030UACV4-F02C5DPFG7L/image.png)
and vscode version is >1.5.0 on macOS Big Sur v1.5.2


Here are the vscode details:
Version: 1.59.1 (Universal)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0


**Python output:**
```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
Python interpreter path: ./venv/bin/python
Error 2021-08-24 17:46:29: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat '/usr/local/bin/python2'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/bin/python2'
}
Starting Jedi Python language engine.
> ~/workspan-network/venv/bin/python -c "import sys;print(sys.prefix)"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python -c "import sys;print(sys.prefix)"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python -c "import sys;print(sys.executable)"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python -c "import sys;print(sys.executable)"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python site --user-site
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python site --user-site
cwd: ~/workspan-network
> ~/workspan-network/venv/bin/python ~/.vscode/extensions/ms-python.python-2021.8.1159798656/pythonFiles/completion.py
> ~/workspan-network/venv/bin/python ~/.vscode/extensions/ms-python.python-2021.8.1159798656/pythonFiles/completion.py``
```


**VS Intellisense output**
```Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1523:3364)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1523:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}```

Please help me! Can't do any work without this

**Comment by jakebailey** [comment]
I'm thinking that any report that contains `command 'python.intellicode.loadLanguageServerExtension' not found` is due to a change in the Python extension, where it finishes activating before Pylance has loaded (and IC tries to send this command too quickly). The IC extension may need to use some other signal to know when it's safe to try and send us the model.

**Comment by FazeelUsmani** [comment]
Okay, is there any fix? @jakebailey

**Comment by ayim** [comment]
@fazeelusmani would you mind trying again?
We're curious if you're still seeing this issue.

-A

**Comment by FazeelUsmani** [comment]
@ayim This is working now. Thanks!

**Comment by issam-seghir** [comment]
Going to the Python extension in the store (ms-python.python), then update the extension or switch to (pre-release) and restart VSCode fix the problem for me

**Comment by rocheparadox** [comment]
I faced the same issue. In my case, **pylance** extension, which is required for intellicode was not active. I found out that the pylance for my vscode version was not supported anymore. Updating the VS code to the latest version fixed this error.
