### ISSUE TITLE
[VS] TS/JS support in Visual Studio

### ISSUE THREAD

**Issue by abuchholtzau** [MicrosoftDocs/intellicode#27]
**OS Version** [macOS/Windows]: Windows
**Target Platform or Language** [e.g. Python]: TypeScript/JavaScript

**Steps to Reproduce / Scenario:**
Bring the TypeScript/JavaScript support into the Visual Studio IntelliCode extension

**Comment by markw-t** [comment]
I'm pleased to report that this feature is now available in Preview form, in Visual Studio 2019 16.1 Preview 3 and higher. 

To use it:

1. Download or update to Visual Studio 2019 16.1 Preview 3 or higher (preview downloads are [here](https://visualstudio.microsoft.com/vs/preview/))
2. Install any workload that supports JavaScript/TypeScript
3. Visit Tools-Options-IntelliCode-General, and switch the Preview feature "JavaScript/TypeScript base models" to "Enabled" and restart Visual Studio.

Thanks!
Mark
