### ISSUE TITLE
VSCode on Mac IntelliCode issues.

### ISSUE THREAD

**Issue by rubikron** [MicrosoftDocs/intellicode#270]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

On the VSCode app, there is an error saying "Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details."

Also, my pylint for VSCode hsa stopped working as soon as this problem surfaced.

**Comment by markw-t** [comment]
Sorry you're seeing this.

Please can you provide a little more detail on the following:
Product and Version [VS/VSCode]: ??
OS Version [macOS/Windows]:  ??
IntelliCode Extension Version: ??
Python Language Server setting in use (Jedi/Microsoft/Pylance)?

It would also be good to see a full contents of your IntelliCode output window in Visual Studio Code (you can see this by going to Output and selecting IntelliCode from the drop down on the right hand side of the output window)

Thanks!

**Comment by ayim** [comment]
@rubikron, would have the following information to share with us?

Product and Version [VS/VSCode]: ??
OS Version [macOS/Windows]: ??
IntelliCode Extension Version: ??
Python Language Server setting in use (Jedi/Microsoft/Pylance)?

**Comment by rubikron** [comment]
What is this for?

Thanks,
Rubikron

**Comment by ayim** [comment]
Hi rubrikon, looks like you filed a bug with us a while ago.
Just wanted to see if you were still having issues with IntelliCode in VSCode for Mac.

Cheers,
Aaron

**Comment by rubikron** [comment]
No I am not having issues anymore.
I got a new laptop and haven’t had the same issue

Thanks for checking up
Rubikron

**Comment by ayim** [comment]
Sweet, you take care!
