### ISSUE TITLE
autosuggestion not working

### ISSUE THREAD

**Issue by Rdxcoder3** [MicrosoftDocs/intellicode#273]
Issue Type: <b>Feature Request</b>

VS intellicode is not working on java 15 version please improve these features

Extension version: 1.2.11
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by markw-t** [comment]
Tagging @Eskibear to see this issue. 

@Rdxcoder3 can you provide some more information of what you see when you try to use IntelliCode in VSCode on Java 15? In particular what do you see in the IntelliCode Output window in VS Code (which you can see by selecting the View menu in VS Code, then selecting Output - once the Output pane shows up, choose VS IntelliCode from the drop down at the right hand end of the pane. The pane will show log details of what IntelliCode is doing (or failing to do) in many cases and this can help with debugging.

**Comment by laurava21** [comment]
I think that I have the same problem, but my version is Java 11, the autosuggestion doesn't work well, it works sometimes with recent words that I use. When I put for first time for example "Thread.", it doesn't suggest anything.

**Comment by Eskibear** [comment]
Try 1.2.11 again, let me know if the problem still exists. If you can stably reproduce the issue, can you provide below logs? That'd be very helpful for us to find out potential issues.
* Logs in IntelliCode Output window
* Logs in "Language Support for Java" Output window. (please change setting `java.trace.server` to "verbose" first)

**Comment by ayim** [comment]
@laurava21 just wanted to check in and see if you were having any further issues
