### ISSUE TITLE
[VS] Support for custom models in TS/JS

### ISSUE THREAD

**Issue by 2percentsilk** [MicrosoftDocs/intellicode#28]
**Product and Version** [VS/VSCode]: VS
**Target Platform or Language** [e.g. Node.js]: TypeScript/JavaScript

**Steps to Reproduce / Scenario:**
Bring custom model support to TS/JS in Visual Studio

**Comment by catycaldwell** [comment]
Normalize labels according to GitHub issues

**Comment by ayim** [comment]
Hey folks, we have deprecated the custom model feature. Some languages are offered the deep re-rerank model - particularly, Python in VSCode, C# in VS and C# Dev Kit. No further languages to announce at this time.

https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
