### ISSUE TITLE
C# ?

### ISSUE THREAD

**Issue by pedro15** [MicrosoftDocs/intellicode#280]
When we can expect to get C# added to this plugin?

i mean the original intellicode has C# in visual studio 2019, why we can't get it on visual studio code?

**Comment by sonicbhoc** [comment]
I have the same question.

**Comment by pixeldashgames** [comment]
same question here

**Comment by markw-t** [comment]
I believe this issue is a dupe of #81 in this repo. If folks agree I'll merge its votes into that item.

**Comment by tacosontitan** [comment]
> I believe this issue is a dupe of #81 in this repo. If folks agree I'll merge its votes into that item.

Yes, it's a dupe.

**Comment by ayim** [comment]
@markw-t, merging and closing.
