### ISSUE TITLE
Import not working properly !

### ISSUE THREAD

**Issue by tarunkishore2303** [MicrosoftDocs/intellicode#281]
**Product and Version** [VS/VSCode]:
![image](https://user-images.githubusercontent.com/53224551/112746566-31b5d580-8fcd-11eb-82a1-5d5c032d4157.png)

**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**:  1.2.12
**Target Platform or Language** : Java

**Steps to Reproduce / Scenario:**

https://user-images.githubusercontent.com/53224551/112746597-6164dd80-8fcd-11eb-9920-9cc846c56f96.mp4

**Comment by markw-t** [comment]
Thanks for the report. This looks like a Java extension issues, so tagging @Eskibear to take a look

**Comment by Eskibear** [comment]
I can repro it. Same when IntelliCode is not installed. 


https://user-images.githubusercontent.com/2351748/113327732-e3e2f980-934d-11eb-8617-35db0536e7b5.mp4

**Comment by markw-t** [comment]
Thanks @Eskibear - I will leave the investigation with you as it's not an IntelliCode issue. OK?

**Comment by Eskibear** [comment]
Sure. I just created an issue for Java extension. We'll track and fix it there.

**Comment by markw-t** [comment]
Great! Closing this issue in favor of the one @Eskibear raised above.
