### ISSUE TITLE
Typescript is die in 5 times 

### ISSUE THREAD

**Issue by z20240** [MicrosoftDocs/intellicode#283]
Issue Type: <b>Bug</b>

Typescript is die in 5 times 

Extension version: 1.2.12
VS Code version: Code 1.55.1 (Universal) (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin arm64 20.3.0
Remote OS version: Linux x64 5.4.0-1040-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 555720ac-1460-45e8-8703-c6c6d26ab997|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 35.236.151.96|
|OS|Linux x64 5.4.0-1040-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (4 x 2199)|
|Memory (System)|15.64GB (7.56GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by ayim** [comment]
@z20240 are you still experiencing issues here?

**Comment by ayim** [comment]
@z20240 would love to hear from you if you're still experiencing issues.
Feel free to open a new ticket!
