### ISSUE TITLE
Difference between pylance and intellicode for python

### ISSUE THREAD

**Issue by DoS007** [MicrosoftDocs/intellicode#284]
I didn't find any information about that. Can someone name the differences between pylance extension and additionally installing intellicode extension for python programming on vscode (since pylance already uses ai?)? (Or maybe the appropriate place to get these information)

Thanks, greets, DoS

**Comment by markw-t** [comment]
@DoS007 - IntelliCode (for Python in VS Code) has only one feature at present: it provides the prioritized "stars" at the top of the completions list which show the most likely completions for your current coding context at the top of the completions list. You can read about what the IntelliCode extension for Visual Studio Code provides [here](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code) - see example for Python below:

![image](https://user-images.githubusercontent.com/12836119/114468147-e2140400-9b9f-11eb-9f41-d35449501a94.png)

Pylance by contrast is a full language service which provides language support for Python overall - see @savannahostrowski 's [blog post](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/) announcing it from last summer.  IntelliCode augments Pylance's capabilities with AI-assisted completion recommendations. 

I hope that clarifies?

Tagging @savannahostrowski to see and comment

**Comment by DoS007** [comment]
@markw-t Thank you.

I read your both links and tested myself.  So everything which the IntelliSense addon adds is to move some popular used APIs to the top. Ok, I thought at first it would also add more things like further completion recommendation like tabnine or kite (because of the naming 'artificial intelligence-assisted ').

Pylance doesn't provide this either ('code completion' probably means the api part), if I'm correct.

Apart from that, the language servers for python will probably be: Pylance vs JediLSP (since Jedi will become legacy because of JediLSP and Microsoft's (first) python language server will become legacy for Pylance).

Do you of a feature comparison post between Pylance vs JediLSP (as this will be the interesting point in the future)? In a quick search I didn't find that?

Greets DoS007

**Comment by markw-t** [comment]
Thanks for the feedback! PyLance's code completion is the non-starred part of the completions lists. 

I'll tag @savannahostrowski to address your question on comparison of PyLance and Jedi.

**Comment by savannahostrowski** [comment]
@DoS007 We don't currently have any documentation on the differences between JediLSP and Pylance but we are working on it. I'll update here when that's available.

**Comment by DoS007** [comment]
@savannahostrowski Thank you. Sounds good.

**Comment by ayim** [comment]
@luabud is it still relevant for us to have documentation comparing JediLSP and Pylance?

**Comment by luabud** [comment]
@ayim potentially! it's still on our backlog but we haven't made progress yet

**Comment by ayim** [comment]
@luabad gotcha, i'll leave this item for y'all to track in your repo then, thanks!!
