### ISSUE TITLE
[VS] PowerShell support

### ISSUE THREAD

**Issue by 2percentsilk** [MicrosoftDocs/intellicode#29]
**Product and Version** [VS/VSCode]: VS
**Target Platform or Language** [e.g. Node.js]: PowerShell

**Steps to Reproduce / Scenario:**
Add PowerShell support to Visual Studio Intellicode

**Comment by catycaldwell** [comment]
Normalizing labels

**Comment by JT114881** [comment]
Any plans on implementing this?

**Comment by ayim** [comment]
Tagging @[StevenBucher98](https://github.com/StevenBucher98)

**Comment by ayim** [comment]
Powershell team have actually added command and parameter name completion... along with a host of other features:
https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/tab-completion?view=powershell-7.3#built-in-tab-completion-features
