### ISSUE TITLE
i got an error. "Sorry, something went wrong activating IntelliCode support for Python."

### ISSUE THREAD

**Issue by devanghingu** [MicrosoftDocs/intellicode#290]
I just updated **vscode** after lunch. And i got following error in notification. 

> Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

Therefore i checked output window and i got following logs there. 
`Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at g._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1743:3364)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1743:3245
Error while activating Python: {}`

And i noticed that Jupyter extension installed automatically due to "Python" extension depends on this

**Comment by tzm41** [comment]
Same. IntelliCode version 1.2.13. Python version 2021.5.829140558.

**Comment by kamilpiwko** [comment]
Same here. Pylance v2021.5.1, Python v2021.5.829140558. Working in WSL2.

**Comment by markw-t** [comment]
Tagging relevant folks:
1. @savannahostrowski @luabud for Python & Pylance
2. @DavidObando @osobeso @leti367 for IntelliCode

**Comment by savannahostrowski** [comment]
Hey folks - could you tell me what version of Python you are using? 

In terms of Jupyter, we have plans to make it an optional dependency, but currently the two extensions are tightly coupled because the Jupyter extension was created from the core Python extension.

**Comment by devanghingu** [comment]
Hi @savannahostrowski,
i m using following python version is my **ubuntu 18.04**.
> For Python2 -> Python 2.7.17
> For Python3 -> Python 3.6.9

**Comment by DimitrisBovasianos** [comment]
downgrade the version worked for me so far.

**Comment by devanghingu** [comment]
> downgrade the version worked for me so far.

about what?

**Comment by savannahostrowski** [comment]
@devanghingu Could you try and update the Python extension? We just released a new version which might fix this.

cc: @jakebailey in case there's more to follow up on.

**Comment by devanghingu** [comment]
@savannahostrowski  Thanks for a quick update. 
I tested on both machines. It works fine now. :smiley:

**Comment by markw-t** [comment]
Thanks for confirming, @devanghingu !
@tzm41 @kamilpiwko I'm not sure if your Python versions are similar to @devanghingu's - but if they are @savannahostrowski 's suggestion may work for you too. If not can you share your Python versions ?

/cc: @jakebailey

**Comment by kamilpiwko** [comment]
Looks that after today's update everything got back to normal. Thanks a lot!

**Comment by markw-t** [comment]
Closing out based on @kamilpiwko and @devanghingu's confirmation that the Python extension update fixed them. @tzm41 if you are still seeing problems please share your Python versions.

**Comment by tzm41** [comment]
Issue fixed. Thank you for the work!

**Comment by markw-t** [comment]
That's great to hear @tzm41 ! Thanks for confirming.

**Comment by bnicholas89** [comment]
I'm getting the same error now. 
Python Version: 3.9.6

Output:

Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1523:3364)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1523:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
