### ISSUE TITLE
Sharing team models in git (non github) repo

### ISSUE THREAD

**Issue by krishnan-unni** [MicrosoftDocs/intellicode#291]
Question
---------------

In the Team completions models, according to this document here: https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#types-of-team-completions-models the repository associated team models could be shared as long as they are git-sourced.

But in the document it only explains on how to integrate to GitHub repos and Azure pipelines.

I have a git repo which is not public (with bitbucket). I want to integrate IntelliCode Team completions with my CI build. Is that possible? Are there any documentations on how to generate models with my build?

**Product and Version** [VS/VSCode]: VS 2019
**OS Version** [macOS/Windows]: Windows
**Target Platform or Language** [e.g. Node.js]: C#

**Comment by markw-t** [comment]
Hi @krishnan-unni. 

Sorry for the inaccuracy of the documentation here – we will correct that. Whilst the distribution mechanism we use to associate team models with a repository works with any flavor of git repo, the only path we support for setting up automatic retraining and distribution of a team model as part of your CI processes is via GitHub actions or Azure DevOps tasks, as you note.  
 
However, you may not need to distribute a team model at all, if you’re using Visual Studio 2019 v16.8 or higher and can simply enable machine-associated team completions locally (see https://docs.microsoft.com/en-us/visualstudio/intellicode/quickstart-team-completions#train-models-for-team-completions) . Each team member who does this will see team completions.

**Comment by markw-t** [comment]
I've fixed the doc issue so I'm closing this issue out; let me know if the machine-associated route works for you @krishnan-unni
