### ISSUE TITLE
Activating Python extension Error while activating Python: {}

### ISSUE THREAD

**Issue by Aditya-R-K** [MicrosoftDocs/intellicode#292]
Moving repro details to body:

Language server is set to Pylance. Acquiring model Acquiring model 'intellisense-members-lstm-pylance' for python Querying IntelliCode service for available models. vs-intellicode-python was passed a model: {}. Downloading model. Starting download of https://intellicodeprodstorage.blob.core.windows.net/models-prod-output/Output_E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19?skoid=bf9239ea-04ee-49e6-8b41-ee3069ca2a1b&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-05-20T12%3A51%3A54Z&ske=2021-05-21T12%3A51%3A54Z&sks=b&skv=2020-02-10&sv=2020-02-10&se=2021-05-20T17%3A38%3A52Z&sr=b&sp=r&sig=SO5KT24nkd6Etnosx1nr0XAUmdhCMI1g69o9XfqSTHE%3D Download complete. Activating Python extension Error while activating Python: {}

**Comment by markw-t** [comment]
Tagging @savannahostrowski @luabud for this as it seems likely a PyLance/Python issue.

**Comment by markw-t** [comment]
@Aditya-R-K can you give us a few more details please?
1.What version of the Python extension are you running?
2.What version of VS Code are you using?
3.What Python runtime are you using?

**Comment by Aditya-R-K** [comment]
Version 3.9.5

**Comment by Aditya-R-K** [comment]
Python Version = 3.9.5

**Comment by Aditya-R-K** [comment]
Python version = 3.9.5
VS code version = 1.56.2
What is runtime version ?

**Comment by markw-t** [comment]
Thanks @Aditya-R-K ! Runtime is the Python version (yours is 3.9.5 from the above).

By my Q1 I meant the version of the Python extension in VS Code that you are running (e.g. on my machine it is v2021.5.842923320, see the extensions pane on VSCode below):
![image](https://user-images.githubusercontent.com/12836119/119268539-4b783100-bba8-11eb-9d24-1256897ce1e5.png)

**Comment by Aditya-R-K** [comment]
Python = v2021.5.842923320
@markw-t  sorry for late reply I'm busy for some days

**Comment by Aditya-R-K** [comment]
I'm redirected when clicked on error msg to "Visual  Studio intellicode "  v1.2.14
@markw-t

**Comment by markw-t** [comment]
Thanks @Aditya-R-K . 

Tagging @luabud and @savannahostrowski as from the error message you were seeing it seems like IntelliCode has correctly completed downloading its model, but the Python extension itself is failing to activate.

**Comment by savannahostrowski** [comment]
@jakebailey for his insight. 

If this is reproduceable, can you please enable trace logging in your settings.json via "python.analysis.logLevel": "Trace" and paste your logs from the Python and Python Language Server windows?

**Comment by jakebailey** [comment]
"Python extension Error while activating Python" implies that it's a Python extension problem so their logs may be more telling.

**Comment by Aditya-R-K** [comment]
> @jakebailey for his insight.
> 
> If this is reproduceable, can you please enable trace logging in your settings.json via "python.analysis.logLevel": "Trace" and paste your logs from the Python and Python Language Server output windows?

I have tried to paste it but it is read-only can't edit the defaultsetting json file

**Comment by jakebailey** [comment]
You don't want to edit the default settings, but your user settings.

You can also find the setting in the settings UI by searching for the name "python.analysis.logLevel".

**Comment by Aditya-R-K** [comment]
@jakebailey 
No setting found
![image](https://user-images.githubusercontent.com/84246389/120801679-17fdb500-c55f-11eb-82fb-2a50e9e7cb51.png)

**Comment by Aditya-R-K** [comment]
Thanks for helping me, don't know how but the python is working now
