### ISSUE TITLE
Python Intellisense Not working!!!

### ISSUE THREAD

**Issue by Rakshitjn** [MicrosoftDocs/intellicode#293]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by markw-t** [comment]
tagging @savannahostrowski and @luabud . 

@Rakshitjn please can you give a few more details about your Python setup:
1. What version of the Python extension are you running?
2. What version of VS Code are you using?
3. What Python runtime are you using?
4. It would be particularly helpful to see the contents of your Python and VS IntelliCode output windows for debugging purposes. You can check these by going to the View menu in VSCode and selecting Output. Then select VS IntelliCode from the dropdown and copy the contents of that output pane here. Do the same for the Python output window.

Thanks!

**Comment by Rakshitjn** [comment]
tagging @markw-t , @savannahostrowski and @luabud .
1. Python Extension - v2021.5.842923320
2. VS code - Version: 1.56.2 (system setup)
                    Commit: 054a9295330880ed74ceaedda236253b4f39a335
                    Date: 2021-05-12T17:13:13.157Z
                    Electron: 12.0.4
                    Chrome: 89.0.4389.114
                    Node.js: 14.16.0
                    V8: 8.9.255.24-electron.0
                    OS: Windows_NT x64 6.1.7601
3. Python Runtime - I didn't got you.
4. VS IntelliCode(Output) - Error while activating Python: {"detail":{"detail":{"code":"MODULE_NOT_FOUND","requireStack":["e:\\Rakshit\\Microsoft VS Code\\resources\\app\\out\\vs\\loader.js","e:\\Rakshit\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js","e:\\Rakshit\\Microsoft VS Code\\resources\\app\\out\\bootstrap-fork.js"]}}}
5. Python(Output)-Blank
6. Please Help me!!

**Comment by markw-t** [comment]
3. This is the version of Python you are running (e.g. if you're running Python 3 it might be 3.7.8 64 bit for instance)
 
Based on 4 it looks like you are having a problem with activating the whole Python extension. This is one for @savannahostrowski and @luabud .

**Comment by Rakshitjn** [comment]
Tagging @markw-t , @savannahostrowski and @luabud .

python version - 3.8.6 64 bit

Now, what should i Do??

**Comment by savannahostrowski** [comment]
Follow-ups:

1. What language server are you using (python.languageServer)? 
2. Could you paste your logs from the Python output window so we can have a look? 

![image](https://user-images.githubusercontent.com/8949415/119373052-dae71800-bc6c-11eb-84bc-be444631fa50.png)

**Comment by Rakshitjn** [comment]
Tagging @savannahostrowski
Actually, there is no option for python in my output section
![030c681a-4a02-4858-851d-752415771533](https://user-images.githubusercontent.com/64477084/119488834-9f397480-bd78-11eb-97e1-6953ab01dabb.jpg)

**Comment by Rakshitjn** [comment]
Tagging @markw-t , @savannahostrowski and @luabud .
Hey, anyone here to help me??

**Comment by luabud** [comment]
Hi @Rakshitjn, I think it may be a bad install of the Python extension. Can you try uninstalling it? 


![image](https://user-images.githubusercontent.com/45497113/119846358-eb8ecc80-bebe-11eb-9c3b-f248d9705d85.png)

After you uninstall it, close VS Code and open it again, then install the Python extension once more. The reload may not be necessary but it's worth doing it just in case. 

If it doesn't work, I can show you how to delete the Python extension folder and we can try it again. But hopefully it will work!

**Comment by Rakshitjn** [comment]
Tagging @markw-t , @savannahostrowski and @luabud .
I have tried all things possible like reinstalling extension, even I reinstalled Vs code but still nothing changed!

**Comment by Rebel154** [comment]
I'm having the same issue as above. I've uninstalled/installed both the python and the VS Intellicode extensions with no change. Likewise, I've restarted VS Code and my PC too.

The error message is:

"Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details."

Visual Studio Code - Insiders

Version: 1.57.0-insider (user setup)
Commit: 20df87725d3ce4a501187f0240c2f159aa0ad2a5
Date: 2021-06-03T06:38:36.085Z (11 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Intellicode Extension Version: 1.2.13 and 1.2.14 tried

Target Language: Python 3 (version 3.9.5 64 bit installed

Steps to reproduce: Open a python source file (Workspace trusted). The error message pops up almost immediately.

[VS Intellicode Ouput.txt](https://github.com/MicrosoftDocs/intellicode/files/6593511/VS.Intellicode.Ouput.txt)
[Python Output.txt](https://github.com/MicrosoftDocs/intellicode/files/6593512/Python.Output.txt)

Thank you.

**Comment by rickstaa** [comment]
@Rebel154 I had the same problem. I managed to fix it using the following steps:

1. Remove the python extension.
2. Make sure the python extension insiders config `"python.insidersChannel": "daily"` statement is removed from your `settings.json`.
3. Remove the Intellicode extension. 
4. Reinstall the python extension.
5. Reinstall the Intellicode extension.

After these steps, I was able to re-enable the daily channel for the python extension without having any issues.

**Comment by Rebel154** [comment]
@rickstaa I just followed your instructions above and the problem persists. I'm now on the latest VS Code too. One difference is that you're running Linux whilst I'm on Windows 10.

Thanks for the advice though.

**Comment by rickstaa** [comment]
@Rebel154 Ah, so the steps only work on Linux. That might be helpful for the developers trying to solve this issue. If somebody experiences problems after following the steps on Linux, please comment below.

**Comment by Rakshitjn** [comment]
Tagging @markw-t , @savannahostrowski and @luabud .
Hey anyone here helping me?? I am stuck!!!!

**Comment by luabud** [comment]
If you run the command "Extensions: Open Extensions Folders" from the command palette, it will open the folder where all extensions live. Sometimes when uninstalling extensions VS Code may leave a few folders behind and that could cause issues.
Can you try deleting all the ms-python.python folders as well as the intellicode ones? You will probably need to close VS Code before you delete them.

**Comment by Rebel154** [comment]
> If you run the command "Extensions: Open Extensions Folders" from the command palette, it will open the folder where all extensions live. Sometimes when uninstalling extensions VS Code may leave a few folders behind and that could cause issues.
> Can you try deleting all the ms-python.python folders as well as the intellicode ones? You will probably need to close VS Code before you delete them.

@luabud  I've just deleted both extensions again (I assume that is what I should have done first) and located the extensions folder. There are no remaining folders related to the two extensions in the that folder.

**Comment by Rakshitjn** [comment]
> If you run the command "Extensions: Open Extensions Folders" from the command palette, it will open the folder where all extensions live. Sometimes when uninstalling extensions VS Code may leave a few folders behind and that could cause issues.
> Can you try deleting all the ms-python.python folders as well as the intellicode ones? You will probably need to close VS Code before you delete them.

@luabud  Hey, I tried this but nothing happened it is showing ("Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.")

**Comment by Rebel154** [comment]
@luabud I didn't immediately reinstall the two extensions last night when I was doing the testing. However, I have just reinstalled them both and the error message is no longer popping up.

This is the VS IntelliCode Output text. Looks like something has changed somewhere, but I know not what.

`Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Downloading model.
Starting download of https://intellicodeprodstorage.blob.core.windows.net/models-prod-output/Output_E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19?skoid=bf9239ea-04ee-49e6-8b41-ee3069ca2a1b&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-06-05T13%3A02%3A10Z&ske=2021-06-06T13%3A02%3A10Z&sks=b&skv=2020-02-10&sv=2020-02-10&se=2021-06-05T17%3A25%3A37Z&sr=b&sp=r&sig=JNIu56Y9aAVTZE%2FPO6igoHIqSSngYCpWc6sM%2Bccz02Y%3D
Download complete.
Activating Python extension`

**Comment by Rakshitjn** [comment]
> @luabud I didn't immediately reinstall the two extensions last night when I was doing the testing. However, I have just reinstalled them both and the error message is no longer popping up.
> 
> This is the VS IntelliCode Output text. Looks like something has changed somewhere, but I know not what.
> 
> `Language server is set to "Default". Pylance is used as current language server. Acquiring model Acquiring model 'intellisense-members-lstm-pylance' for python Querying IntelliCode service for available models. vs-intellicode-python was passed a model: {}. Downloading model. Starting download of https://intellicodeprodstorage.blob.core.windows.net/models-prod-output/Output_E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19?skoid=bf9239ea-04ee-49e6-8b41-ee3069ca2a1b&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-06-05T13%3A02%3A10Z&ske=2021-06-06T13%3A02%3A10Z&sks=b&skv=2020-02-10&sv=2020-02-10&se=2021-06-05T17%3A25%3A37Z&sr=b&sp=r&sig=JNIu56Y9aAVTZE%2FPO6igoHIqSSngYCpWc6sM%2Bccz02Y%3D Download complete. Activating Python extension`

Is ut working now?

**Comment by Rebel154** [comment]
@Rakshit It appears to be working for me at the moment.

These the 2 outputs from the extensions;

[VS IntelliCode Output.txt](https://github.com/MicrosoftDocs/intellicode/files/6604052/VS.IntelliCode.Output.txt)
[Python Output.txt](https://github.com/MicrosoftDocs/intellicode/files/6604053/Python.Output.txt)

**Comment by luabud** [comment]
Thanks for confirming that it's working for you now, @Rebel154. I'm honestly not sure what was causing the issue, my best guess is that it was a bad installation sort of problem.

@Rakshitjn is is still not fixed for you? 

Just for future reference, my guidance for those who face this issue is:
- Make sure you have the latest version of VS Code
- Close VS Code  
- Delete the Python, Pylance and IntelliCode extension folders
- Reopen VS Code
- Install the latest versions of Python, Pylance and IntelliCode extensions

**Comment by Rakshitjn** [comment]
@luabud It is still not working for me!!!

**Comment by luabud** [comment]
@Rakshitjn can you try it on VS Code Insiders? You can install it here: https://code.visualstudio.com/insiders/
And then install the Python and IntelliCode extensions on it. You can install it side by side with regular VS Code, one should not impact the other at all. The only difference is that VS Code Insiders get updated more regularly than "regular" VS Code. 

The underlying problem is that the Python extension isn't activating for you, but there's nothing we can do on IntelliCode or Python extension side of things because ultimately it's VS Code that controls the activation. If even VS Code insiders doesn't work, we can take it to the VS Code team at http://github.com/Microsoft/vscode, to see if they can give us some light.

**Comment by Rakshitjn** [comment]
Hey @luabud, Thanks for suggesting me VS Code Insiders!! The Insider is working for me! Thanks for your help!!
