### ISSUE TITLE
Intellicode suggestions ignore the 'else' keyword in the java language

### ISSUE THREAD

**Issue by csturmer** [MicrosoftDocs/intellicode#294]
**Product and Version** [VS/VSCode]: 
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 18.7.0

**OS Version** [macOS/Windows]:
macOS Mojave 10.14.6

**IntelliCode Extension Version**: 
v1.2.14

**Target Platform or Language** [e.g. Node.js]:
Java

**Steps to Reproduce / Scenario:**
1.  Type in an if() {} else statement and while typing in 'else' it will pop up suggestions that do not include 'else' so you have to hit space after the 'else' or hit 'esc' to remove the suggestions to continue and not have it apply the recomended substitution.  NOTE: While typing the else and you get to the 's' and suggestions picked ElementsTable because it matched on El.....s.....

![IMG_5603](https://user-images.githubusercontent.com/929031/119360912-b725d100-bc70-11eb-997a-80e06b30c18a.jpg)

**Comment by markw-t** [comment]
Hi @csturmer - it looks like this is a question regarding the regular auto-completion/IntelliSense for Java (no "stars" are shown in your screen shot, so it doesn't seem like IntelliCode is involved, unless I'm missing something?).  As such I'm tagging @Eskibear to take a look as it seems like a Java extension question.

**Comment by csturmer** [comment]
Hi Mark,

Sorry.  I am fairly new to VSCode and not sure where to direct things yet.  Thank you for passing it  to the correct place/person.

BTW Love this editor!

--Carl--

**Comment by markw-t** [comment]
No problem at all, glad to help. And glad you are enjoying VS Code! 

I hope you have chance to install the [IntelliCode extension for VS Code](https://aka.ms/vsic/xtn/vscode) and would love to hear any feedback you have there.

**Comment by markw-t** [comment]
BTW for Java extension pack issues, you may want to file (and search for others filing) at https://github.com/microsoft/vscode-java-pack/issues

**Comment by csturmer** [comment]
I had both IntelliCode and the JavaExtensionPack installed.  I was trying different things to see if I could resolve the issue. I sure might have had IntelliCode disabled when I did the screen cap.  I was having trouble telling where one extension's features started and another stopped so I was thrashing around a bit.  In the end I just took a wild guess that it might be IntelliCode.  After your comment and some more experimentation here, it appears you were correct.  I disabled the Java Extension Pack and the problem went away but so did any offered suggestions ;-), so that pretty much nails it down.

In the end though the problem seems to be happening with 'else' the other keywords I tried showed up as the first item in the list (if, while, try, catch, for, etc.).  So the issue seems to be isolated.

Should I go ahead and repost the issue in the Java Extension Pack section now?  Is that the correct approach?

Thank you!
--Carl--

**Comment by markw-t** [comment]
I think this will end up being a core Java extension pack issue, but I'll let @Eskibear make the final call and migrate to the other repo's issues as appropriate.  From the screenshot it appears you're seeing a partial match listing in IntelliSense (so it matches the characters e l s and e but not necessarily contiguously) -  @Eskibear can comment on whether that is expected given the else statement already being in the buffer.

Note that the extension pack actually includes IntelliCode anyway by the way.

**Comment by csturmer** [comment]
Sorry, still tinkering over here.  It appears to be a bit more complicated than 'it never includes else'.

If I simply find a blank line in a .java file and type else, it is at the top of the suggestions list.

However if I type in:

if( )
{
}
else

It does not appear in the suggestions list.

Examples:

**Comment by Eskibear** [comment]
@csturmer That's probably because when there's syntax error, Java Language Server doesn't recognize it as a valid if-block.

For example if you type in:
```
if (true)
{
}
else
```
"else" should appear in the suggestion list. 

BTW, it's behavior of Java Language Server, if you have further issues/thoughts, please open ticket in https://github.com/redhat-developer/vscode-java/issues

**Comment by csturmer** [comment]
Hi!

The reason I brought this up in the first place was because it became very frustrating to have to hit escape or enter and then backspace to remove the space after an else statement because it was not offering else as the first item in the list of suggestions.

Typically I don't have a syntax error when I am coding up an if else but the example I provided was not as careful, it was simply an example to show the problem.  I was not having this issue with any other java language keywords so I figured it was something you might want to know about.

Thanks!
--Carl--

**Comment by csturmer** [comment]
Hi!

Tell you what though.  I will keep an eye on my specifics and see if there is something else that is triggering it.  I will make sure that if I have an incomplete or incorrect if else statement I recognize the mistake and see if there are any other things that might cause the issue.

Thanks for you time on this!
--Carl--

**Comment by Eskibear** [comment]
@csturmer Thank you for all the information. If you have further findings or thoughts, I strongly recommend that you open new issues in Java extension repository, so that more developers working on or using that extension will see it. And hopefully we can improve the overall experience which also benefits other developers.

**Comment by markw-t** [comment]
Given the comments above I'm closing this item out - per @Eskibear please go ahead and raise new issues on the Java extension repo for maximum visibility @csturmer and thanks for all your comments!
