### ISSUE TITLE
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found

### ISSUE THREAD

**Issue by mage1k99** [MicrosoftDocs/intellicode#295]
**Product and Version** [VS/VSCode]: 1.57.0-insider (user setup) (commit 20df87725d3ce4a501187f0240c2f159aa0ad2a5)
**OS Version** [macOS/Windows]: Windows 10 (10.0.19042)
**IntelliCode Extension Version**: v1.2.14
**Target Platform or Language** [e.g. Node.js]: Python
**Language Server** : Pylance
**Pylance Extension** : v2021.6.0
**Python Extension** : v2021.6.897246044-dev
**Python Version**: 3.8.2
**Python venv is used for virtual environment.**

**Steps to Reproduce / Scenario:**

1. Updated VSCode Insiders which had issues with python juypter extension and has been fixed in update
2. Then It fails to activate the extension. log message is below
```
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

### Complete Log of extension

```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

I tried to install insider pylance by enabling python Insider Channel but nothing seems to help.

Old version released 2 months before does not works well

**Comment by solarmist** [comment]
I'm hitting this issue as well. It started this week.

```Version: 1.57.0-insider
Commit: 20df87725d3ce4a501187f0240c2f159aa0ad2a5
Date: 2021-06-03T06:00:36.788Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0```

```Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

**Comment by solarmist** [comment]
Here's the log from the Python extension
```Error 2021-06-03 10:31:54: stderr jediProxy Error (stderr) /Users/solarmist/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-06-03 10:31:54: stderr jediProxy Error (stderr) /Users/solarmist/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-06-03 10:31:54: stderr jediProxy Error (stderr) /Users/solarmist/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-06-03 10:31:54: stderr jediProxy Error (stderr) /Users/solarmist/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]
```

**Comment by ayim** [comment]
Hi there! Aaron from the Intellicode team here - we're looking into this.

Repro'd in...

VS Code 1.57.0 and 1.57.0-insider.
Python: v2021.5.842923320
Pylance: v2021.6.1
OS: Windows 10 21H1 Build 19043.1057

**Comment by ayim** [comment]
@mage1k99 @solarmist 

Please upgrade to 2021.5.926500501 of the Python extension and let us know if the issue persists: 
[marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2021.5.926500501/vspackage](url)

**Comment by mage1k99** [comment]
yes, I have updated and the issue is fixed, thanks for the response :)

closing the issue
