### ISSUE TITLE
Issue with activating IntelliCode support for TypeScript/JavaScript

### ISSUE THREAD

**Issue by frankjlin16** [MicrosoftDocs/intellicode#297]
**Product and Version** [VS/VSCode]: VS Code v1.56.2
**OS Version** [macOS/Windows]: Windows 10 Pro
**IntelliCode Extension Version**: v1.2.14
**Target Platform or Language** [e.g. Node.js]: JavaScript

**Steps to Reproduce / Scenario:**
1. Opened a Java file. IntelliCode activates correctly.
2. Next, opened a JavaScript file and IntelliCode throws activation error
![image](https://user-images.githubusercontent.com/67761168/120750676-9dc82480-c4bb-11eb-860c-906e7a2be778.png)

**Output Log:**
```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"c:\\Users\\frank\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.14\\cache\\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
Java Extension is activated.
JavaAPI: {"apiVersion":"0.6","javaRequirement":{"java_home":"C:\\Program Files\\Java\\jdk-16.0.1","java_version":16},"status":"Started","serverMode":"Standard"}
Enabled IntelliCode for Java.
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
Error while activating TypeScript/JavaScript: {}.
```

**Comment by ayim** [comment]
@frankjlin16 would love to hear from you if you're still seeing this issue.
Feel free to open a new issue!

**Comment by TheArgentinian** [comment]
> @frankjlin16 would love to hear from you if you're still seeing this issue. Feel free to open a new issue!

I'm seeing the same issue:

Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
**Error while activating TypeScript/JavaScript: {}.**

**Comment by mat-wang** [comment]
> 

The same issue and also the same log.

**Comment by DaDummy** [comment]
Just happened to me, too.

@ayim is any additional information needed in order to reopen this issue for at least improving the error message?

**Comment by DaDummy** [comment]
More context:

This is the whole content of the CS IntelliCode Output window, so there is pretty much nothing to go on for investigating this issue from the user perspective:
```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
Error while activating TypeScript/JavaScript: {}.
```

**Comment by hakshu25** [comment]
The same problem occurred. The same log was output.

```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
Error while activating TypeScript/JavaScript: {}.
```

**Comment by tomo-x7** [comment]
I had the same problem and the same log.
```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
Error while activating TypeScript/JavaScript: {}.
```

**Comment by zayne-wang** [comment]
@ayim 

Since this issue is still there, do you consider to reopen it? And if any additional info needed?

Or we could open a new issue so that anybody could track this?

**Comment by COOLIRON2311** [comment]
@ayim The issue should be reopened because the problem is still there

**Comment by nethriis** [comment]
@ayim This is not fixed why you closed the issue as resolve ?

**Comment by bryannrodrigues** [comment]
Same problem today after updanting intellicidde extension.

**Comment by gui-ying233** [comment]
Same

**Comment by vivlimmsft** [comment]
We'll use #545 to track this. It's plainly visible from this thread that it's not a new issue, but yesterday's update seems to have made it more likely, because the extension starts up faster now. I'll write more details on #545.
