### ISSUE TITLE
Got an error: "Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details."

### ISSUE THREAD

**Issue by Vikin05** [MicrosoftDocs/intellicode#298]
I got following error in notification.

Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

Therefore i checked output window and i got following logs there.

Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///C:/Users/vikin/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///C:/Users/vikin/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}

**Comment by ayim** [comment]
Hi @Vikin05 thanks for reporting this!
What version of Operating System, VS Code, Python, and Pylance are you using?

**Comment by ayim** [comment]
May be related to #295, #296.
Repro'd in...

* VS Code 1.57.0 and 1.57.0-insider.
* Python: v2021.5.842923320
* Pylance: v2021.6.1
* OS: Windows 10 21H1 Build 19043.1057

**Comment by Vikin05** [comment]
Thanks @ayim. It has been fixed and working fine for me now.

**Comment by ayim** [comment]
@GeGrieftGames @noelleleigh @GPla 

Please upgrade to 2021.5.926500501 of the Python extension and let us know if the issue persists: 
[marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2021.5.926500501/vspackage](url)
