### ISSUE TITLE
The Microsoft Python language service breaks CTags and the VS Code Outline view.

### ISSUE THREAD

**Issue by JeffHanna** [MicrosoftDocs/intellicode#3]
Switching away from Jedi to the Microsoft Python language service causes ctags.exe to throw errors while it is attempting to generate tags. It also neuters the recently added VS Code Outline panel. The Outline ever updates with navigable information such as method names, class names, etc...

Re-enabling Jedi and disabling the Intellicode extension restores both the CTags and Outline view functionality.

**Comment by markw-t** [comment]
@JeffHanna thanks for the report. For issues with the new Python language service itself, rather than the IntelliCode recommendations, please can you report at https://github.com/Microsoft/vscode-python/issues/new ?

Thanks for trying IntelliCode!
