### ISSUE TITLE
[VS Code] PowerShell support

### ISSUE THREAD

**Issue by 2percentsilk** [MicrosoftDocs/intellicode#30]
**Product and Version** [VS/VSCode]: VS Code
**Target Platform or Language** [e.g. Node.js]: PowerShell

**Steps to Reproduce / Scenario:**
Add PowerShell support to the VS Code IntelliCode extension

**Comment by guidooliveira** [comment]
Yes Please!

**Comment by ljtill** [comment]
+1 - would love to have PowerShell support!

**Comment by ravidsinghbiz** [comment]
+1 - Yes Please.

**Comment by manoj2994** [comment]
yes

**Comment by drewjanderson** [comment]
Huzzah!

**Comment by hjorslev** [comment]
Yes please!

**Comment by fMichaleczek** [comment]
+1

**Comment by ravidsinghbiz** [comment]
+1

**Comment by catycaldwell** [comment]
Normalizing labels

**Comment by shtau1** [comment]
yes, please!

**Comment by ayim** [comment]
Tagging @[StevenBucher98](https://github.com/StevenBucher98)

**Comment by ayim** [comment]
Powershell team have actually added command and parameter name completion... along with a host of other features:
https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/tab-completion?view=powershell-7.3#built-in-tab-completion-features
