### ISSUE TITLE
Typo in vsintellicode.modify.editor.suggestSelection

### ISSUE THREAD

**Issue by 4310V343k** [MicrosoftDocs/intellicode#300]
**Product and Version** [VS/VSCode]: Code 1.57.0 (https://github.com/microsoft/vscode/commit/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
**OS Version** [macOS/Windows]: Windows_NT x64 10.0.19042
**IntelliCode Extension Version**: v1.2.14
**Target Platform or Language** [e.g. Node.js]: VS Code

**Steps to Reproduce / Scenario:**

I'm pretty sure it should be `automaticallyOverrideDefaultValue` instead of `automaticallyOverrodeDefaultValue`

1. Open settings or settings.json
2. Search or create `vsintellicode.modify.editor.suggestSelection`, open drop down menu or press shift+space (or whatever shortcut you have for autocompletion)
3. Watch the typo

**Comment by vivlimmsft** [comment]
This isn't a typo, it is intentionally written in past tense. IIRC (it's been a while since I looked too closely at it), the setting is used to store state tracking _whether_ our extension set suggestSelection to override the default.
