### ISSUE TITLE
Intellicode insiders edition breaks emmet abbreviations

### ISSUE THREAD

**Issue by rickstaa** [MicrosoftDocs/intellicode#302]
**Version:** 1.58.0-insider
**Commit:** a81fff00c9dab105800118fcf8b044cd84620419
**Date:** 2021-06-17T05:16:54.194Z
**Electron:** 12.0.11
**Chrome:** 89.0.4389.128
**Node.js:** 14.16.0
**V8:** 8.9.255.25-electron.0
**OS:** Linux x64 5.8.0-55-generic
**IntelliCode Extension Version**: v1.0.6 (insiders) 

**Steps to Reproduce / Scenario:**

1. Enable the visual studio intellicode insiders extension.
2. Open a react project and create a functional component (see `functionalComponent.js` in [the example repository](https://github.com/rickstaa/emmet-intellicode-abbreviation-bug)).
3. See that the emmet abbreviation function is not working.
4. Disable the visual studio intellicode insiders extension.
5. See that the emmet abbreviations function is working.

![emmet-intellicode-problem](https://user-images.githubusercontent.com/17570430/122374366-9d6f6500-cf62-11eb-801d-3f9a385685a3.gif)

**Extra debug info:**
- Problem is not present when using the default intellicode extension or when disabling it.

**Comment by leti367** [comment]
I reproduced this bug. Seems the emmet UI is blocked, if we enable 'tab' for emmet, and press 'tab', we can still get emmet completion items. IMO this seems like a bug in vscode API.

**Comment by rickstaa** [comment]
@github-actions Bad decision.

**Comment by markw-t** [comment]
You are right @rickstaa - adding product-issue as this is a bug.

**Comment by leti367** [comment]
@rickstaa, This issue is fixed in vscode-insiders 1.59.0. Thanks!
