### ISSUE TITLE
Warning to necessary await statements 

### ISSUE THREAD

**Issue by sergiycheck** [MicrosoftDocs/intellicode#303]
**Product and Version** [VSCode]: May 2021 (version 1.57)
**OS Version** [Windows]: Microsoft Windows 10 Pro. Version: 10.0.19042 Build 19042 
**IntelliCode Extension Version**: v1.2.14
**Target Platform or Language** : JavaScript

**Steps to Reproduce / Scenario:**

	const fruitBasket = {
		apple:27,
		grape:0,
		pear:14
	}

	const sleep = (ms) => {
		return new Promise(resolve=>setTimeout(resolve,ms));
	}

	const getNumFruit = async (fruit) => {
		return sleep(1000).then(r=>fruitBasket[fruit])
	}

	const arrNames = ['apple','grape','pear'];

	const reduceSumEveryQuantity = async () => {

		const sum = await arrNames.reduce( async (promisedSum, fruit)=>{
			const sum  = await promisedSum;
			const num = await getNumFruit(fruit);
			console.log('got num from promise', num);
			return sum + num;
		},0);

		console.log('final sum ', sum);
	}

	await reduceSumEveryQuantity();

I have the following warning " 'await' has no effect on the type of this expression. ts(80007) " before "await arrNames..." and "await promisedSum" but these awaits are needed to execute code correctly.

**Comment by markw-t** [comment]
Hi @sergiycheck  . This appears to be a general TypeScript problem rather than IntelliCode. Tagging @uniqueiniquity who should be able to help you route this to the right repo for the issue.

**Comment by uniqueiniquity** [comment]
Hi @sergiycheck,
If you believe this is an issue with TypeScript, please file an issue on https://github.com/microsoft/typescript.
However, I was able to resolve the issue by changing the `reduce` operations `initialValue` to `Promise.resolve(0)`.
Note that providing annotations for `getNumFruit` caused a more helpful error to be produced.

```ts
const fruitBasket = {
	apple:27,
	grape:0,
	pear:14
}

const sleep = (ms) => {
	return new Promise(resolve=>setTimeout(resolve,ms));
}

const getNumFruit = async (fruit: string): Promise<number> => {
	return sleep(1000).then(r=>fruitBasket[fruit])
}

const arrNames = ['apple','grape','pear'];

const reduceSumEveryQuantity = async () => {

    const sum = await arrNames.reduce(async (promisedSum, fruit) => {
        const sum = await promisedSum;
        const num = await getNumFruit(fruit);
        console.log('got num from promise', num);
        return sum + num;
    }, Promise.resolve(0));

	console.log('final sum ', sum);
}

await reduceSumEveryQuantity();

export {};
```

**Comment by sergiycheck** [comment]
It worked. Warnings disappeared with using `Promise.resolve(0)`  from target js file.
