### ISSUE TITLE
Erro no intelliCode com python

### ISSUE THREAD

**Issue by leozd1** [MicrosoftDocs/intellicode#304]
Issue Type: <b>Bug</b>

Aparece essa mensagem sempre que uso o python no visual code
"Houve um erro ao ativar o suporte do IntelliCode para Python. Verifique as janelas de saída "Python" e "VS IntelliCode" para obter detalhes."

Como resolver? 
Agradeço qualquer ajuda

Extension version: 1.2.14
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.47GB free)|
|Process Argv|--crash-reporter-id 727103b0-8e2e-4a0a-8ae6-6f65cf8f91d6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
aatestflight:30331711
bridge0702:30333155

```

</details>

**Comment by DavidObando** [comment]
Oi @leozd1,

Você pode ver a janela de saída para VS IntelliCode e para Python, e colar o conteúdo aqui? Precisamos ver quais erros são relatados para ser útil. Você pode ver a janela de saída invocando-a através do menu:
> ![image](https://user-images.githubusercontent.com/950290/125342604-ee783c00-e309-11eb-83cf-387947fe769e.png)

Uma vez que a janela de saída esteja visível, selecione a saída VS IntelliCode para ver quais erros são relatados.
> ![image](https://user-images.githubusercontent.com/950290/125342792-22ebf800-e30a-11eb-9f80-8a59aac65550.png)

**Comment by leozd1** [comment]
Olá, aqui esta o anexo referente ao erro do IntelliCode

***@***.***D77782.9F9F25A0]

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: David ***@***.***>
Enviado:segunda-feira, 12 de julho de 2021 16:10
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [MicrosoftDocs/intellicode] Erro no intelliCode com python (#304)


Oi @leozd1<https://github.com/leozd1>,

Você pode ver a janela de saída para VS IntelliCode e para Python, e colar o conteúdo aqui? Precisamos ver quais erros são relatados para ser útil. Você pode ver a janela de saída invocando-a através do menu:

[image]<https://user-images.githubusercontent.com/950290/125342604-ee783c00-e309-11eb-83cf-387947fe769e.png>

Uma vez que a janela de saída esteja visível, selecione a saída VS IntelliCode para ver quais erros são relatados.

[image]<https://user-images.githubusercontent.com/950290/125342792-22ebf800-e30a-11eb-9f80-8a59aac65550.png>

**Comment by DavidObando** [comment]
Você poderia colar o texto da janela de saída aqui? O e-mail que recebi não tinha anexos.

**Comment by leozd1** [comment]
Olá, parece que a última atualização resolveu esse problema, não recebi mais o erro ao iniciar o vs code, agradeço a ajuda

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by DavidObando** [comment]
Obrigado, vou fechar este tíquete agora.
