### ISSUE TITLE
Vs-code IntelliCode (Auto-complete) works very slow in in wsl2 remote-env

### ISSUE THREAD

**Issue by starlord13599** [MicrosoftDocs/intellicode#305]
Issue Type: <b>Bug</b>

The issuse i've been facing is  the vs-code auto-completion works very slow in wsl2 environment. As soon i type my snippet shortcut and press tab the auto complete does not work

I have been looking and searching into this issue for a long time but nothing works.

Please help, its been decreasing my productivity,

Thank you in advance,

Extension version: 1.2.14
VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.33GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/home/deepp/node-projects/confienement --crash-reporter-id 24a94ed0-fa62-4178-a9a1-227755eeb185|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|Memory (System)|6.13GB (5.70GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by markw-t** [comment]
Sorry you're seeing this issue. Can you help us narrow things down a little bit? 

1. What languages are you coding in when you see the slowdowns
2. If you disable IntelliCode extension, do things improve or stay about the same? This will help us narrow down the possible root causes

Thanks!
Mark

**Comment by starlord13599** [comment]
Basically I code in JavaScript using Node and React framework.

Yes, If I turn off the IntelliCode extension the auto-completion, which is provided by other extensions (React/Redux snippets, Node snippets  etc)  works just fine and fast.

But turning on the IntelliCode lags things.

**Comment by markw-t** [comment]
Thank you for the rapid response. I have a couple of further follow-ups to clarify and help the team understand:
1. When you say "type your snippet shortcut and press tab" - which specific snippet shortcut are you talking about? Do you see this with all items in the method/property list in JavaScript, or just certain ones?
2. You mention that the issue is problematic specifically on a WSL2 environment. Have you had the opportunity to try the same machine NOT in a WSL2 environment? Can you help us understand what makes you link this behavior to that environment?
Thanks!
Mark

**Comment by starlord13599** [comment]
Thank you for still being in contact with me.

Basically it happens to every snippets, including the built in onces such as you mentioned above.

When i first started facing this issue i instantly tested it without WSL2, it was working fine and fast but it seems bit laggy when using WSL2 environment, Now i am not sure why that's happening.

**Comment by markw-t** [comment]
Thanks for the details and sorry for the inconvenience; we will take a look and see if we can reproduce this behavior; if not we may need your help capturing some traces.

**Comment by ayim** [comment]
@starlord13599 any chance you're still seeing issues with this?

**Comment by starlord13599** [comment]
No @ayim , working fine now, thanks for the help.
