### ISSUE TITLE
Error: CLI Warning: 0 : The 'CSharp' analyzer was not able to collect data from the codebase.

### ISSUE THREAD

**Issue by kolappannathan** [MicrosoftDocs/intellicode#306]
**Product and Version**: GitHub IntelliCode Team Completions action
**OS Version**: Microsoft Windows Server 2019
**IntelliCode Extension Version**:  1.0
**Target Platform or Language**: C#

**Steps to Reproduce / Scenario:**
1. I tired to run the GitHub action on my [Web API boilerplate repo](https://github.com/kolappannathan/dotnet-web-api-boilerplate) which is a standard ASP.NET Web API project.
2. You can view the action logs [here](https://github.com/kolappannathan/dotnet-web-api-boilerplate/runs/3162695305?check_suite_focus=true)

Here is the full output

```
D:\a\_actions\microsoft\vs-intellicode\v1.0\dist\CLI\intellicode.exe train --directory D:\a\dotnet-web-api-boilerplate\dotnet-web-api-boilerplate --anonymous --verbosity n --user-agent GitHub
CLI Information: 0 : IntelliCode CLI Version 1.1.241.30581
CLI Warning: 0 : The 'CSharp' analyzer was not able to collect data from the codebase.
[]
(node:724) UnhandledPromiseRejectionWarning: Error: The process 'D:\a\_actions\microsoft\vs-intellicode\v1.0\dist\CLI\intellicode.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\microsoft\vs-intellicode\v1.0\dist\index.js:920:25)
    at ExecState.CheckComplete (D:\a\_actions\microsoft\vs-intellicode\v1.0\dist\index.js:903:18)
    at ChildProcess.<anonymous> (D:\a\_actions\microsoft\vs-intellicode\v1.0\dist\index.js:797:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by markw-t** [comment]
@osobeso can you take a look?

**Comment by osobeso** [comment]
@kolappannathan Hi, thanks a lot for taking the time of submitting this issue.
After further review it seems that the main problem is that the github agent's MSBuild version is not compatible with dotnet 5 sdk, therefore it's not being able to build the solution to extract patterns from it.

The current version being used by the default github agent seems to be 16.10.31424.327
(I got that info by checking the debug logs from the IntelliCode CLI that trains the models: 
`Using Visual Studio instance: Visual Studio Enterprise 2019 (16.10.31424.327)
Using MSBuild at 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin' to load projects.`)

It seems as if Visual Studio only started including the required libraries to build dotnet 5 sdk [after version 16.10.4](https://dotnet.microsoft.com/download/dotnet/5.0)

I created [this issue](https://github.com/actions/virtual-environments/issues/3798) to track this.
Once Visual Studio is updated to version 16.10.4 the problem should be gone (I tried locally and it trained the model properly).

Thanks again for the feedback!

Oscar.

**Comment by osobeso** [comment]
@kolappannathan Hi, Visual Studio has been updated by the Github team on the windows agent, but I'm still able to repro the issue.
We're currently working on this, as it seems it has to do with us using MSBuild to extract the code patterns from the codebase.
That is causing issues with our process so **for now .NET 5 and beyond is currently not supported by this Github Action**.

We will let you know once we're able to fix this problem, in the meantime I've created [this issue](https://github.com/MicrosoftDocs/intellicode/issues/307) to track this problem.

Thanks again for reaching out and we'll keep you posted on the resolution for this problem.

In the meantime you can train a model for your code using Visual Studio Custom model training, see [the docs here](https://docs.microsoft.com/en-us/visualstudio/intellicode/not-in-toc/autotraining_faq#enabling-autotraining-models-for-custom-code-completions-in-visual-studio)

Oscar.
