### ISSUE TITLE
Support .NET 5 on Team Completions Github Action and ADO Task.

### ISSUE THREAD

**Issue by osobeso** [MicrosoftDocs/intellicode#307]
C# extractor is not able to extract patterns from .NET 5 projects because we're using MSBuild and it can't find the dotnet 5 libraries needed to compile.

**Product and Version** [VS/VSCode]: Github Action / ADO Task.
**OS Version** [macOS/Windows]: Windows agent
**IntelliCode Extension Version**: NA
**Target Platform or Language** [e.g. Node.js]: C#

**Scenario:**

1. Currently .NET 5 is not being compiled properly by the C# Extractor used for Github Action / ADO task, primarily because we're using MSBuild instead of dotnet.

We need to take a look at how we could change this pattern and start using the newer tools for roslyn. Still need to do some investigation about this.

Probably we don't need to switch to dotnet, but we need to find a way to make these needed libraries available for MSBuild when extracting the patterns using the C# extractor.

**Comment by ayim** [comment]
@osobeso what's the latest on this?

**Comment by kolappannathan** [comment]
@DavidObando Do we have any updates on this?

**Comment by osobeso** [comment]
@kolappannathan I'm sorry for not being responsive enough with this topic.  I have not been able to prioritize this, mainly because this feature will be deprecated in the near future.

I will re-assess this problem see if it's worth fixing in the coming months.
In the meantime, I strongly recommend for you to use [Machine-associated models](https://github.com/MicrosoftDocs/intellicode/blob/main/docs/custom-models.md#machine-associated-models) instead. These will create a model that will be maintained locally in your machine and will be automatically kept up to date by Visual Studio.

Will let you know once we arrive to a solution, and sorry again for the inconvenience.

**Comment by kolappannathan** [comment]
@osobeso Noted. Thank you

**Comment by ayim** [comment]
Team completions has been upgraded to a deep learning model that doesn't require training a custom model, full details here:
https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
