### ISSUE TITLE
Could I build use the model for extension of other editor?

### ISSUE THREAD

**Issue by chemzqm** [MicrosoftDocs/intellicode#31]
I want to try the trained model from intellicode service in other editor as an extension, it that allowed?

**Comment by markw-t** [comment]
@chemzqm, no this is not permitted. 

The models created and used by IntelliCode are only licensed for use in Visual Studio Code or Visual Studio. See https://aka.ms/intellicodeLicense for the license terms regarding Custom Model usage.
