### ISSUE TITLE
TypeScript statement completion with symbols does not always work

### ISSUE THREAD

**Issue by leidegre** [MicrosoftDocs/intellicode#311]
This is in reference to this [issue](https://github.com/microsoft/vscode/issues/132683#issuecomment-915792750_) that I originally opened with the VS Code team. All the information you need can be found in that issue.

The problem for me is that a TypeScript type with symbols only doesn't get proper completions. I have to either disable the IntelliCode extension or change the IntelliCode setting `vsintellicode.typescript.completionsEnabled` to `false` to get correct suggestions.

There's also a odd empty suggestion, that if you try to use that inserts an emoji star. I think this is a bug (or several) and it's related to some issue with IntelliCode dealing with object types where symbols (not strings) are being used as keys.

With the extension disabled

![image](https://user-images.githubusercontent.com/63085/132633614-5e00a4b0-157e-474a-846f-aaad56ad1e67.png)

With the extension enabled

![image](https://user-images.githubusercontent.com/63085/132633567-ea7472c9-de51-47c6-a282-24aed1fbfb1b.png)

_There are no more suggestions offered than those shown in the screenshot above._

Repo source code can be found here https://gist.github.com/leidegre/e51afd311eb4d9729c3ea2a5e6411d3b

**Comment by ayim** [comment]
@leti367 is this still an issue?

**Comment by leti367** [comment]
The fix is already in. The issue will be fixed in next release.

**Comment by leti367** [comment]
This issue should be resolved in the latest version: v1.2.19. Thanks!
