### ISSUE TITLE
Intellisense not working properly on Angular templates

### ISSUE THREAD

**Issue by chascruzrm** [MicrosoftDocs/intellicode#313]
Issue Type: <b>Bug</b>

When editing a html component's template file, I type a component ts object's name while between in {{ }} and intellisense does not show right object properties and methods. It just shows snippets and other extensions' stuff.
Using Angular 11.2.14

Extension version: 1.2.14
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.86GB free)|
|Process Argv|C:\\Fuentes\\Proyecto Turnos\\pyturnos_server --crash-reporter-id 66f06bda-8d12-400f-9edb-3eafdd689df7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224cf:30367820
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by markw-t** [comment]
Tagging @jessetrinity as this appears to be a JS IntelliSense problem?

**Comment by jessetrinity** [comment]
@chascruzrm are you able to update angular (just to rule out issues with that version)? I created a new project with `ng-new` which defaulted to Angular 12.2. Also, which version of TypeScript is your project using.

I am not familiar with Angular development in VSCode, so full steps to reproduce this issue in a new project would be helpful.

**Comment by jessetrinity** [comment]
Also, are you using an extension for Angular development?

**Comment by DionatanGG** [comment]
I think you should install the Angular Language Service plugin first, that's what power up your angular templates to bring all the autocomplete stuff.

**Comment by DionatanGG** [comment]
As an example, for me it's working as expected.
Angular 12.1.3, Typescript 4.3.5

![image](https://user-images.githubusercontent.com/44219120/134761561-9a6596a3-29fc-4541-bbf6-1ec290f15915.png)

**Comment by markw-t** [comment]
Closing out as this appears to be a question of which language service plugins you have enabled, and not an IntelliCode issue.
