### ISSUE TITLE
Intellicode is not displaying starred suggestions

### ISSUE THREAD

**Issue by ivanlegranbizarro** [MicrosoftDocs/intellicode#314]
**Product and Version** [VS/VSCode]: 1.60.2
**OS Version** [macOS/Windows]: Mac OS 11.6
**IntelliCode Extension Version**: 1.2.14
**Target Platform or Language** [e.g. Node.js]: Python 

**Steps to Reproduce / Scenario:**

1.You just write code in a .py file. Intellisense works perfectly, but IntelliCode starred hints are never displayed. They only happen with Python. With Javascript / Typescript Intellicode it works perfectly.
2.This is the Output that VS intelliCode returns:
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension

3. The bug is also reproduced with the insider version of vscode.

Obviously it does not happen with the disabled extensions, but it is impossible for me to locate which of them could cause the error, since the Python extension works correctly and provides me with Intellisense, and the Intellicode extension does not seem to fail to acquire the models ...

Thank you. I hope you can help me.

**Comment by ivanlegranbizarro** [comment]
Hello again... Is there any news about it? The problem still persists and is very frustrating.

Thanks in advance, and sorry for the inconvenience.

**Comment by DavidObando** [comment]
Hi @ivanlegranbizarro, we're still looking into this without a repro at hand. Is this happening in an Intel or M1 processor?

**Comment by ivanlegranbizarro** [comment]
First of all, thank you for your interest.

I confirm that these problems occur on a machine with an M1 chip

**Comment by jiayouzl** [comment]
my macbook pro m1pro in bugs！no⭐
inter windows yes
inter macos yes
m1pro macos no⭐
myemail:jiayouzl@vip.qq.com

**Comment by ivanlegranbizarro** [comment]
Hello. Any advance? Thanks :)

**Comment by jiayouzl** [comment]
Hello. Any advance? Thanks :)

**Comment by jiayouzl** [comment]
> 
They ignore us

**Comment by leti367** [comment]
@ivanlegranbizarro @jiayouzl , it's already in our backlog. I will provide some updates next week.

**Comment by ivanlegranbizarro** [comment]
@leti367, thank you so much for your attention! :)

**Comment by leti367** [comment]
At this point, we only support x64 for Mac OS, I will work on adding support for M1 machine. Also as mentioned in #338 We're acquiring M1 hardware to diagnose and test this, we will update with you as soon as we got it.

**Comment by jiayouzl** [comment]
> At this point, we only support x64 for Mac OS, I will work on adding support for M1 machine. Also as mentioned in #338 We're acquiring M1 hardware to diagnose and test this, we will update with you as soon as we got it.

x64 macos no bugs。m1 and m1pro macos in bugs，my old 2020 macbook pro m1 Reshipment system only vscode and python3 environment Have a problem。

**Comment by jiayouzl** [comment]
> At this point, we only support x64 for Mac OS, I will work on adding support for M1 machine. Also as mentioned in #338 We're acquiring M1 hardware to diagnose and test this, we will update with you as soon as we got it.

ok，thank。

**Comment by ivanlegranbizarro** [comment]
Yeah, thanks.

**Comment by leti367** [comment]
The changes are already in. It will be available for next "Pylance" extension release which is supposed to be next Wednesday.

**Comment by ivanlegranbizarro** [comment]
Thanks a lot! I can't wait for see it!

**Comment by jiayouzl** [comment]
> The changes are already in. It will be available for next "Pylance" extension release which is supposed to be next Wednesday.

Finally repaired, thank you!

**Comment by jiayouzl** [comment]
> The changes are already in. It will be available for next "Pylance" extension release which is supposed to be next Wednesday.

When will the update be released?

**Comment by DavidObando** [comment]
We were expecting the Pylance team to release last week, but there were unaccounted-for delays. They usually release on Wednesdays, almost every week. I hope that there will be no additional delays and we can see this fix go out this week.

**Comment by ivanlegranbizarro** [comment]
At last the problem has been solved. With this and Intellicode's new autocomplete... I'm freaking out with VSCODE right now.

Many thanks for your work!

**Comment by DavidObando** [comment]
That's great to hear! We're happy to finally have all the IntelliCode extensions working on M1 computers. Enjoy!

/cc @leti367 who did all the heavy lifting here!
