### ISSUE TITLE
Intellisense doesn't suggest any methods or properties when I use classname like (container) but when I use document , it is showing suggestions.

### ISSUE THREAD

**Issue by OmkarGharat** [MicrosoftDocs/intellicode#316]
**Product and Version** [VS/VSCode]: vscode 
**OS Version** [macOS/Windows]: windows 1.61.1
**IntelliCode Extension Version**: 1.2.14
**Target Platform or Language** [e.g. Node.js]: Javascript

**Steps to Reproduce / Scenario:**

1. vscode Intellisense doesn't suggest any methods or properties when I use classname like (container) but when I use document or document.body , it is showing suggestions. I don't know why this is happening ??
![Screenshot (168)](https://user-images.githubusercontent.com/83211956/137852485-6e3f501c-8a22-49ca-9a32-08412dc212c3.png)
![Screenshot (170)](https://user-images.githubusercontent.com/83211956/137852543-e237a47d-19f0-499f-8c78-e036f8be6c39.png)

**Comment by DavidObando** [comment]
@OmkarGharat let us know if you have any additional questions. Thanks!
