### ISSUE TITLE
When querying IntelliCode service: Error: certificate has expired

### ISSUE THREAD

**Issue by bbishop-neovest** [MicrosoftDocs/intellicode#317]
When I install the IntelliCode extension into Azure Data Studio, I get the following error stream in the Output view:

```
Acquiring model 'intellisense-members' for sql
Querying IntelliCode service for available models.
Couldn't reach service Error Message: certificate has expired, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: certificate has expired, (Error)
No model available for SQL, cannot continue.
```

**Product and Version** Azure Data Studio Version 1.33.0; VS Code: 1.58.0:
**OS Version** Windows 10:
**IntelliCode Extension Version**: 1.2.1 
**Target Platform or Language** MSSQL:

**Steps to Reproduce / Scenario:**

1. Install the extension
2. Open or construct a T-SQL query -- error quickly occurs in Output view

**Comment by markw-t** [comment]
It looks like you are having some networking issues here - can you confirm you're sitting behind some sort of proxy server? /cc @DavidObando @vivlimmsft

**Comment by ayim** [comment]
@bbishop-neovest are you still experiencing this issue?

**Comment by bbishop-neovest** [comment]
This is not an issue anymore. I will close the ticket.
