### ISSUE TITLE
Most of the cases, I get the error "Couldn't download IntelliCode model"

### ISSUE THREAD

**Issue by tarekahf** [MicrosoftDocs/intellicode#319]
**Product and Version** [VS/VSCode]:
Visual Studio IntelliCode
Id: visualstudioexptteam.vscodeintellicode
Description: AI-assisted development
**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**: 1.2.14
**Target Platform or Language** [e.g. Node.js]: SQL and Java
**VS Code Version**:
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Steps to Reproduce / Scenario:**

1. Open vs code
2. Open SQL File or Java code file

**Error displayed on the notification panel:**
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

**Extension Output:**
Acquiring model 'intellisense-members' for sql
Querying IntelliCode service for available models.
Couldn't reach service Error Message: Socket is closed, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: Socket is closed, (Error)
No model available for SQL, cannot continue.

The problem occurs most of the time. Sometimes it doesn't happen, and I don't know why, maybe it is just that I don't notice it. Mind you that our environment has security in place, and I must use VPN to access internal resources. I tried to set a proxy as recommended by our support team. I searched how to set up a proxy and tried different ways, but nothing worked.

Please help.
Tarek

**Comment by tarekahf** [comment]
There is an issue for sure. I found a work-around here:

https://github.com/MicrosoftDocs/intellicode/issues/49#issuecomment-961281661

**Comment by DavidObando** [comment]
> The solution was to stop the company VPN, remove Proxy settings made for vs code, and restart vs code. Now, the IntelliCode module is downloaded. You can check the results in Output view/Extensions.

Thank you for posting the issue, we've been trying to cover proxy and VPN scenarios for a while and we know we have gaps. We will continue to work on improvements to this experience, but for now I'll be closing this issue as you seem to be unblocked.
