### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 235337218** [MicrosoftDocs/intellicode#321]
Issue Type: <b>Feature Request</b>

: 1.62.3 (user setup)
: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

It seems that this visual studio intellicode plug-in cannot complete the syntax it intelligently prompts.
For example, in a C language file:
When entering "print", it can prompt the "print" statement, but when I select this statement, it seems that it can't automatically fill in parentheses and semicolons

Extension version: 1.2.14
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by markw-t** [comment]
Thanks for raising this @235337218 ; IntelliCode is the AI-assisted "starred completions" in IntelliSense - you can see more at https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code .  IntelliCode doesn't support C files in VSCode so I'm closing out this issue..

It seems like the problem you are mentioning is a core IntelliSENSE (autocompletion) problem for C in VS Code - you may want to raise it with the folks who support C/C++ on VSCode.

Thanks
Mark
