### ISSUE TITLE
Enable IntelliCode to run on VS Code on the web

### ISSUE THREAD

**Issue by isidorn** [MicrosoftDocs/intellicode#322]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure that Intellicode can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

Feel free to reach out to me if you have questions or if I can help somehow.
Thank you

**Comment by ayim** [comment]
Update here: we're working on an implementation for JS/TS.
CC: @lei-msft

**Comment by codecycleteam** [comment]
@markw-t @gewarren @catycaldwell @ghogen @2percentsilk @DavidObando 
Any update for the solution to this issue?
Make the VSCode extension compatible with https://vscode.dev and https://github.dev
Please consider this as DX improvement and give some priority for it.
Thanks

![Screenshot 2022-04-25 08 46 44](https://user-images.githubusercontent.com/84431724/165015141-ca230250-0c4a-44c8-966b-703fbcfdb9c2.png)

**Comment by leti367** [comment]
@codecycleteam , the support for IntelliCode JS/TS implementation is completed. We are waiting for changes from TS team to get it ready to release.

**Comment by codecycleteam** [comment]
@leti367 Thanks a lot for your clarity. I appreciate it.

**Comment by ayim** [comment]
Since version 1.2.16 of the IntelliCode extension, JS/TS has been supported on the web.
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

**Comment by lavilao** [comment]
Hi, was the support removed? I currently cant install intellicode on vscode.dev 🙁
