### ISSUE TITLE
Not getting code suggestions

### ISSUE THREAD

**Issue by TrajcheKrstev** [MicrosoftDocs/intellicode#327]
Whenever i open a java file, it stops giving me Intellisense code suggestions once it automatically imports project. It works fine for a few secs before the project gets imported and then i lose all suggestions and i only get "Language support for java by red hat" suggestions. Even something like sysout doesn't show up. This is probably a stupid question but i haven't been able to figure out what i have to change to make it work.

Here is what it looks like:
when i open the file:
![Before](https://user-images.githubusercontent.com/79156111/150651143-4fe5e5c0-4a17-4221-82f0-4883c75b76b6.jpeg)
after 1 sec i lose the suggestions:
<img width="477" alt="After" src="https://user-images.githubusercontent.com/79156111/150651140-21d205c8-c91d-4bc3-8cda-3809bbd2530e.png">

**Comment by ayim** [comment]
Tagging @Eskibear, would you mind taking a look at this issue?
Appreciate you looking into this, it seems like a Java language problem on first look

**Comment by ayim** [comment]
Note: China team is on Chinese New Year holiday this week.

**Comment by Eskibear** [comment]
@TrajcheKrstev 
It’s strange because in the first screenshot, suggestions should also include types starting with letter S.

A few detailed questions below:
- what’s the version of intellicode extension and Java language support by redhat?
- Does this issue occur when intellicode is disabled?

**Comment by ayim** [comment]
@[TrajcheKrstev](https://github.com/TrajcheKrstev) bump!

**Comment by ayim** [comment]
@[TrajcheKrstev](https://github.com/TrajcheKrstev) feel free to reopen this issue, going to close for now since we don't have a reproducible issue.
