### ISSUE TITLE
[BUG][javascript] "types" compiler option in jsconfig.json doesn't work

### ISSUE THREAD

**Issue by tjx666** [MicrosoftDocs/intellicode#328]
When I enable this extension, you can see that I can still get the suggest from @types/node.

![image](https://user-images.githubusercontent.com/41773861/151309609-806682b5-04be-4fa1-b296-8df2785243fc.png)

But no issue in typescript project or disable this extension in js project:

![image](https://user-images.githubusercontent.com/41773861/151309878-3eee2de4-654a-49b0-bb92-af98d1a38ab7.png)

VSCode version: 1.64.0-insider
intellicode version: v1.2.16
OS: MacOS 12.1

**Comment by ayim** [comment]
Happy Friday @minestarks, the question here seems to be relating to JS/TS IntelliSense support rather than IntelliCode. Mind taking a look here for us?

**Comment by minestarks** [comment]
@tjx666 This may be by design, but I'm not sure. could you file this in https://github.com/microsoft/vscode ?

**Comment by ayim** [comment]
Moved to https://github.com/microsoft/vscode/issues/141975

**Comment by tjx666** [comment]
@ayim thanks, I have no free time because the Spring Festival...
