### ISSUE TITLE
Option to disable "Interested in API usage examples?" toast

### ISSUE THREAD

**Issue by nzig** [MicrosoftDocs/intellicode#329]
A while ago I got this message:
![image](https://user-images.githubusercontent.com/7372858/151945747-775db55c-9c98-4d06-81c4-e6d09d9d0d33.png)
I installed the extension but didn't like it so I uninstalled it. Now every time I open VSCode I get the same message. Is there a way to disable this? I do not want to install the extension. 

Clicking "No, Thanks!" makes it go away, but when I open VSCode again it pops up again.

**Comment by ayim** [comment]
@osobeso are you the right person to look into this?

**Comment by osobeso** [comment]
@nzig Hi, I'm sorry you're experiencing this.
This is definitely a bug.

Short answer is there is a way to disable it. If you go to File > Preferences > Settings and type Visual Studio IntelliCode in the search box, you'll notice there's a setting with the title of "Features: Api Examples".
If you mark that as disabled, you will get rid of this notification.

The not so short answer is this is definitely not the experience we worked for, and you most probably stumbled upon a scenario we couldn't foresee. I'd like to know more about your experience and your current environment.

If you could help me providing me with a little bit more information about your current setup it would be really helpful for me to try and replicate this on my side.
Things such as:
* Your current Operating System
* The version of the IntelliCode Extension you currently have installed. You can get it by pressing Ctrl+Shift+X on VSCode and then searching for "Visual Studio IntelliCode". The version tag will be next to the extension title once you expand the view.
* A list of the extensions currently installed on your vscode setup.
* If you're working with virtual environments or any kind of non-desktop/non-local experience that would also be really helpful to know.

In the meantime, I'll try to replicate the steps you mentioned on your post, to see if I can figure out what might have gone wrong.

Again, I'm sorry for the bad experience, and thanks for letting us know.

**Comment by nzig** [comment]
Thanks, I've disabled that setting as you suggested and it did stop the notification.

This is the output of the "report issue" feature in VScode:

Extension version: 1.2.16
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.16.4-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|15.44GB (2.52GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 4eca593c-aba3-413d-89f9-312acde53d4b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|sway|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vs360cf:30404996
vsrem710cf:30416617
vscop841:30430977

```

</details>

<details>
<summary>
Output of `code --list-extensions`

</summary>

```
asvetliakov.vscode-neovim
atlassian.atlascode
bradymholt.pgformatter
coolbear.systemd-unit-file
deerawan.vscode-dash
eamodio.gitlens
GitHub.copilot
GitHub.remotehub
GitHub.vscode-pull-request-github
guyskk.language-cython
ivory-lab.jenkinsfile-support
joaompinto.vscode-graphviz
lunaryorn.fish-ide
mads-hartmann.bash-ide-vscode
mgesbert.python-path
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.cpptools
ms-vscode.hexeditor
ms-vscode.test-adapter-converter
ms-vsliveshare.vsliveshare
nickgo.cuelang
pascalsenn.keyboard-quickfix
PowerQuery.vscode-powerquery
redhat.vscode-xml
redhat.vscode-yaml
rsbondi.highlight-words
rust-lang.rust
samuelcolvin.jinjahtml
shakram02.bash-beautify
skyapps.fish-vscode
streetsidesoftware.code-spell-checker
swimm.swimm
tamasfe.even-better-toml
timonwong.shellcheck
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
vscodevim.vim
yinfei.luahelper
zxh404.vscode-proto3
```

</details>
I am not working in a virtual environment, just a plain app on my desktop.

**Comment by osobeso** [comment]
As an update, we were able to identify the issue, and have rolled out a new version (1.2.17) with a fix for this issue.

**Comment by ayim** [comment]
@nzig, out of curiosity, what didn't you like about the extension?
It's currently experimental and we're open to suggestions!

**Comment by nzig** [comment]
@ayim The API suggestions took up too much space in the tooltip. I would rather see the normal tooltip with the parameters and docstring first. Even if the examples came last, I don't want the tooltip so large that it hides a lot of code. Maybe if it was hidden by default with some option to expand it when needed, I would consider using the extension.

**Comment by ayim** [comment]
Gotcha, appreciate the feedback!
