### ISSUE TITLE
Getting error during initial load of vscode for JS files

### ISSUE THREAD

**Issue by sivaecekrr** [MicrosoftDocs/intellicode#33]
Getting below error notification when opening the vscode after installing Intellicode. 
This issue happens when js files is opened by default. 

**Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.**

Visual Studio IntelliCode Version: 1.1.0

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Windows 10

**Comment by sivaecekrr** [comment]
@markw-t Thank you!. After performing the steps mentioned in #4 works for me.

**Comment by markw-t** [comment]
Great; out of interest which specific set of steps worked for you? (there are a few in #4 )

**Comment by sivaecekrr** [comment]
I had tried by switching the proxy and it worked. It does not work in office network. I had tried in home  network which doesn't have any firewall settings.
