### ISSUE TITLE
doesn't show python code suggestion 

### ISSUE THREAD

**Issue by leiyang** [MicrosoftDocs/intellicode#332]
it doesn't give me any code suggestion from intellicode and  the output is 

Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension -------------------> seems stop here ?

**Comment by markw-t** [comment]
Thanks for letting us know that it's fixed for you @leiyang - I'll close this item but if the problem recurs please do let us know. It would be good to see the output of the Output-Python tab as well as the IntelliCode one, since this may have important data about the source of the failure too.
