### ISSUE TITLE
VS intelliCode issue 

### ISSUE THREAD

**Issue by Imsharique** [MicrosoftDocs/intellicode#337]
**Product and Version** [VS Code/1.64.2]:
**OS Version** [Windows 10, Version- 21H2, OS build-19044.15526]:
**IntelliCode Extension Version**: VisualStudioExptTeam.vscodeintellicode
**Target Platform or Language** [Java]:

**Steps to Reproduce / Scenario:**

1. I am facing the below issue. Kindly, help [ASAP!]
![image](https://user-images.githubusercontent.com/99683703/154859873-10fa25cc-7dad-4f77-a092-be30c3071b33.png)

**Comment by Eskibear** [comment]
As mentioned in the notification, can you check these output windows and attach detailed logs?

**Comment by Imsharique** [comment]
Hi @Eskibear, thanks for the reply.

**Comment by ayim** [comment]
@imsharique appreciate you reaching out! Always love to hear about bugs and potential improvements :)
