### ISSUE TITLE
Intellicode is not displaying starred suggestions help me！

### ISSUE THREAD

**Issue by jiayouzl** [MicrosoftDocs/intellicode#338]
my macbook pro m1pro in bugs！python3.9.10 no⭐
inter windows yes
inter macos yes
m1 macos no⭐
m1pro macos no⭐
myemail:jiayouzl@vip.qq.com
Thank you very much！

**Comment by jiayouzl** [comment]
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension

**Comment by jiayouzl** [comment]
版本: 1.64.2 (Universal)
提交: f80445acd5a3dadef24aa209168452a3d97cc326
日期: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

**Comment by jiayouzl** [comment]
Thank you very much！

**Comment by jiayouzl** [comment]
my macos version 12.2.1

**Comment by jiayouzl** [comment]
Is anybody there?

**Comment by ayim** [comment]
Hi @jiayouzl, sorry for the late update here & thanks for your patience.
We have the ability to diagnose on M1 Mac now & are working on it.

**Comment by jiayouzl** [comment]
> Hi @jiayouzl, sorry for the late update here & thanks for your patience. We're acquiring M1 hardware to diagnose this, hope to have an update for you soon!

Thank you
