### ISSUE TITLE
extension is  doesn't work

### ISSUE THREAD

**Issue by KCN6512** [MicrosoftDocs/intellicode#341]
Issue Type: <b>Bug</b>

At start of Vs code notification text me that extension is not working

Extension version: 1.2.17
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.24GB free)|
|Process Argv|--crash-reporter-id fbc991ee-4f72-476f-b04e-c682c882e36b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvid2:30447481
pynewfile477cf:30450039

```

</details>

**Comment by KCN6512** [comment]
Visual Studio IntelliCode *

**Comment by KCN6512** [comment]
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Error while activating Python: {}

**Comment by markw-t** [comment]
Thanks for sharing the IntelliCode window contents. - Could you share the Python window ones too as this may help pin down the problem that is happening activating Python?

**Comment by KCN6512** [comment]
Thanks you for help!

**Comment by markw-t** [comment]
You're welcome; out of interest what fixed this for you?
