### ISSUE TITLE
Since a certain version of update, IntelliSense works too slow and strange

### ISSUE THREAD

**Issue by starjasmine** [MicrosoftDocs/intellicode#342]
Issue Type: <b>Bug</b>

Hi all. Hope you are doing great!
I appreciate all those great works you do for public!

It's hard to say when was the first time it has started to happen.
While I'm editing my Java (Spring boot) code, IntelliSense does not work at all
or it works too slow.
And as the screenshot below explains, it seems like the feature conflicts with other extensions like GitLens.  (The assistant shadow message by GitLens appears by cracking my normal code line)

![image](https://user-images.githubusercontent.com/5242304/159201047-43ffd359-deb8-4c0c-bb40-023de30a30e2.png)

Hope you are willing to regard this as a considerable issue.

Extension version: 1.2.17
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-210-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz (24 x 3067)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|95.99GB (85.00GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bhome-gpu/home/woniok/projects/corpmesh --crash-reporter-id 0e38481a-6ff8-40ba-9e1b-cf5748ade8ed|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: home-gpu|
|OS|Linux x64 4.4.0-210-generic|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3622)|
|Memory (System)|15.64GB (0.89GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
vscgsvid2:30447481
cppdebug:30451566
pynewfile477cf:30450039

```

</details>

**Comment by markw-t** [comment]
Thanks for raising this - it appears to be an issue with the core Java support rather than IntelliCode as such, so I'm tagging @Eskibear  to see this issue.

**Comment by Eskibear** [comment]
@starjasmine This can be any of below:
- performance of core Java support 
- performance of Spring Tools extension (if installed)
- performance of IntelliCode (less likely)
- performance of gitlens (less likely)
- above extensions compete for CPU
- networking issue as you are running vscode in remote

A simple way to identify the culprit is, you disable above extensions and enable them one by one, see which one affects the performance most.

**Comment by starjasmine** [comment]
@Eskibear Thanks for your comment.
