### ISSUE TITLE
not activated

### ISSUE THREAD

**Issue by jmw6121** [MicrosoftDocs/intellicode#345]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by markw-t** [comment]
Thanks for your report. We need some further information to understand the problem you are seeing and respond.

Please can you provide the following information:

1. Is the problem in VS or VS Code?
2. What operating system are you using? (MacOS/Windows/??)
3. What is the version of the IntelliCode extension you have installed?
4. What language are you using when you see the problem? (JavaScript, TypeScript, Python, ...)

If you are using the Visual Studio Code version of IntelliCode it would be very helpful to see the contents of the Output Panes for IntelliCode and the language you are using. You can get them in VSCode by clicking 'View' -> 'Output'. Then choose 'VS Intellicode' and 'Python' (or whatever language you are using) for logs when you see the issue.  Just paste the results from each one of them into this issue.

It would also be helpful if you can provide a little more detail of the exact steps you took to see this issue (e.g. Opened VS Code, opened a <language> file, saw this message appear....)

Thanks! 
Mark

**Comment by ayim** [comment]
@jmw6121 would love to hear back on you.

Are you still seeing problems?
If so, need your help answering markw-t's questions

**Comment by ayim** [comment]
@jmw6121 feel free to open a new issue if you're still seeing problems - we'll need a bit more detail to help us help you!
