### ISSUE TITLE
Intellisense for java not working

### ISSUE THREAD

**Issue by shaithal** [MicrosoftDocs/intellicode#352]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Intellisense for java not working

Extension version: 1.2.18
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 36254bfb-d628-418a-a0dd-79aab0777794|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaac:30438847

```

</details>

**Comment by ayim** [comment]
Hi @shaithal, sorry to hear that IntelliSense isn't working for you in Java.
Could you clarify whether you mean:

1) There is an issue with the IntelliSense dropdown for methods/classes and their documentation
2) There should be stars attached to methods that you aren't seeing
![image](https://user-images.githubusercontent.com/10951869/163855443-8bd47724-feda-4b97-b6fd-9e9ec834fffd.png)

**Comment by ayim** [comment]
@[shaithal](https://github.com/shaithal) would love to hear from you still! Feel free to reopen this issue if you're still experiencing issues
