### ISSUE TITLE
Make All VSCode extensions of Intellicode compatible with https://vscode.dev/ and https://github.dev/

### ISSUE THREAD

**Issue by beingminimal** [MicrosoftDocs/intellicode#356]
Feature Request
---------------
@markw-t @gewarren @catycaldwell @ghogen @2percentsilk @DavidObando
Make All VSCode extensions of Intellicode compatible with https://vscode.dev/ and https://github.dev/
Please consider this as DX improvement and give some priority for it.

Here is more info
https://aka.ms/vscode-web-extensions-guide
https://code.visualstudio.com/api/extension-guides/web-extensions

Thanks

For feature requests, please include enough of this same info so we know if the request is tool or language/platform specific.
-->

![Screenshot 2022-04-25 08 54 13](https://user-images.githubusercontent.com/84431724/165015750-ab0f62b1-4837-42bf-913e-6dbe8b43ab43.png)
![Screenshot 2022-04-25 08 53 39](https://user-images.githubusercontent.com/84431724/165015752-61f176f0-19ba-4a9d-8e2b-71e68a4c9f54.png)
![Screenshot 2022-04-25 08 53 15](https://user-images.githubusercontent.com/84431724/165015753-6bc5f2ad-f5e0-4058-a975-01c1e190e4f6.png)
![Screenshot 2022-04-25 08 52 51](https://user-images.githubusercontent.com/84431724/165015754-3b694fb1-59ff-48b6-9bc1-8f7bce1d5e8e.png)
![Screenshot 2022-04-25 08 46 44](https://user-images.githubusercontent.com/84431724/165015756-56d8c53a-b96d-4000-befc-fc8ae17bf2bf.png)

**Comment by DavidObando** [comment]
Hi,

We're considering making some of the above extensions available for VSCode.dev and GitHub.dev, watch this space for upcoming updates.

Thanks!

**Comment by codecycleteam** [comment]
@DavidObando Thanks a lot for considering this request.

**Comment by ayim** [comment]
Since version 1.2.16, this extension supports JS/TS for vscode.dev and github.dev
