### ISSUE TITLE
Couldn't download IntelliCode model

### ISSUE THREAD

**Issue by Pixfri** [MicrosoftDocs/intellicode#367]
When I launch a JavaScript file on VS Code I have an error message: Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

**Comment by Omoeba** [comment]
It appears that the server `prod.intellicode.vsengsaas.visualstudio.com` is currently down.

**Comment by xdhmoore** [comment]
I also get the above message when trying to use the java extension pack and Remote Containers. The VS IntelliCode Output is:
```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: connect ECONNREFUSED 40.125.125.220:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ECONNREFUSED 40.125.125.220:443, (Error)
No model available for Java, cannot continue.
```

**Comment by trolleyboy** [comment]
Also getting no response from `prod.intellicode.vsengsaas.visualstudio.com`. I've tried from several different networks so this doesn't seem to be a Proxy issue like most other posts point to. 
Have tried connecting to the Traffic Manager IP's in different regions via static hosts file entry, still no go, so seems to be a global issue.

**Comment by naks110** [comment]
@vivlimmsft Looks like global issue, please help us out
Check: 20.81.69.210:443  , prod.intellicode.vsengsaas.visualstudio.com

Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Couldn't reach service Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
No model available for Java, cannot continue.

**Comment by dottools** [comment]
I am having this issue as well. Does Intellicode download the model every single time VSCode is started up and not cache the model files? If so then that's a huge design flaw.

**Comment by cgarrovillo** [comment]
> I am having this issue as well. Does Intellicode download the model every single time VSCode is started up and not cache the model files? If so then that's a huge design flaw.



> @vivlimmsft Looks like global issue, please help us out Check: 20.81.69.210:443 , prod.intellicode.vsengsaas.visualstudio.com ...
> 
> ...
> 
> ...
>
> **Checking the local model cache. None of the cached models match.** 
>
> ...

**Comment by ADataGMan** [comment]
I'm also getting this in my remote development container when previously it was working fine. 

This seems like a great reminder to support offline usage: https://github.com/MicrosoftDocs/intellicode/issues/102

**Comment by trolleyboy** [comment]
Started getting a 503 response in VSCode output now...
```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Service responded with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. 
No model available for Java, cannot continue.
```

A simple curl to what I believe is the API returns 503 now too...
```
curl https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/java/intellisense-members/output/latest
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**And now,** just as I was double-checking my curl command and the output, I got a 200 response with valid data. Restarted VSCode and the Intellicode output now looks good...
```
Acquiring model 'intellisense-members' for java
Querying IntelliCode service for available models.
Downloading model.
Starting download of https://intellicodeprodstorage.blob.core.windows.net/models-prod-output/Output_45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3?<access token removed>
Download complete.
vs-intellicode-java was passed a model: {"modelId":"45788CA1782FEF17F07049DB4764F5647A62","modelPath":"c:\\Users\\user1\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.21\\cache\\45788CA1782FEF17F07049DB4764F5647A62_975CC5EC71E347A9B047E779B175B7D3","outputId":"975CC5EC71E347A9B047E779B175B7D3"}.
Java Extension is activated.
JavaAPI: {"apiVersion":"0.6","javaRequirement":{"tooling_jre":"c:\\Users\\user1\\.vscode\\extensions\\redhat.java-1.6.0-win32-x64\\jre\\17.0.2-win32-x86_64","tooling_jre_version":17,"java_home":"C:\\Program Files\\Microsoft\\jdk-17.0.3.7-hotspot","java_version":17},"status":"Started","serverMode":"Hybrid"}
Enabled IntelliCode for Java.
```

Backend issue resolved perhaps?

**Comment by Omoeba** [comment]
Python appears to have recovered as well.

**Comment by naks110** [comment]
java model downloaded now...

**Comment by dyegros** [comment]
Got same error while trying get javascript model

> Acquiring model 'intellisense-members' for javascript
> Querying IntelliCode service for available models.
> Couldn't reach service Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)
> Could not reach the IntelliCode service. Checking the local model cache.
> None of the cached models match.
> Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ETIMEDOUT 20.81.69.210:443, (Error)

No URL is showing (only IP address). It seems https://prod.intellicode.vsengsaas.visualstudio.com is down (not responding in fact, because no error is returned, only TIMEOUT).

No proxy used in my configuration. Try to open it on browser results in TIMEOUT too.
