### ISSUE TITLE
Weird brace completion behaviour for VSC WLC

### ISSUE THREAD

**Issue by ayim** [MicrosoftDocs/intellicode#372]
Creating a friction log to track behaviour/cases

**Comment by ayim** [comment]
![image](https://user-images.githubusercontent.com/10951869/171740008-a503d310-0ee4-482d-83dc-5d73b5062005.png)
If I dismiss the prediction and type again, it will suggest an additional closing brace

**Comment by ayim** [comment]
![image](https://user-images.githubusercontent.com/10951869/171742369-fe2616f7-00a9-4e5a-b30e-6d492a1aedd9.png)
we suggested a brace after the brace?

**Comment by juihanamshet1** [comment]
@ayim Thanks for catching this! I need the following information from you to repro this and any future bugs:
1. VS Code version
2. Code files
3. File type (for example, this looks like an .ipynb file)

**Comment by ayim** [comment]
@juihanamshet1 we were discussing how to best track this stuff at Bug Bash.. came to the conclusion of using GitHub to do my friction logging + easily uploading GIFs for these 'issues' to group rough areas of feedback together.

Once a developer on our team feels like something is bug worthy or wants to scope it down, we'll open an ADO item to track the work for that.

Does that sound good to you?

**Comment by juihanamshet1** [comment]
@ayim That sounds perfect, thanks for the context! I think this is worth filing an ADO item for especially since we have native brace completion support from vscode now.

**Comment by ayim** [comment]
@juihanamshet1 do we already have a fix in/an ADO issue tracking this?

**Comment by juihanamshet1** [comment]
The fix is in! :)
