### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sprinteroz** [MicrosoftDocs/intellicode#374]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1851,
		"activateCallTime": 10,
		"activateResolvedTime": 1575,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.intellicode-api-usage-examples",
				"_lower": "visualstudioexptteam.intellicode-api-usage-examples"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by osobeso** [comment]
hi @sprinteroz can I get more details about the issue you are having or trying to report with this issue?
Thanks!

**Comment by markw-t** [comment]
We are unable to act further without more description on the problem you encountered - if you can provide some more details on the issue you saw, for instance the contents of your Output window in VSCode's IntelliCode section, and some details of what you were doing when you saw the problem, please feel free to reactivate.
