### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aiyeola** [MicrosoftDocs/intellicode#375]
- Issue Type: `Performance`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/imohd/AppData/Local/Temp/VisualStudioExptTeam.intellicode-api-usage-examples-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ayim** [comment]
@osobeso do we need more information here?
Doesn't look like user's attached the cpu profile file

**Comment by osobeso** [comment]
@aiyeola Hi what language were you working with? Was it python or javascript? Just so we have a sense of which language triggered this high cpu usage.
Thanks!

**Comment by aiyeola** [comment]
Hi @osobeso. It's JavaScript

**Comment by markw-t** [comment]
Hey @aiyeola 

We need the CPU date described in the bug to pursue this further:

⚠️ Make sure to attach this file from your home-directory:
⚠️file:///c%3A/Users/imohd/AppData/Local/Temp/VisualStudioExptTeam.intellicode-api-usage-examples-unresponsive.cpuprofile.txt

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

Please reopen if you can provide this info.

Thanks!
