### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by arsh985** [MicrosoftDocs/intellicode#376]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by markw-t** [comment]
@arsh985 we are unable to act further without more description on the problem you encountered - if you can provide some more details on the issue you saw, for instance the contents of your Output window in VSCode's IntelliCode section, and some details of what you were doing when you saw the problem, please feel free to reactivate.
