### ISSUE TITLE
Extension Issue, is not providing suggestions for autocomplete

### ISSUE THREAD

**Issue by manasvip01** [MicrosoftDocs/intellicode#377]
1.VS Code Version: 1.68
2.OS Version (Windows): 64-bit operating system, x64-based processor
3. IntelliCode Extension Version: v1.2.21
4. Python: v2022.8.0

It should this once:
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

My Visual Code IntelliCode is not working it is not auto-completing my commands, I have tried to downgrade the python version as well as disabled python deep learning as found solutions on the internet, Could you please tell me what should I do?

 
![image](https://user-images.githubusercontent.com/79736693/173665823-7c60f427-b2dc-464c-841b-762c52ea30eb.png)
![image](https://user-images.githubusercontent.com/79736693/173665918-e5416393-4afc-4877-afb3-e9973167859b.png)
![image](https://user-images.githubusercontent.com/79736693/173666011-53b98881-02fe-4b57-a86b-0a8e3c5963f2.png)

**Comment by markw-t** [comment]
@manasvip01 sorry you're seeing this issue. It will be very helpful to see the contents of your "Python" and "VS IntelliCode" output windows when the problem shows up, as they will have more detailed information on how things have failed. You can find these windows in VSCode by using the View menu to select Output. Once selected, the Output window will appear at the bottom part of your VS Code screen. Look for the dropdown list in the top right corner of the pane and select Python, then copy the text you see into this issue. Then do the same for the VS IntelliCode item in the Output window.

**Comment by ayim** [comment]
Hi @manasvip01  feel free to file a new issue with more information if you continue to experience issues related to the IntelliCode extension, thanks!
