### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by royal45mts** [MicrosoftDocs/intellicode#379]
- Issue Type: `Performance`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/aldii/AppData/Local/Temp/VisualStudioExptTeam.intellicode-api-usage-examples-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ayim** [comment]
@royal45mts could you attach the file at the directory above?

**Comment by ayim** [comment]
@royal45mts feel free to reopen this issue by attaching the logs at the filepath noted above if you're still experiencing issues
