### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Bertowujek** [MicrosoftDocs/intellicode#380]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ayim** [comment]
Hi there, could you paste the information in your clipboard here?
We'll need the info to proceed.

Cheers!

**Comment by ayim** [comment]
If you are still experiencing issues, feel free to open a new issue with the attached data in your clipboard
