### ISSUE TITLE
[question] building the VS Code IntelliCode extension from source

### ISSUE THREAD

**Issue by turturel** [MicrosoftDocs/intellicode#381]
Is there any way I can build the VS Code IntelliCode extension from source?

Thanks!

**Comment by turturel** [comment]
for more context - the VS Code marketplace page for the IntelliCode extension points to this repository, however it doesn't seem to contain all the stuff needed to build the extension...

**Comment by markw-t** [comment]
Hi @turturel 

The IntelliCode extension for VS Code is not open source at this time, so you cannot build from source.- sorry for any confusion caused by the repo link from the marketplace page. We use the repository solely for github's issue logging for the extension.
