### ISSUE TITLE
run code not showing

### ISSUE THREAD

**Issue by A-m-r-u-t-a** [MicrosoftDocs/intellicode#386]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by A-m-r-u-t-a** [comment]
in my vs code there are not showing run code, what to do?

**Comment by ayim** [comment]
Hi @A-m-r-u-t-a could you clarify...
1) What you expect to see
2) What is happening

**Comment by ayim** [comment]
Hi @A-m-r-u-t-a feel free to file a new issue with more information if you continue to experience issues related to the IntelliCode extension, thanks!
