### ISSUE TITLE
Does Intellicode send my code to the Microsoft servers?

### ISSUE THREAD

**Issue by AndreaPi** [MicrosoftDocs/intellicode#389]
After I installed the extension, does it send any data to the Microsoft servers? In particular, does it send my source code back to the Microsoft servers? I know that GitHub Copilot can, and that's why I don't use it. What about Intellicode?

**Comment by ayim** [comment]
To add some nuance here, there are two features that users must explicitly opt-in to that will mine the code locally...

- **What:** IntelliCode custom models for C++ and C# in Visual Studio
- **How it works:** Methods and their usages are mined locally then sent to the server to generate a more precise model. Again, this is NOT source code that is being sent.
- **Where:** The resulting model is still run locally
- **When:** There is an explicit opt-in and additional terms/policy the user must accept before any analysis is done
**Full Details:** https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#data-and-privacy

- **What:**[ IntelliCode API Usage Examples](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.intellicode-api-usage-examples)
- **How it works:** A list of methods is mined from the code locally. These methods are sent to the server to identify where there are API usage examples we can provide.

**Comment by AndreaPi** [comment]
thanks @ayim , that clarifies my doubts.
