### ISSUE TITLE
Intellicode fails to build training model for c++ because of missing executable on path.

### ISSUE THREAD

**Issue by momo3334** [MicrosoftDocs/intellicode#390]
To report a problem with IntelliCode for Visual Studio Code, you're in the right place. Please copy and paste any details that are visible in the Output window logs for VS-IntelliCode and the language you're using.

**Product and Version** [VS/VSCode]: Community 17.2.5
**OS Version** [macOS/Windows]: Windows 10.0.25151 Build 25151
**IntelliCode Extension Version**:  2.2.2137.31885
**Target Platform or Language** [e.g. Node.js]:  C++

**Steps to Reproduce / Scenario:**

1. Fresh Install Microsoft Visual Community 17.2.5
2. Open up an Unreal Engine 5.0 C++ Project 
3. Open up the Intellicode windows via the menus inside Visual Studio
4. Try to generate a custom model for the current project by clicking the button

The custom model generation fails with the following output inside the Intellicode output window:

```
[TrainCommand I] Beginning extraction for cplusplus/intellisense-members.
[VSIX I] CLI Information: 0 : IntelliCode CLI Version 1.1.494.58956
[VSIX I] CLI Warning: 0 : Extractor for language 'CPlusPlus' cannot continue because it's missing requirements on the Path: cl.exe,cmake.exe,isense_model_extractor.exe
[VSIX E] IntelliCode CLI exited with error code '1'.
[VSIX E] IntelliCode CLI 'Extraction' could not be performed.
[TrainCommand I] Finished extraction for cplusplus/intellisense-members. Succeeded: False
[AutomaticModelTrainingController W] Error while training: Failed training record: cf9b58b3-3118-4df4-925a-bcc5007301c3 with contents {"Kind":0,"ExtractedWorkspace":null,"TrainingWorkspaceModel":null,"Exception":null,"ExceptionStackTrace":null,"MessageFromService":null,"Attempts":null,"Skipped":false,"Language":"cplusplus","AnalyzerName":"intellisense-members","RecordId":"cf9b58b3-3118-4df4-925a-bcc5007301c3","Created":"2022-07-10T01:56:43.9485922-04:00"}. Microsoft.VisualStudio.IntelliCode.AutomaticModelTraining.TrainingFailureException: Une exception de type 'Microsoft.VisualStudio.IntelliCode.AutomaticModelTraining.TrainingFailureException' a été levée.
   à Microsoft.VisualStudio.IntelliCode.AutomaticModelTraining.AutomaticModelTrainingController.<CreateExtractionInternalAsync>d__62.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.VisualStudio.IntelliCode.AutomaticModelTraining.AutomaticModelTrainingController.<>c__DisplayClass61_0.<<CreateExtractionAsync>b__1>d.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.VisualStudio.IntelliCode.TaskNotifications.TaskNotificationService.<AwaitTaskWithNotificationAsync>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.VisualStudio.Threading.ReentrantSemaphore.NotRecognizedSemaphore.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.VisualStudio.Threading.ReentrantSemaphore.NotRecognizedSemaphore.<ExecuteAsync>d__1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.VisualStudio.IntelliCode.AutomaticModelTraining.AutomaticModelTrainingController.<CreateExtractionAsync>d__61.MoveNext()
```

It seems like the generation task is not able to find the following executable on the PATH :
[ cl.exe, cmake.exe, isense_model_extractor.exe ]

This happens even after i manually added them to the PATH variable of my system and restarted the computer.

## **Fix/Workaround:**

Fortunately after digging in Visual Studio files and folders i was able to find the file that specifies the requirement for the Intellicode extension.
the file on my system was located at : "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\IntelliCode\CLI\Extractors\CPlusPlus\manifest.json"

```
{
  "language": "cplusplus",
  "regex": "(vcxproj|cmakelists|CMakeLists)",
  "extractor": "CppCustomModelExtractorDriver.exe",
  "type": "exe",
  "OS": [ "Windows" ],
  "requirements": { "Path": [ "cl.exe", "cmake.exe", "isense_model_extractor.exe" ] }
}
```

So i edited the  "Path" property to remove the requirements since I knew they were already accessible on my PATH (Verified by opening a command prompt).

With the manifest.json edited like so:

```
{
  "language": "cplusplus",
  "regex": "(vcxproj|cmakelists|CMakeLists)",
  "extractor": "CppCustomModelExtractorDriver.exe",
  "type": "exe",
  "OS": [ "Windows" ],
  "requirements": {  }
}
```

The model generation is now successful with the following output:

```
[TrainCommand I] Beginning extraction for cplusplus/intellisense-members.
[VSIX I] CLI Information: 0 : IntelliCode CLI Version 1.1.494.58956
[VSIX I] Completed successfully.
[TrainCommand I] Finished extraction for cplusplus/intellisense-members. Succeeded: True
[AutomaticModelTrainingController I] Attempting to train extraction 30e14c35-3560-40db-9b37-379719d6e7f5.
[AutomaticModelTrainingController I] Created a new model with ID 5536FB477C79B0D441AC7D2C19160985C7D2.
```

I didnt find any information for this workaround anywhere on the web so I figured out i would post it here to save someone in the same situation countless hours of searching and reinstalls.

PS: This is the first time i submit an issue on github so tell if you need more info or if I did something improperly, and english isnt my first language so sorry for my rough writing. 😅 

Thank you.

**Comment by ayim** [comment]
Hey folks, we've transitioned away from the custom model training service towards a deep learning model for C# in VS and C# Dev Kit for VSCode, along with Python in VSCode. We don't have any additional support to announce at this time, but keep your eyes posted.

https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
