### ISSUE TITLE
Instructions to disable starred recommendations are out of date.

### ISSUE THREAD

**Issue by Dalqin** [MicrosoftDocs/intellicode#393]
Hello,

The instructions for `How do I turn starred recommendations off?` are different for VS2022 Version 17.3.0 Preview 2.0
Instead, I navigate to `Tools` -> `Options` -> `Intellicode` -> `General` and uncheck `Promote likely items in IntelliSense completion lists`

If this is out of date, would someone please update it? I visit this page every time I install Visual Studio since I never remember the steps to turn off starred intelicode recommendations.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 319e91fe-5e43-c02c-cc72-d0fd7b3b8fdc
* Version Independent ID: 7fbb0db9-0607-7893-abcc-708772453c65
* Content: [Frequently asked questions - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq#feedback)
* Content Source: [docs/faq.yml](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/faq.yml)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @markw-t
* Microsoft Alias: **mwthomas**

**Comment by ayim** [comment]
Hey! This is on me to fix - thanks.

**Comment by dirtygooback** [comment]
I'd like to see some detailed docs on what each of those items actually do. What happens when I turn them on or off. What features do each affect?
