### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Aloento** [MicrosoftDocs/intellicode#395]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.2`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.69.2`
![image](https://user-images.githubusercontent.com/11802769/181057734-b492f91c-7fb4-44b6-ba4c-3fb26695fcbb.png)

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 111,
		"activateCallTime": 1,
		"activateResolvedTime": 150,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.intellicode-api-usage-examples",
				"_lower": "visualstudioexptteam.intellicode-api-usage-examples"
			},
			"activationEvent": "onLanguage:typescriptreact"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by osobeso** [comment]
Hi @Aloento thanks for reporting this.
This is a known issue we've been seeing on startup, and we're currently working on mitigating it. Will let you know once we publish the release containing a fix for this.

**Comment by osobeso** [comment]
@Aloento Hi, we have just published a new version of the extension that should not have this problem anymore.

I will close this feedback ticket but feel free to re-open if you are still having problems.
Thanks!
