### ISSUE TITLE
Intellicode Completions Crashes Ext. Host

### ISSUE THREAD

**Issue by ferreteleco** [MicrosoftDocs/intellicode#396]
Issue Type: <b>Bug</b>

Just found that my Ext. Host was crashing continuouslly. Ran extension bisect method and found Intellicode Completions as the guilty one.

Extension version: 1.0.15
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 5.15.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|15.42GB (0.91GB free)|
|Process Argv|elephant_carpaccio --crash-reporter-id 6a7732dc-b4a0-4b2d-ae5a-89e8e9ea37a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by ngnlTeto** [comment]
Same here.
I worked on an Angular Projekt and it keep crashing the Ext. Host.
After that I tried to work on an "ASP.NET - API" with VS-Code (and the extension activated) and it worked fine.

**Comment by adi-FlocknGo** [comment]
Same here, I work in python and most of my projects are on Django, whenever I open VS Code, this extension crashes the extension host. Had to do a chain of bisecting the extensions enabled to see if this is the one failing. Disabling Intellicode Completions solved the issue for me, but this is nonetheless an important extension for developers as it saves a ton of time and effort in rewriting a lot of boilerplate code.

**Comment by juihanamshet1** [comment]
Thank you for reporting this issue! 
@ngnlTeto @adi-FlocknGo Would you mind sharing your System Info, VS Code version, and OS version, please? 

For the VS Code information, in VS Code, if you click on Help -> About, you can copy the information and paste it here.

**Comment by ngnlTeto** [comment]
I had this Error on this specs:
> Version: 1.69.2 (user setup)
> Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
> Date: 2022-07-18T16:12:52.460Z
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> OS: Windows_NT x64 10.0.19042

I don't know if this information helps but, I have almost 150 Extensions. Maybe it doesn't work with another extension installed.

**Comment by ColdSpirit0** [comment]
Same for me. If I close all files in vscode, then the host will start normally

**Comment by juihanamshet1** [comment]
@ColdSpirit0 @ngnlTeto @adi-FlocknGo @ferreteleco Please update the extension to v1.0.16 as soon it's available to you; it includes a fix for the issue you were facing. Let us know if it's resolved on your end. 

If you run into the issue again, follow these steps to send us logs: In VS Code, Ctrl + Shift + P and Run the command "Developer: Open extension logs folder". It'll open up a folder, search for "intellicode-completions" in the folder and send me the latest log file when the issue occurred.

**Comment by ngnlTeto** [comment]
The fix works for me.

**Comment by ColdSpirit0** [comment]
It works for me too, thank you!

**Comment by juihanamshet1** [comment]
Glad to hear that! Thank you for the update
