### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Htut1257** [MicrosoftDocs/intellicode#399]
- Issue Type: `Performance`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/NAYMYO~1/AppData/Local/Temp/VisualStudioExptTeam.intellicode-api-usage-examples-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by osobeso** [comment]
This will be fixed once we implement the LSP server. Which should be ready in the following weeks.

**Comment by osobeso** [comment]
Hi @Htut1257, thanks a lot for the feedback!
We have just released a new version that addresses these perf issues that you mention. 

I will close this issue for now but please feel free to re-open if you still experience issues.
