### ISSUE TITLE
Slowness on larger files

### ISSUE THREAD

**Issue by domjancik** [MicrosoftDocs/intellicode#400]
Type: <b>Bug</b>

Using extension Bisect, I have identified IntelliCode API Usage Examples to be causing slowness issues, primarily in TypeScript files, especially in larger ones.

IntelliSense would take a long time to load after changes
Prettier would take a long time to format
Saving was noticably delayed until all extensions finished
If using Vim extension, editing would be noticeably delayed

Extension version: 0.2.0
VS Code version: Code 1.70.0 (Universal) (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id ca0dbd96-d70c-4e7a-a40a-0bdf63e6c6be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253

```

</details>

**Comment by osobeso** [comment]
Hi @domjancik, thanks a lot for the feedback!
I'm happy to inform you that we have just published a new version with many improvements targeting performance on ts/js large projects.

I will close this issue for now but please feel free to re-open if you still experience performance issues.
