### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by prashant-rajoriya-kredx** [MicrosoftDocs/intellicode#402]
- Issue Type: `Performance`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.2.0`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/2z/3_ymhx4j1vxbm1xw89n7ft6r0000gn/T/VisualStudioExptTeam.intellicode-api-usage-examples-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by osobeso** [comment]
Hi @prashant-rajoriya-kredx , please update your extension version to latest this issue has been fixed on 0.2.1.
