### ISSUE TITLE
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

### ISSUE THREAD

**Issue by Jagdish2022** [MicrosoftDocs/intellicode#405]
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

**Comment by markw-t** [comment]
Looks like a duplicate of #404
