### ISSUE TITLE
IntelliCode Completions do not work with long Jupyter notebooks

### ISSUE THREAD

**Issue by miqdadraza** [MicrosoftDocs/intellicode#406]
For a while now, Intellicode completions (grey suggestions) do not work with longer Jupyter notebooks. The extension activates fine and models are downloaded fine but it will not bring up any suggestions in grey. 

When I open a new Jupyter notebook, it starts working and I start seeing suggestions until the file becomes long and I save it. Once reopened, the suggestions stop. Pylance works fine as I can see suggestions in the drop down menu for functions, but no Completions grey suggestions. 

Language: Python
IntelliCode Version: 1.2.25
IntelliCode Insiders Version: 1.1.10
IntelliCode Completions Version: 1.0.18
Jupyter Version: 2022.9.1002571034 (Pre-Release)
Pylance Version: 2022.9.11 (Pre-Release)
Python Version: 2022.15.12561016 (Pre-Release)

VS Code Version: 1.72.0-insider
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by PrattayDev** [comment]
not just python bro also in java language. same problem

**Comment by juihanamshet1** [comment]
@miqdadraza Thank you for reporting the issue. Would you mind sharing the exact steps to reproduce the issue? What was the length/size of your file? If you could repro the issue with a file that you can share with us, that would be great! 

@PrattayDev At the moment, this extension supports Python, with additional experimental support for JavaScript and TypeScript.

**Comment by ayim** [comment]
We root caused this issue and fixed it a while ago!
