### ISSUE TITLE
Link to privacy policy for IntelliCode is broken

### ISSUE THREAD

**Issue by justinwiley** [MicrosoftDocs/intellicode#407]
**Product and Version** [VS/VSCode]:1.71.0
**OS Version** [macOS/Windows]:Mac
**IntelliCode Extension Version**: v0.2.2
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. Go to the install page for IntelliCode
2. Scroll to the bottom click the link in "It will never send your own custom function names. You can read more about the privacy characteristics of the feature [here](https://github.com/MicrosoftDocs/intellicode/blob/HEAD/intellicode-privacy.md#intellicode-api-usage-examples)"
3. Observe the broken url that returns 404 for https://github.com/MicrosoftDocs/intellicode/blob/HEAD/intellicode-privacy.md#intellicode-api-usage-examples

I tried following the PR instructions "To report a problem with IntelliCode for Visual Studio, please use the "Report a Problem..." feature built into the tool."...but I cant find it.

**Comment by PrattayDev** [comment]
same problem

**Comment by osobeso** [comment]
This has been fixed on version 0.2.3
