### ISSUE TITLE
Jump to definition not working properly in JS

### ISSUE THREAD

**Issue by melkayam92** [MicrosoftDocs/intellicode#41]
**Product and Version** [VS/VSCode]:  VSCode Version 1.30.0
**OS Version** [macOS/Windows]: macOS 10.14.2 
**IntelliCode Extension Version**: latest
**Target Platform or Language** [e.g. Node.js]: React/JS.

**Steps to Reproduce / Scenario:**

1. Enable the extension.
2. Every import from node_modules, when I try to jump to the definition - it takes like 10 seconds and then goes to a build folder that web pack outputs. 

* When I disable the extension, the jump to definitions works as expected.
* Any idea how can I disable it specific for JS? cause I have python and JS in the same project and it works fine for python.

**Comment by jkeech** [comment]
I don't think the IntelliCode extension should be invoked during "go to definition", so I'm not sure how it would be causing a delay in this case. @minestarks, can you take a look?

Unfortunately, there's not a way to disable IntelliCode for JS only.

**Comment by melkayam92** [comment]
Hi @minestarks, thanks for the replay.

When I say 'works as expected' I mean both fast and jump to the right definition. 
If you say it can't be related I can try again playing with other extensions as well..  

I guess it slow because it tries to look at other folders, such as the dist folder which files there are pretty big.

**Comment by minestarks** [comment]
I may certainly be wrong! I will try to reproduce locally. Thanks for the details.

I'm wondering if somehow Automatic Type Acquisition didn't kick in and we don't have typings for external libraries. Does IntelliSense appear to be generally slow/broken for external libraries?

**Comment by melkayam92** [comment]
Not only for external libraries.

For example:
import Example from '../comp/example/'

If I press on Example it takes 10 seconds if I press on the path - there is no delay.

**Comment by catycaldwell** [comment]
normalizing labels

**Comment by ayim** [comment]
@melkayam92 let us know if you're still seeing issues here! We'd love to hear from you.
