### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Anmol-Agrawal-Codes** [MicrosoftDocs/intellicode#411]
- Issue Type: `Bug`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.2.28`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 185,
		"activateCallTime": 10,
		"activateResolvedTime": 21949,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.vscodeintellicode",
				"_lower": "visualstudioexptteam.vscodeintellicode"
			},
			"activationEvent": "onLanguage:java"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by markw-t** [comment]
This appears likely to be a Java language service issue. Tagging @Eskibear to help route to the correct repo

**Comment by markw-t** [comment]
Hi @Anmol-Agrawal-Codes 
Can you give us a little more information on what symptoms you are seeing? If you see no IntelliSense for Java, I suggest you raise this issue at https://github.com/microsoft/vscode-java-pack/issues . If you're not seeing the starred items in the IntelliSense list, that might be an IntelliCode problem. 
Thanks
Mark
