### ISSUE TITLE
API Usage Examples LSP using wrong path to supported calls JSON.

### ISSUE THREAD

**Issue by Unnoen** [MicrosoftDocs/intellicode#414]
## Information
OS: _Windows 10_
OS Build: _19044.2006_
VSCode: _1.71.2 (user setup)_
IntelliCode Extension: _v1.2.28_
IntelliCode API Usage Examples Extension: _v0.2.4_

## Issue Summary
The IntelliCode API Usage Examples extension uses the wrong drive letter to access VSCode's User globalStorage directory in attempt to load the supported calls JSON files.

In the obfuscated distribution code (within server.js) `[7373].URI.parse()` splits the URI given by removing the drive letter from the path and storing it under the `scheme` property.

This parsed URI object is passed to a new instance of the `CodeSearchProviders` class where it is stored as `this.globalStorageUri`.

The `getApiExampleProvider...` functions then join it with the `support_calls.json` files using `[7373].Utils.joinPath()` which *doesn't* use the `scheme` property.

The result is a path of `\\Users\\<User>\\AppData\\Roaming\\Code\\User\\globalStorage\\visualstudioexptteam.intellicode-api-usage-examples/javascript_supported_calls.json`.

As you can see, the path does not contain a drive letter. This results in the extension erroring when VSCode is launched from any location other than the C drive (e.g., using "Open with Code" in an explorer window) as the path will contain the launch location drive, e.g., `d:\\Users\\<User>\\AppData\\Roaming\\[...]`

* _`[7373]` is the obfuscated module number. It appears to contain utility functions for path manipulation._

## Workaround
For now I have simply inserted `this.globalStorageUri.path = "c:" + this.globalStorageUri.path;` in the constructor of the `CodeSearchProviders` class after `this.globalStorageUri = t`.

**Comment by fireattack** [comment]
Can confirm, encountered the same error.

```
Logger Init
Initialization complete.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open 'f:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\visualstudioexptteam.intellicode-api-usage-examples\supported_calls.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'f:\\Users\\Administrator\\AppData\\Roaming\\Code\\User\\globalStorage\\visualstudioexptteam.intellicode-api-usage-examples\\supported_calls.json'
}
[Info  - 22:03:27] Connection to server got closed. Server will restart.
```

Obviously my `\Users\` isn't at `F:`.

**Comment by osobeso** [comment]
@Unnoen @fireattack 
Thanks a lot for reporting this.
I'll take a look and let you know once it's fixed!

**Comment by Unnoen** [comment]
Version 0.2.5 appears to have fixed it, thanks!
