### ISSUE TITLE
Font in the suggestion box looks wrong

### ISSUE THREAD

**Issue by tsonev7** [MicrosoftDocs/intellicode#415]
It seems that the font in the suggestion box is different than the one for the VS code editor. I couldn't find any setting for that, so maybe it's a bug ?

<img width="529" alt="image" src="https://user-images.githubusercontent.com/3913549/193822231-2364148b-1587-4451-aa9e-59081dafb07f.png">

**Comment by markw-t** [comment]
Hi @tsonev7  - this appears to be a problem with the JavaScript language service, so it would be better to raise the issue on the VSCode repository at https://github.com/microsoft/vscode/issues

Thanks!
Mark

**Comment by drupol** [comment]
Got the same issue, haven't found a way to fix it yet.
