### ISSUE TITLE
Small Spelling Issue

### ISSUE THREAD

**Issue by CubesterYT** [MicrosoftDocs/intellicode#416]
I just wanted to point this out, but on the Intellicode extension page on The VS Marketplace has a small spelling error:

![image](https://user-images.githubusercontent.com/78769806/195945227-6e2c5ba8-bd81-4b5d-ab2d-adb469397908.png)

Nothing more, but otherwise, the extension's great!

**Comment by ayim** [comment]
@CubesterYT, we're on it - thanks for letting us know!
If you're using the extension, let us know if you run into any bugs or problems

**Comment by CubesterYT** [comment]
Checked back on this issue after a while, it's fixed.
