### ISSUE TITLE
intellicode doesn't work at all

### ISSUE THREAD

**Issue by davidvalencia1** [MicrosoftDocs/intellicode#417]
Hi, I'm working on python and I installed the extension. It doesn't give me any installation errors. However, no suggestions appear in gray text. I've tried to disable various features like the deep learning system, but it still doesn't work. all active options as they come by default.
I think maybe I have to download some model, but I don't know how to do it

**Comment by jexjws** [comment]
![picture](https://user-images.githubusercontent.com/65129712/197372008-4495d1a2-31a1-416a-9817-cb33c5da59c5.png)

**Comment by davidvalencia1** [comment]
> ![picture](https://user-images.githubusercontent.com/65129712/197372008-4495d1a2-31a1-416a-9817-cb33c5da59c5.png)

Sorry that option doesn't even appear for me

**Comment by ayim** [comment]
@davidvalencia1 happy to help you get this working.
Could you launch VS Code, View > Output > IntelliCode and IntelliCode Completions and paste the content into this issue?

<img width="882" alt="image" src="https://user-images.githubusercontent.com/10951869/197601373-9e281fda-52f3-4d77-9f84-d618bb4c689e.png">

**Comment by davidvalencia1** [comment]
@ayim 
hello, of course yes, this is what it shows me
![image](https://user-images.githubusercontent.com/114039494/200091650-6a90575f-3c0f-4ff6-8362-187cf5bdd0da.png)

**Comment by shaojs321** [comment]
> @ayim 你好，当然是的，这就是它向我展示的 ![图像](https://user-images.githubusercontent.com/114039494/200091650-6a90575f-3c0f-4ff6-8362-187cf5bdd0da.png)

I have the same question

**Comment by ayim** [comment]
@davidvalencia @shaojs321, the grey-text suggestions require the IntelliCode Completions extension:
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions
