### ISSUE TITLE
Variable names suggestion

### ISSUE THREAD

**Issue by ryzngard** [MicrosoftDocs/intellicode#418]
From https://github.com/dotnet/roslyn/issues/64669 

> I propose putting recommendation of variable names into the functions you author, then IDE can intelligently look at the pattern of your function (what variable name was returned), to suggest to the caller what they should name the variable that the function is return.

> Programmers doesn't have to change anything, while this change makes everyone's life easier, AI can aid the process of naming things when what's returned doesn't have a name

**Comment by ayim** [comment]
If I'm reading this right, IntelliCode does this when it offers a return statement... and so does Copilot.
