### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by chiragClassplus** [MicrosoftDocs/intellicode#419]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.2.0`
- OS Version: `Darwin arm64 21.2.0`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ayim** [comment]
Hi @chiragClassplus, thanks for the report.
What is the problem you're seeing? Could you paste the issue from your clipboard?

**Comment by ayim** [comment]
@chiragClassplus if you're still seeing issues, please feel free open a new issue _with_ the error message encountered - thanks!
