### ISSUE TITLE
How to train the model with existing codebase in visual studio code like visual studio?

### ISSUE THREAD

**Issue by sarathlalsaseendran** [MicrosoftDocs/intellicode#42]
**Product and Version** [VSCode]
**OS Version** [Windows]
**IntelliCode Extension Version**: [Any]
**Target Platform or Language** [Typescript and Javascript]:

How to train the model with existing codebase in visual studio code like visual studio?

**Comment by jkeech** [comment]
Custom models are currently only supported in Visual Studio for C#. If you would like to see custom model support for TS/JS in VS Code, please vote on #26 by adding a thumbs-up.
