### ISSUE TITLE
How to download IntelliCode models externally and install them manually

### ISSUE THREAD

**Issue by halloleo** [MicrosoftDocs/intellicode#421]
I  run VS Code on an air-gapped machine (no internet). I was able to download externally the (Java) extensions I need and then install them manually. _Java_ development works now. 

However, after opening a _JavaScript_ file (as part of a Java Web project) I get the following error: "Couldn't download IntelliCode model. Please check your network connectivity or firewall settings." 

So I need to download the relevant model externally on another machine and then install it manually into VS Code. **How do I do this?**

Thanks heaps for any pointers! 

***

Updates/Notes: 

1. For completeness here the messages from the VS IntelliCode log:

        Acquiring model 'intellisense-members' for javascript
        Querying IntelliCode service for available models.
        Couldn't reach service Error Message: connect ECONNREFUSED 192.168.95.159:3128, (Error)
        Could not reach the IntelliCode service. Checking the local model cache.
        None of the cached models match.
        Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ECONNREFUSED 192.168.95.159:3128, (Error)

2. I have seen the issue about problems with the proxy when downloading the model. But in my case I cannot download the model at all because of the isolation of the machine (no internet), so the solution needs to involve a manual installation of the model.

**Comment by He110te4m** [comment]
Maybe you can take a look #102

**Comment by ayim** [comment]
Going to track this in #102, thanks!
