### ISSUE TITLE
Alan

### ISSUE THREAD

**Issue by alcarp03** [MicrosoftDocs/intellicode#428]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 412.0.0
- Skaffold Version: v2.0.3
- Minikube Version: 1.28.0

Extension version: 1.2.29
VS Code version: Code - Insiders 1.75.0-insider (79c4f9b75db3b4f50468fc022cacf8ba6d640aff, 2023-01-05T05:21:10.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.52GB free)|
|Process Argv|C:\\Users\\acarp_a9ew9kt\\iCloudDrive\\Downloads\\Bitcoin\\Scripts\\New Text Document123456.txt --crash-reporter-id a4f78e15-f94f-4d1f-b003-e8e153afaba0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by Davsterl** [comment]
Closing this out but please let us know if there is an actionable issue here.
