### ISSUE TITLE
I don't this text is supposed to be on the Intellicode vscode extension market place page

### ISSUE THREAD

**Issue by kenkit** [MicrosoftDocs/intellicode#43]
This is the vscode extionsion page not VisualStudio IDE hence this feels wrong.
`For C#, C++ and XAML support in the Visual Studio IDE, check out the IntelliCode extension on the Visual Studio Marketplace.`

**Comment by DavidObando** [comment]
Hi kenkit. The text is expected, its intention is to direct Visual Studio IDE customers to the extension for Visual Studio. The text does contain a hyperlink to the marketplace.

Thank you for your comment! We'll take it into account for future edits of this readme.

**Comment by markw-t** [comment]
Thanks for the feedback @kenkit. As @DavidObando has indicated, this sentence in the extension page for Visual Studio Code is meant to direct users who are looking for C#, C++ and XAML support to use the Visual Studio extension, as we don't support those languages in Visual Studio Code at this point. I can see how we could make that point a little more clearly, and we'll take a look next time we update that page; thanks for taking the time to raise this.

**Comment by kenkit** [comment]
I was offline for abit. 
Thanks for looking into this @markw-t @DavidObando
