### ISSUE TITLE
Star icon suggestion appears on bottom of completion list

### ISSUE THREAD

**Issue by hackerwin7** [MicrosoftDocs/intellicode#433]
**Product and Version** [VS/VSCode]: 1.75.0
**OS Version** [macOS/Windows]: windows 10
**IntelliCode Extension Version**: v1.2.30
**Target Platform or Language** [e.g. Node.js]: Java

**Steps to Reproduce / Scenario:**

![image](https://user-images.githubusercontent.com/15257080/217137461-64e8e151-4264-44cf-a6de-b6e2bc5fe261.png)

it should appear at the top of completion list with star icon suggestion

**Related Settings:**
```
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection": "enabled",
```
even I set `editor.suggestSelection` to `recentlyUsed`, `vsintellicode.modify.editor.suggestSelection` to `disabled`,  it still appears at bottom

**Comment by Eskibear** [comment]
AFAIK It's an upstream issue in Java extension, and should be fixed by https://github.com/eclipse/eclipse.jdt.ls/pull/2439 already.

**Comment by hackerwin7** [comment]
Exactly same case to this [redhat-developer/vscode-java#2917](https://github.com/redhat-developer/vscode-java/issues/2917)
After upgrade, there is no problem now.
