### ISSUE TITLE
Install of IntelliCode Insiders produces an error.

### ISSUE THREAD

**Issue by CarlBean-USDA** [MicrosoftDocs/intellicode#434]
Type: <b>Bug</b>

Received the following error when installing the "IntelliCode Insiders" extension.  I'm running VSCode on an Ubuntu VM version 22.04.2 LTS on VMWare Workstation 16 Player which is running on Windows 11.

Failed to download .NET 6.0.14:
Command failed: "/home/devuser/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/devuser/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.14" -Version 6.0.14 -Runtime dotnet

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
dotnet_install: Error: Extraction failed

 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/devuser/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/devuser/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.14" -Version 6.0.14 -Runtime dotnet

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
dotnet_install: Error: Extraction failed

Extension version: 1.1.10
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.19.0-35-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (2 x 1895)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|3.80GB (0.75GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id e88ca8c2-a854-4450-b6f1-326d65e53100|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsctsb:30677850
vscodeenable:30660116
pythonb192:30669360
funwalk2:30676043

```

</details>

**Comment by ayim** [comment]
We've currently not using the IntelliCode Insiders extension.
If you have the IntelliCode completions & API Usage Examples extensions installed as well, you'll already have our latest functionality
