### ISSUE TITLE
Code Completion crashes the whole extension server for some reason.

### ISSUE THREAD

**Issue by leomarkcastro** [MicrosoftDocs/intellicode#437]
Type: <b>Bug</b>

Everything was working fine in the morning, not installed anything new, but in the afternoon, it jsut started crashing

Extension version: 1.0.21
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5625U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.34GB (3.58GB free)|
|Process Argv|--crash-reporter-id 91684b82-9af6-4264-8407-9840f356e1f1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
6233i204:30672705
pythonb192:30669360
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by ayim** [comment]
Potentially related to https://github.com/MicrosoftDocs/intellicode/issues/439, https://github.com/MicrosoftDocs/intellicode/issues/438, #443, #441, #437

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in https://github.com/MicrosoftDocs/intellicode/issues/450, please update to the latest version of VSCode and see if this still occurs. Thanks!
