### ISSUE TITLE
Extension Host Terminated

### ISSUE THREAD

**Issue by MoeMusa** [MicrosoftDocs/intellicode#438]
Type: <b>Bug</b>

Simply Launch Visual Studio Code, and open a python script.

Extension version: 1.0.21
VS Code version: Code - Insiders 1.77.0-insider (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:56:00.839Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.97GB free)|
|Process Argv|--crash-reporter-id a4305e7a-2b27-4e2f-8900-e1282de54c85|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
azdwalk:30687957
pythonms35:30671666
cai9j608:30680470
7ij38806:30687742
pythonclientmv:30700173

```

</details>

**Comment by ayim** [comment]
Related to #440:

> 



> Type: Bug
> 
> intellicode caused the extension host to crash
> 
> Extension version: 1.0.21 VS Code version: Code - Insiders 1.78.0-insider (Universal) (2da5a0024fe2ca407f741f19340f1a10f4d692af, 2023-04-03T05:23:48.301Z) OS version: Darwin arm64 22.4.0 Modes: Sandboxed: Yes
> 
> System Info
> Item	Value
> CPUs	Apple M2 (8 x 24)
> GPU Status	2d_canvas: enabled
> canvas_oop_rasterization: disabled_off
> direct_rendering_display_compositor: disabled_off_ok
> gpu_compositing: enabled
> metal: disabled_off
> multiple_raster_threads: enabled_on
> opengl: enabled_on
> rasterization: enabled
> raw_draw: disabled_off_ok
> skia_renderer: enabled_on
> video_decode: enabled
> video_encode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> webgpu: disabled_off
> Load (avg)	7, 6, 4
> Memory (System)	8.00GB (0.06GB free)
> Process Argv	
> Screen Reader	no
> VM	0%

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in #450, please update to the latest version of VSCode and see if this still occurs. Thanks!
