### ISSUE TITLE
Ext Host crash

### ISSUE THREAD

**Issue by godzail** [MicrosoftDocs/intellicode#439]
Type: <b>Bug</b>

Extensions Host crashes until I disabled intellicode, the problem could be Copilot nightly with intellicode.

Extension version: 1.0.21
VS Code version: Code - Insiders 1.78.0-insider (f31dffc7f9b93a1cdef21243ec30dea7d489a615, 2023-03-31T01:47:17.818Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.50GB free)|
|Process Argv|--crash-reporter-id e16ab8f5-ef1e-40f9-b867-875d7d375252|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
6233i204:30659907
pythonb192cf:30661257
azdwalk:30687957
pythonms35:30671666
03d35959:30680466
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in #450, please update to the latest version of VSCode and see if this still occurs. Thanks!
