### ISSUE TITLE
AI Algorithm behind Intellicode

### ISSUE THREAD

**Issue by MbProg** [MicrosoftDocs/intellicode#44]
Hello, 
I wanted to ask if you could provide any information about the AI Algorithm used for Intellicode. It would be also great if you could give some insight what data you collect for learning your model and what features are used for the machine learning approach. I could not find any paper, article or blog describing that.

**Comment by jkeech** [comment]
@MbProg, we have some details in our FAQ at https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-model-faq#what-is-sent, which also describes how you can see the full contents of what is collected for learning the models.

**Comment by MbProg** [comment]
Unfortunately you nowhere mentioned in the article what kind of AI algorithm you are using. There are academic papers which have researched on this issue and compared some AI algorithms like KNN and Bayesian network and association rule learning. 
Could you provide some information about this and why you have decided to use it?

**Comment by jkeech** [comment]
We aim to be fully transparent about which data we are using as input to the algorithm, but the exact algorithm that is used to generate the model from that data is proprietary at this time.

**Comment by michaelsassurant** [comment]
@jkeech, after generating SCHEMA from the JSON that IntelliCode produces I have some idea of potential features, but is there a schema or documentation that Microsoft can provide to better understand how the data is collected? Some are obvious (i.e. "isInIfBlock") but others are not (i.e. "spanStart"). Appreciate any additional detail you can provide. Thanks,

SCHEMA:
         "Windows.System.Launcher": {
            "type": "object",
            "required": [],
            "properties": {
              "LaunchUriAsync(System.Uri)": {
                "type": "object",
                "required": [],
                "properties": {
                  "containingClass": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "containingFunction": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "isInConditional": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "isInLoop": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "isInIfBlock": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "spanStart": {
                    "type": "array",
                    "items": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "Repo": {
        "type": "string"
      },
      "Solution": {
        "type": "string"
      },
      "Project": {
        "type": "string"
      },
      "Document": {
        "type": "string"
      }
    }

**Comment by jkeech** [comment]
Here is a description of what those members mean:

* `Windows.System.Launcher` in the schema you provided is the class name
* `LaunchUriAsync(System.Uri)` is a member name within the class
* `containingClass`: Array of classes where this member was invoked from
* `containingFunction`: Array of functions where this member was invoked from
* `isInConditional`: Array of values indicating whether an invocation was within a conditional statement
* `isInLoop`: Array of values indicating whether an invocation was within a loop
* `isInIfBlock`: Array of values indicating whether an invocation was within an if block
* `spanStart`: Array of values indicating the position where the invocation happened within the document
* `Solution`: Path to solution file on disk where these invocations occurred
* `Repo`: Path of the directory that contains the solution
* `Project`: The name of the project where these invocations occurred
* `Document`: The name of the file where these invocations occurred
