### ISSUE TITLE
crashing extension host

### ISSUE THREAD

**Issue by RI7TE** [MicrosoftDocs/intellicode#440]
Type: <b>Bug</b>

intellicode caused the extension host to crash 

Extension version: 1.0.21
VS Code version: Code - Insiders 1.78.0-insider (Universal) (2da5a0024fe2ca407f741f19340f1a10f4d692af, 2023-04-03T05:23:48.301Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 6, 4|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ayim** [comment]
Closing this for now, we'll track in #438

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in #450, please update to the latest version of VSCode and see if this still occurs. Thanks!
