### ISSUE TITLE
JS/TS language service immediately crashed

### ISSUE THREAD

**Issue by awarely-alex** [MicrosoftDocs/intellicode#442]
Type: <b>Bug</b>

Error message: 
The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode. Please try disabling these extensions before filing an issue against VS Code.

This is for an expo react native project that has both JS and TS files. Seems to happen when the "allowJs" and "checkJs" options are set to true. 

{
  "compilerOptions": {
    "jsx": "react-native",
    "target": "es2016",                               
    "module": "commonjs",                  
    "allowJs": true,                                  
    "checkJs": true,                             
    "esModuleInterop": true,                           
    "forceConsistentCasingInFileNames": true,       
    "strict": true,                                    
    "skipLibCheck": true                             
  }
}

Extension version: 1.2.30
VS Code version: Code 1.77.1 (Universal) (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:23:33.779Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 8, 8|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id ad392788-e59d-4be2-b895-9137d80a57a8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012
03d35959:30706073
pythonfmttext:30710681
pythonclientmv:30708685

```

</details>

**Comment by ayim** [comment]
@awarely-alex if you're still encountering this issue even after https://github.com/microsoft/vscode/issues/179696 was merged in, feel free to reopen the issue.
