### ISSUE TITLE
Report a problem Python is not able to be detected by intelli code, even though it is an environment variable

### ISSUE THREAD

**Issue by SwapnadeepK** [MicrosoftDocs/intellicode#444]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by ayim** [comment]
@swapnadeepK if there is a specific error message that you're seeing and more information that you can provide about your configuration, feel free to reopen this bug
