### ISSUE TITLE
初始化崩溃，需要重启宿主程序

### ISSUE THREAD

**Issue by ChineseEngineer** [MicrosoftDocs/intellicode#447]
Type: <b>Bug</b>

打开编辑器就可复现

Extension version: 1.0.21
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.11GB free)|
|Process Argv|--folder-uri file:///d%3A/GitHub/vue/vue3-playgraound --crash-reporter-id 06ed2cbb-ba92-45bf-a1ca-72d9199d062d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by ayim** [comment]
Hi, is there a specific error code that you are getting?
i.e. "extension host has crashed"

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in https://github.com/MicrosoftDocs/intellicode/issues/450, please update to the latest version of the extension & VSCode and see if this still occurs. Thanks!
