### ISSUE TITLE
host

### ISSUE THREAD

**Issue by nhrycun** [MicrosoftDocs/intellicode#448]
Type: <b>Bug</b>

states that the host won't start at startup of VScode

Extension version: 1.0.22
VS Code version: Code - Insiders 1.78.0-insider (2c51b3de329d48f45eabe80316f099f46fd3a5cc, 2023-04-26T05:19:40.699Z)
OS version: Windows_NT x64 10.0.23440
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (44.02GB free)|
|Process Argv|--crash-reporter-id f6c9e0ba-dd0c-4b81-9a34-cf65df98f3af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
azdwalk:30721579
pythonms35:30671666
cai9j608:30680470
ecj1e332:30687743
pythonfmttext:30716741
pythonclientmv:30700173
fixshowwlkth:30724385
showsbindicator:30724477

```

</details>

**Comment by ayim** [comment]
@nhrycun we'll track this in #450
