### ISSUE TITLE
Crash extension host on startup

### ISSUE THREAD

**Issue by Kitt3120** [MicrosoftDocs/intellicode#450]
Type: <b>Bug</b>

The extension crashes the VS Code extension host on startup.

Extension version: 1.0.22
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.43GB free)|
|Process Argv|--crash-reporter-id b65361a7-6755-4b7c-8519-5c863aaced65|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythonclientmv:30725892
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by juihanamshet1** [comment]
@Kitt3120 Thank you for reporting this issue! 

It looks like you're using an older version of VS Code, would you mind updating to the latest version and see if you're still facing the issue? 

If you continue to face this issue, please help us with the below information - 
* List of all extensions you have installed. You can get this list by running `code --list-extensions` in your terminal
* Double check that it is the Intellicode Completions extension causing this issue. Run VS Code extension bisect - https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by Kitt3120** [comment]
I was forced to switch over to the insiders build, as the bug was already fixed there. I'm still on the insiders build and will probably stay there because of the additional GitHub Copilot features. By now, I guess that it's fixed on stable too.

**Comment by ayim** [comment]
From #448:

> Type: Bug
> 
> states that the host won't start at startup of VScode
> 
> Extension version: 1.0.22 VS Code version: Code - Insiders 1.78.0-insider (2c51b3de329d48f45eabe80316f099f46fd3a5cc, 2023-04-26T05:19:40.699Z) OS version: Windows_NT x64 10.0.23440 Modes: Sandboxed: Yes
> 
> System Info
> Item	Value
> CPUs	13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)
> GPU Status	2d_canvas: enabled
> canvas_oop_rasterization: disabled_off
> direct_rendering_display_compositor: disabled_off_ok
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> opengl: enabled_on
> rasterization: enabled
> raw_draw: disabled_off_ok
> video_decode: enabled
> video_encode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> webgpu: enabled
> Load (avg)	undefined
> Memory (System)	63.72GB (44.02GB free)
> Process Argv	--crash-reporter-id f6c9e0ba-dd0c-4b81-9a34-cf65df98f3af
> Screen Reader	no
> VM	0%
> A/B Experiments
> ```
> vsliv695:30137379
> vsins829:30139715
> vsliv368:30146709
> vsreu685:30147344
> python383:30185418
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> vslsvsres303:30308271
> pythontb:30258533
> pythonptprofiler:30281269
> vshan820:30294714
> pythondataviewer:30285072
> vscod805:30301674
> bridge0708:30335490
> bridge0723:30353136
> cmake_vspar411:30581797
> vsaa593cf:30376535
> pythonvs932:30404738
> cppdebug:30492333
> vsclangdf:30492506
> c4g48928:30535728
> dsvsc012cf:30540253
> pynewext54:30618038
> pylantcb52:30590116
> nodejswelcome1:30587009
> pyind779:30611226
> pythonsymbol12:30651887
> 2i9eh265:30646982
> azdwalk:30721579
> pythonms35:30671666
> cai9j608:30680470
> ecj1e332:30687743
> pythonfmttext:30716741
> pythonclientmv:30700173
> fixshowwlkth:30724385
> showsbindicator:30724477
> ```

**Comment by ayim** [comment]
@nhrycun per the instructions that were successful for @Kitt3120, please update to the latest version of VSCode and see if this still occurs. Thanks!

**Comment by ayim** [comment]
Per the instructions that were successful for @Kitt3120 who was seeing the same issue in #450, please update to the latest version of VSCode and see if this still occurs. Thanks!

**Comment by nhrycun** [comment]
Updated. It's fixed.
