### ISSUE TITLE
IntelliCode stops working

### ISSUE THREAD

**Issue by Leonardooww** [MicrosoftDocs/intellicode#453]
My intellicode for vscode just stop working, I have already unistalled the extension and vscode to reinstall both, but it didn't help.
I'm using vscode on a windows 10 pro dell notebook and trying to code in js.
I didn't saw any error messages.

**Comment by ayim** [comment]
Hi, we believe that this is due to a bug that has been resolved in the latest version. Please upgrade to the latest IntelliCode extension (v1.2.30) and latest VSCode (v1.79 or above) and see if this still occurs.
