### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ashu1230** [MicrosoftDocs/intellicode#483]
- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

**Comment by drewbitt** [comment]
You have not described the bug.

**Comment by ashu1230** [comment]
.

**Comment by ashu1230** [comment]
.
