### ISSUE TITLE
Extension works slow as hell on large TypeScript Angular project

### ISSUE THREAD

**Issue by drweb86-work** [MicrosoftDocs/intellicode#50]
Hello

I recently had to disable that extension in my latest VS Code insider build.

Could you please make adapt that extension behavior to large projects. Navigation to definition takes forever.

Thank you.

**Product and Version** [VS/VSCode]: latest insider
**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**: last
**Target Platform or Language** [e.g. Node.js]: Node.JS

**Comment by jkeech** [comment]
@drweb86-work, can you provide a minimal repro for this? IntelliCode should not be invoked during Navigate to definition, but we have also heard another report of this in #41 and would love to investigate further.

/CC @minestarks

**Comment by markw-t** [comment]
@drweb86-work we are also assuming that turning the extension off relieved the performance problem, and turning it back on again brought it back - can you confirm?

/cc @minestarks @jkeech

**Comment by drweb86-work** [comment]
@jkeech, I wish i could produce repro sample. But i can't because it is reproduced on a large angular project in company for about a 1.5 month. And after its disabling problem disappeared. I cant share the project source code since its not my property.

But issue disappeared for a while. After ~3 work days it happens again. Now i disabled all plugins and navigation to definition searches for definition to class in module for about 40 secs.

**Comment by drweb86-work** [comment]
As far as i understand now something is broken in VS Code itself.

**Comment by minestarks** [comment]
Would you be able to share a TSServer log when this happens? This is possible from the VS Code command palette: “TypeScript: open TS Server log” (or similar — I don’t remember the exact name, sorry).

Note that the log will contain possibly sensitive information about the source. If you’re not comfortable sharing here please feel free to email it to me at mineyalc@microsoft.com .

**Comment by drweb86-work** [comment]
Hello

I just posted file on e-mail. 

Thank you

**Comment by minestarks** [comment]
After investigating online we narrowed down the issue to a ~30 second delay in `updateGraphWorker` (opening the project). The issue appears linked to the Angular language service plugin rather than IntelliCode. Closing the issue based on this information. Thanks @drweb86-work for helping us investigate!
