### ISSUE TITLE
Is `DisableRemoteAnalysis` no longer supported?

### ISSUE THREAD

**Issue by undergroundwires** [MicrosoftDocs/intellicode#510]
[privacy.sexy](https://privacy.sexy/) sets `DisableRemoteAnalysis` registry key as part of "Opt-out from IntelliCode data collection" script like this:

`reg add "HKLM\SOFTWARE\Policies\Microsoft\VisualStudio\IntelliCode" /v "DisableRemoteAnalysis" /d 1 /f`

This key was documented by this repo, see [blob - intelliCode-privacy.md](https://github.com/MicrosoftDocs/intellicode/blob/dd2b47c51933897d9b290b8be4af63ab2d7a2661/docs/intelliCode-privacy.md).

Some users report issues about this freezing their Visual Studio launch (see undergroundwires/privacy.sexy#267). Is there any documentation about this? Did devs drop the support for this configuration? I see #226 PR that's related to this but it does not say much.

I'd appreciate any recommendation going forward about setting this key to know whether it should be excluded from standard pool (or from privacy.sexy completely).

**Comment by vivlimmsft** [comment]
That registry key is no longer relevant, as the related feature is no longer functional - the backend servers for model training have been shut down.
