### ISSUE TITLE
Python dose not autocomplete methods from inherited class

### ISSUE THREAD

**Issue by AlcoholV** [MicrosoftDocs/intellicode#52]
vscode : 1.30.2 
intellicode : 1.1.2 
os : Windows 10

I Can't found how to get autocomplete of inherited methods.
Am I misunderstanding about something?
Here is example.

```
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
    Dense(32, input_shape=(784,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

# not support autocomplete
model.summary()  
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

# It works! 
model.__base__.compile() 
model.__base__.__base__.summary()
```

**Comment by AlcoholV** [comment]
I checked again and it doesn't work with the Microsoft Python Analysis Engine too. 
Is this vscode own problem?

**Comment by jkeech** [comment]
@AlcoholV, if the suggestions are not showing up in the completion list when IntelliCode is disabled, then that would indicate an issue with the Python language server. If you do see the members in the list, but just not the IntelliCode starred suggestions, then that would be an issue with the IntelliCode extension.

Can you confirm that you do not see those suggestions at all? If that's the case, I would recommend filing an issue at https://github.com/Microsoft/python-language-server/issues. Thanks!

**Comment by AlcoholV** [comment]
When Jedi enabled ("python.jediEnabled": true), I can see the members in the suggestions. but if I disabled both of Jedi & intellicode, I can't see the inherited members.

**Comment by AlcoholV** [comment]
> @AlcoholV, if the suggestions are not showing up in the completion list when IntelliCode is disabled, then that would indicate an issue with the Python language server. If you do see the members in the list, but just not the IntelliCode starred suggestions, then that would be an issue with the IntelliCode extension.
> 
> Can you confirm that you do not see those suggestions at all? If that's the case, I would recommend filing an issue at https://github.com/Microsoft/python-language-server/issues. Thanks!

When Jedi enabled ("python.jediEnabled": true), I can see the members in the suggestions. but if I disabled both of Jedi & intellicode, I can't see the inherited members.
Is that a problem with Python language server?
Thank you.

**Comment by jkeech** [comment]
Yes, that sounds like a problem with the language server itself.

**Comment by jkeech** [comment]
@dhensen, that's a different issue. It looks like you are on an older version of the IntelliCode extension which points to our deprecated APIs. Can you update to the latest extension (1.1.2)? If that doesn't work, can you open a new issue?

**Comment by catycaldwell** [comment]
@savannahostrowski - Is this issue resolved in Pylance?

**Comment by savannahostrowski** [comment]
@AlcoholV 

I'd recommend installing the new Python language server for VS Code, [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance). Pylance is IntelliCode compatible and has fixed many of these issues. If you give Pylance a try and are still experiencing this, please file an issue on [our issue tracking repo](https://github.com/microsoft/pylance-release) and my team can investigate.
