### ISSUE TITLE
disable copilot toast

### ISSUE THREAD

**Issue by webreidi** [MicrosoftDocs/intellicode#523]
Type: <b>Feature Request</b>

We have been getting lots of reports that the toast stating that whole line completions are disabled because copilot is enabled. It would be great to be able to "do not show again" or disable the toast once seen.

Extension version: 0.1.26
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by vivlimmsft** [comment]
Fixed in today's release of v2.0.25.

There are some details about the fix in the changelog, which I'll repost here:

- Remove confusing toast prompting users to disable GitHub Copilot to be able to use IntelliCode.
    - The message is replaced by an unintrusive output log message saying that this extension will not suggest inline completions.
    - This is because having multiple extensions provide inline completions introduces timing-related inconsistency as the displayed completion may change after being displayed, depending on when each extension provides its completion.
    - In this case, we disable IntelliCode Completions, because:
        - GitHub Copilot, which uses an online model, is better able to provide a quality completion than IntelliCode Completions, which uses an offline model.
        - IntelliCode completions will often provide an inline completion sooner, because there's no network round-trip involved.
        - Therefore, using both at the same time often results in seeing a completion from IntelliCode for a second before it is then replaced by a totally different completion from GitHub Copilot.
    - If you would like to use both anyway, configure `"intellicodeCompletions.runAlongsideCopilot": true` in your settings.
