### ISSUE TITLE
Information page has no images

### ISSUE THREAD

**Issue by alakoring** [MicrosoftDocs/intellicode#534]
**Product and Version** [VS/VSCode]: VSCode (but really N/A)
**OS Version** [macOS/Windows]: macOS
**IntelliCode Extension Version**: v0.1.26
**Target Platform or Language** [e.g. Node.js]: N/A

**Steps to Reproduce / Scenario:**

1. Visit https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp

Note that no images show up, which makes it hard to see what this tool actually does.
<img width="742" alt="Screen Shot 3" src="https://github.com/MicrosoftDocs/intellicode/assets/12171257/981a6bc8-fe05-4c0e-8b2e-b70ed5260d5e">

The visual presentation is different from within Visual Studio but the images are missing there too. 
<img width="599" alt="Screen Shot 4" src="https://github.com/MicrosoftDocs/intellicode/assets/12171257/bd95bbd8-cffd-45d2-89f5-b5a254fdafa3">

**Comment by vivlimmsft** [comment]
Fixed with the update to v2.0.25
