### ISSUE TITLE
[VS Code] JS/TS string literal auto-complete bug

### ISSUE THREAD

**Issue by svipas** [MicrosoftDocs/intellicode#55]
**Product and Version** [VS/VSCode]: VS Code
**OS Version** [macOS/Windows]: macOS latest
**IntelliCode Extension Version**: 1.1.2
**Target Platform or Language** [e.g. Node.js]: JS/TS

If I add `.` (dot) in the string I will get auto-complete which is not correct especially with such context:

<img width="677" alt="screenshot 2019-01-25 at 11 06 49" src="https://user-images.githubusercontent.com/10441177/51735911-54689e80-2091-11e9-8a71-10e17c25f66b.png">

**Comment by svipben** [comment]
I'm separating issues from https://github.com/MicrosoftDocs/intellicode/issues/53

**Comment by Eskibear** [comment]
Same issue here, when I want to type "..." within string literal, the auto-completion blocks me. E.g. following is a simple example to reproduce it. 

![tmp](https://user-images.githubusercontent.com/2351748/53718370-f4d28f80-3e95-11e9-81ce-831b2e9b30b1.gif)

**Comment by jkeech** [comment]
Version 1.1.4 with this fix has been published to the marketplace.
