### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by MihailProcudin** [MicrosoftDocs/intellicode#550]
Type: <b>Bug</b>

HI, I am using JS and React 

And my intellisense import suggestions stopped working. 

I need to access the file where components are and then I can import them using the Lamp icon in different files. 

Feels like an issue 

P.S.
I did try Help: Start Extention Bisect 
and issue still persists 

Extension version: 1.3.1
VS Code version: Code - Insiders 1.88.0-insider (b831801945400c785b138698d9df9896ced796b7, 2024-04-02T10:12:13.894Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.15GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-22.04/root/seagoat/admin.seagoat --crash-reporter-id 3239dd5e-f9f3-4955-8312-742adf4bef9e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|Memory (System)|15.48GB (9.81GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp1r3:30958150
pythonait:30973460
jchc7451:30973074
7ghi1836:30988844
g1icg217:30999571

```

</details>

**Comment by vivlimmsft** [comment]
At first glance this *seems* unrelated to IntelliCode (we don't provide import suggestions) but then I found https://github.com/microsoft/vscode/issues/161570. 

If this is still happening can you please collect the TS server log by following [these instructions](https://github.com/microsoft/vscode/issues/161570#issuecomment-1256525622)?

If you uninstall the IntelliCode extension, do the suggestions start to work again?
