### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by a-eid** [MicrosoftDocs/intellicode#59]
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.31.0`

**Comment by jkeech** [comment]
@a-eid, can you attach the CPU profile file mentioned in the message? What language were you programming in when this happened?

**Comment by a-eid** [comment]
[VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/intellicode/files/2872613/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt)

@jkeech javascript.

**Comment by jkeech** [comment]
Thanks!

/cc @minestarks @uniqueiniquity

**Comment by jkeech** [comment]
@a-eid, did this happen when you first opened a JS file? Was it the first time you used IntelliCode for JS files? I looked through the trace, and the bulk of the time (5s) is spent in the model downloading/caching component of the IntelliCode extension.

3.9s is spent in the actual model download. This should only happen during initial extension activation, then the cached model is loaded for future use. The whole model loading process only happens during extension activation, so it should not have a continual impact while you are editing. While the download is happening, you should also see a VS Code progress indicator in the bottom saying "Downloading IntelliCode models" with a progress update (you can briefly see it in the gif below):

![progress](https://user-images.githubusercontent.com/746020/53046808-c68c9300-3445-11e9-83fb-996f47027422.gif)

I don't see any immediate ways to greatly reduce the cost here. Depending on your location, we could possibly reduce the time spent in network calls by having our models service and the model blobs themselves deployed to a region closer to you. I'd be interested to hear if this was a one-time issue or if this happens on every VS Code session. Thanks!

**Comment by a-eid** [comment]
@jkeech yeah that might be it, thanks.
