### ISSUE TITLE
PYTHONPATH set in "python.envFile" ignored

### ISSUE THREAD

**Issue by dakotahawkins** [MicrosoftDocs/intellicode#6]
**VS Code Version**: 1.25.1
**OS Version**: Windows 7
**Visual Studio IntelliCode Extension Version**: 1.0.1
**Python Extension Version**: 2018.7.1
**Target Platform or Language**: Python

**Steps to Reproduce / Scenario:**

I noticed that jedi seems to be picking up the `PYTHONPATH` set in my `.env` file, but turning that off to enable intellicode requires adding the same paths to `python.autoComplete.extraPaths` to find my modules.

**Comment by markw-t** [comment]
Hi @dakotahawkins  - thanks for trying IntelliCode

From the description, I believe the problem you are seeing is with the new Python language service itself rather than IntelliCode. Please can you report it at [VSCode-python](https://github.com/Microsoft/vscode-python/issues/new) ?

Any messages you're seeing in the Python output window in Visual Studio Code when the failure occurs may be helpful.

Thanks!

Mark

**Comment by dakotahawkins** [comment]
@markw-t Thanks! I can file it with [VSCode-python](https://github.com/Microsoft/vscode-python/issues/new). I know they've fixed issues to make this work, so maybe they need to add something similar to support IntelliCode?

I never got far enough to see things in the Python output window. In my use case this is python for django running in docker, so it's not really ever run in the development environment. That's why all of the python modules are in a subfolder of `${workspaceFolder}`, and it also makes working intellisense pretty important :)

The messages I see are just intellisense errors (e.g. "[Python (analysis)] Unable to resolve 'accounts.models'. IntelliSense may be missing for this module."). If I comment-out my `python.autoComplete.extraPaths` settings, I get them with IntelliCode but not with jedi -- it works with the `PYTHONPATH` set in my `.env` file.

I can switch back and forth by re-enabling jedi in my user settings, but I'm not sure exactly what kind of interaction between extensions happens when I do this. IntelliCode wants the MS Python Language Server (preview) re-enabled, which as far as I know only entails turning jedi off.

Is it VSCode-python's responsibility to set either IntelliCode _or_ jedi up with my python path?

**Comment by markw-t** [comment]
@dakotahawkins , yes as you've discovered, IntelliCode will only work with the new MS Python Language Server, and we help you switch jedi off to achieve that. 

IntelliCode is completely agnostic to the env file, that's entirely a language service responsibility.

**Comment by dakotahawkins** [comment]
@markw-t Thanks for the explanation! I've filed in (I hope) the proper place.

**Comment by markw-t** [comment]
Thanks @dakotahawkins ! Once things are working for you I look forward to your IntelliCode feedback 👍
