### ISSUE TITLE
【VS Code】Not working with setting: "typescript.tsdk"

### ISSUE THREAD

**Issue by Lxxyx** [MicrosoftDocs/intellicode#62]
**Product and Version** [VS/VSCode]:VSCode
**OS Version** [macOS/Windows]:Mac 10.13
**IntelliCode Extension Version**: latest
**Target Platform or Language** [e.g. Node.js]:TypeScript

**Steps to Reproduce / Scenario:**

1.define custom typescript.tsdk location in vs code
2. reload window, intellicode not working

**Comment by jkeech** [comment]
@minestarks, @uniqueiniquity can you take a look at this? Is the IntelliCode plugin not being loaded by the custom typescript SDK?

**Comment by minestarks** [comment]
Yes I believe this is the same as #32 , will confirm

**Comment by ChristianIvicevic** [comment]
I am running into the same issue. Currently I am developing in a container using the new Remote Development features and Intellicode only works when using the TypeScript version shipped with VSCode itself, but not when setting it to `"typescript.tsdk": "node_modules/typescript/lib",` in the `.vscode/settings.json` of the workspace.

**Comment by feafarot** [comment]
Is there any progress on this issue?

**Comment by uniqueiniquity** [comment]
Hi all, thanks for following up on this. I will take a look at this issue as soon as I can. Thanks for your patience!
