### ISSUE TITLE
Suggestions for Azure DevOps integration

### ISSUE THREAD

**Issue by elgorro** [MicrosoftDocs/intellicode#64]
**Product and Version** [VS/VSCode]: VS
**OS Version** [macOS/Windows]: Win10
**IntelliCode Extension Version**:  2.1.6.62495
**Target Platform or Language** [e.g. Node.js]: C#

**Steps to Reproduce / Scenario:**

1. Assuming a team
2. Training a model via IntelliCode by one developer
3. Share the model with the team (copy the link, share the link, add the link for all members)
4. Security - (Everybody who has the link can gather informations?)
5. Manually retrain the model
6. Same model is used for different branches

**Suggestions**
1. Integrate the link to the ai-model in a seperate file (".intellicode") at solution root
2. Implement that IntelliCode prefers the ".intellicode" file at root level if exists
3. Add a setting for IntelliCode where a developer can decide if he wants to benefit from team ai-model or use an own ai-model on solution level.
4. Security - automatically sharing permissions over VS TeamExplorer connected to Azure DevOps project the permission to use this ai-model
5. Automatacly train the ai-model: add an option to periodically update the ai-model (daily, weekly, monthly, yearly or every build). Considering a team the ai-model should be possible to generate from a specific branch (e.g. "master") and the model should be created only once in a while! If you have an idea of implementing this easily then go on. My idea was a possibility of using Azure DevOps and a IntelliCode build-pipeline task -> the team can then decide how often they would like to update the model, e.g. every build on master or a seperate build that triggers by schedule.
6. "GitFlow" integration: use different ai-model for different branches. (e.g. versioning IntelliCode ai-model by git branch / commit)

Thanks for the great work so far!

**Comment by jkeech** [comment]
Thanks for the suggestion! Several of these ideas are things we are actively exploring. Stay tuned for more details!

**Comment by catycaldwell** [comment]
normalizing labels. @elgorro +kudos for great feedback.

**Comment by ayim** [comment]
This feature has been succeeded by https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
