### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by levin-ilya** [MicrosoftDocs/intellicode#7]
Starting Microsoft Python language server.
[Info  - 3:33:04 PM] Created Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreter instance from Microsoft.PythonTools.Interpreter.Ast.AstPythonInterpreterFactory
[Error - 3:33:05 PM] Server initialization failed.
  Message: Object reference not set to an instance of an object.
  Code: -32000 
[object Object]

**Comment by dpetukhov** [comment]
I have the same issue. What do you need to see the context? Maybe debug info or anything?
I'm using Code 1.26.1, python 2.7

Interesting detail: if I open new editor instance (Ctrl + Shift + N) and open folder with few simple python files, select interpreter Python 3.5 - it works.

It doesn't work only in my current huge Django project written in python 2.

**Comment by dpetukhov** [comment]
Probably it's related to issue in Python Language server, not to the intellicode itself:

https://github.com/Microsoft/vscode-python/issues/2017

**Comment by markw-t** [comment]
@levin-ilya, we think this is  https://github.com/Microsoft/vscode-python/issues/2017 per @dpetukhov 's comment above. Can you resolve if you agree?

**Comment by levin-ilya** [comment]
Yup - I guess I’ll try installing the developer version...or just wait for the next release. Thanks!
