### ISSUE TITLE
[VS Code] Use enumDescriptions for enum

### ISSUE THREAD

**Issue by KamasamaK** [MicrosoftDocs/intellicode#70]
**Product and Version**: VS Code 1.32.2
**OS Version**: Windows 10
**IntelliCode Extension Version**: 1.1.4

Please use `enumDescriptions` for each `enum` in your configuration. There is currently a configuration property `vsintellicode.modify.editor.suggestSelection` that has its `markdownDescription` containing a list of each option and their respective descriptions instead of utilizing the `enumDescriptions`.

**Comment by vivlimmsft** [comment]
Done, it'll be in the next update (`1.1.5`). Thanks for reporting this!
