### ISSUE TITLE
Intellicode for Java breaks Javadoc completion

### ISSUE THREAD

**Issue by fbricon** [MicrosoftDocs/intellicode#72]
Create a java file with 

```java
/**|  Javadoc completion no longer works here
public static void main(String[] args) {}
```

See https://github.com/redhat-developer/vscode-java/issues/811

**Comment by jkeech** [comment]
@Eskibear can you take a look at this?

**Comment by Eskibear** [comment]
Sure, we didn't do lsp to code conversion for this snippet. I'll provide a fix.

**Comment by jkeech** [comment]
We plan to publish a new version of the extension (1.1.5) on Monday with this fix. Thanks for reporting!
