### ISSUE TITLE
I have an issue for Visual Studio,  don't know how to report it!

### ISSUE THREAD

**Issue by erlis** [MicrosoftDocs/intellicode#73]
While trying to report an issue I noticed the message: 

_To report a problem with IntelliCode for Visual Studio, please use the "Report a Problem..." feature built into the tool._

So I realized I should not use this method to report a VS problem, but then I cannot find the "Report a Problem" anywhere on the tool. 

How am I supposed to report a problem in VS again? 

![image](https://user-images.githubusercontent.com/137626/54438455-08d78600-470d-11e9-9c1b-a20f2fa17a95.png)

Thanks!

**Comment by jkeech** [comment]
Help > Feedback > Report a Problem. There’s also an icon near the top right corner for feedback and you can select Report a Problem there as well. Let us know if you still have issues finding it.

**Comment by erlis** [comment]
I don't see the top right icon, but I saw the option on the Help menu, I was expecting something specifically for IntelliCode not a VS issue, but anyway, I'll submit using that.

Thanks!

**Comment by markw-t** [comment]
Sorry for any confusion @erlis - we are using the general Visual Studio problem reporting system to collect feedback and issue reports. As long as you mention IntelliCode in your report, it will find its way to us. And thanks for trying IntelliCode!

Mark

**Comment by erlis** [comment]
Thanks for clarifying... you can close this one now ;)
