### ISSUE TITLE
Autocompletion Problem

### ISSUE THREAD

**Issue by RealFeorache** [MicrosoftDocs/intellicode#75]
Product: VS Code, version 1.32.3
OS: Windows 10 build 17763.379
Intellicode Extension Version: 1.1.4
Language: Python

Enabled extensions:
1. Bracket Pair Colorizer 2
2. GitLens — Git supercharged
3. MagicPython
4. Material Icon Theme
5. Python
6. Todo+

Steps to Reproduce / Scenario:
1. Enable the Visual Studio IntelliCode - Preview Extension
2. Confirm the change from Jedi to Microsoft Python Language Server (Preview)
3. Use the following code as a test:
```
import turtle

ttl = turtle.Turtle()
wn = turtle.Screen()
```
4. Next, try to check the autocompletion for ttl:
![Annotation 2019-03-18 205534](https://user-images.githubusercontent.com/47661811/54559424-5596b780-49c0-11e9-940a-825f350097f8.png)

Expected behavior:
Suggestions for the possible autocompletions. Works with Jedi:
![Annotation 2019-03-18 210050](https://user-images.githubusercontent.com/47661811/54559743-01d89e00-49c1-11e9-8948-29432771d53c.png)

Full reinstall didn't change anything.
P.S. My first issue opening, I hope I didn't miss anything

**Comment by jkeech** [comment]
@RealFeorache, thanks for reporting! This looks like an issue with the Microsoft Python Language Server rather than IntelliCode. Can you try disabling the IntelliCode extension temporarily and seeing if this problem still happens?

If it is a problem with the Microsoft Pyhton Language Server, I would recommend re-posting this issue on their repo: https://github.com/Microsoft/python-language-server/issues.

**Comment by RealFeorache** [comment]
@jkeech 
I turned off the extension, and left the Microsoft Python Language Server turn on, not turning on Jedi, and I have got myself in a situation where I don't have any autocomplete suggestions again. 
Did I understand you correctly? Please, confirm if I have done as you have asked and I will go re-post the issue on the repo of Microsoft Python Language Server.
Thanks.

**Comment by jkeech** [comment]
@RealFeorache, yes, you understood correctly. Thanks for confirming! This is an issue with the Microsoft Python Language Server. Please open an issue on that repo. Closing this issue since it's not directly related to IntelliCode.
