### ISSUE TITLE
Intellisense for custom dotnet dll loaded with clr

### ISSUE THREAD

**Issue by tmueller79** [MicrosoftDocs/intellicode#76]
**Product and Version** [VSCode]:
**OS Version** [Windows/Linux]:
**IntelliCode Extension Version**:  1.1.4

**Steps to Reproduce / Scenario:**

1. imprt clr
    sys.path.append(XYZ)
    clr.AddReference(NAMEOFDLL)
    from NAMEOFDLL import YOURCLASS
   YOURCLASS. (now the possibilities should appear)

**Comment by pgroene** [comment]
Thank you for your feedback, IntelliCode is trained on frequently used public components. It will only give intellisence on those components. Currently, we have only custom training in the Visual Studio IntelliCode extension for c#. 

-Peter [MSFT]

**Comment by catycaldwell** [comment]
@tmueller79 Thanks for the suggestion.

**Comment by catycaldwell** [comment]
#39 (similar)

**Comment by ayim** [comment]
If this is in a C# file, the new deep learning model introduced with VS2022 should actually provide some predictions here.  https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
