### ISSUE TITLE
brackets can't  be auto-completed

### ISSUE THREAD

**Issue by xqXQzzz1** [MicrosoftDocs/intellicode#8]
**VS Code Version**:1.26.1
**OS Version** [macOS/Windows]:Windows 10 17134.228
**Visual Studio IntelliCode Extension Version**:1.0.3
**Python Extension Version**:3.7
**Target Platform or Language** [e.g. Python]:
Python

rackets can't  be auto-completed

**Comment by markw-t** [comment]
Thanks for raising and closing this @xqXQzzz1 - was this a settings issue or similar? Just want to make sure there is no bug here.
