### ISSUE TITLE
Not adding parenthesis after python command

### ISSUE THREAD

**Issue by RicaBenhossi** [MicrosoftDocs/intellicode#80]
Issue Type: <b>Bug</b>

When we chose a command in python, IntelliCode completes the sentence, but without adding the parenthesis.

![NotAddingParenthesis](https://user-images.githubusercontent.com/15204313/55425211-3703f500-5558-11e9-8d00-7d88108d1700.gif)

Extension version: 1.1.5
VS Code version: Code - Insiders 1.33.0-insider (0ac111466ec925fd5ca180ab9893f51531e419b2, 2019-04-01T15:46:11.456Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1310)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.68GB (0.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jkeech** [comment]
Thanks for the additional details. This looks like a problem with the new Microsoft Python language server not supporting the `python.autoComplete.addBrackets` setting properly, which is not related to IntelliCode. I filed an issue on the Python language server repo instead.

**Comment by RicaBenhossi** [comment]
Cool... Thank you @jkeech.
