### ISSUE TITLE
[VS Code] C# support

### ISSUE THREAD

**Issue by DanielSSilva** [MicrosoftDocs/intellicode#81]
Product and Version [VS/VSCode]: VS Code
Target Platform or Language [e.g. Node.js]: C#

Steps to Reproduce / Scenario:
Add C# support to the VS Code IntelliCode extension

**Comment by aabgaryan** [comment]
15 days already and nothing happened ..

**Comment by jkeech** [comment]
@aabgaryan, this is a feature request which we are considering based in part on user demand compared to other features. We are actively tracking the number of up votes for various feature requests / enhancement issues, including this one, but we don't have anything additional to add at this time. Thanks!

**Comment by Bloodday** [comment]
@jkeech, where can i vote for this?

**Comment by DanielSSilva** [comment]
Tap on the +1 on the reactions

**Comment by konstantin890** [comment]
This is so needed, it's almost essential.
I hope to see it soon.

**Comment by Legio1221** [comment]
Here's to hoping that C# is added relatively soon!

**Comment by hegsie** [comment]
+1

**Comment by ImmaB** [comment]
Is there some sort of roadmap, that we can see if and when this is planned?

**Comment by SamMacedo** [comment]
+1

**Comment by Gameghostify** [comment]
## +1

**Comment by volkoff-pro** [comment]
+1

**Comment by kubarom** [comment]
+1

**Comment by LiamMorrow** [comment]
Being that it is the #1 upvoted issue by a large margin, wondering if there's been any movement on this front?

**Comment by pidgeon777** [comment]
Also interested.

**Comment by catycaldwell** [comment]
Thanks for the suggestion @DanielSSilva.

**Comment by omid3098** [comment]
+1

**Comment by gamerdev7** [comment]
So is there any update when are we getting C# intellicode.

**Comment by kamasylvia** [comment]
+1

**Comment by pidgeon777** [comment]
+1

**Comment by nativvstudios** [comment]
Suprised C# support isn't already added since I mean... Y'know. But besides the point any official stance on this?

**Comment by OneCyrus** [comment]
looks like an artificial limitation to push Visual Studio licenses?

**Comment by scott-parkhill** [comment]
I'm really surprised this support isn't here yet, you'd think Microsoft would want to build tools that encourages C#'s use and uptake. I'd love if this was a feature and it seems like there are a ton of others who want this too. It's interesting they chose to support Java but not C#. I'm almost inclined to believe @OneCyrus, even if it is kind of conspiratorial.

**Comment by saeed-barari** [comment]
> I'm really surprised this support isn't here yet, you'd think Microsoft would want to build tools that encourages C#'s use and uptake. I'd love if this was a feature and it seems like there are a ton of others who want this too. It's interesting they chose to support Java but not C#. I'm almost inclined to believe @OneCyrus, even if it is kind of conspiratorial.

Are they really from Microsoft though? the vscode intellicode's devs

**Comment by ayim** [comment]
This is the parent issue for #280. 
#280 had 5 votes at the time of closing, merging them here.

**Comment by pedro15** [comment]
I hope we can get this feature soon!

**Comment by ayim** [comment]
Noting a request for C# support in Linux
https://github.com/MicrosoftDocs/intellicode/issues/208

**Comment by somedeveloperhappy** [comment]
> looks like an artificial limitation to push Visual Studio licenses?

At this point, I think you're right...

**Comment by somedeveloperhappy** [comment]
> 

Nah, too late. As someone who was initially very interested about IntelliCode, I've switched to Github's copilot and am not going back to some experimental IntelliCode that has a lot of licencing and telemetry stuff involved in it. Plus, copilot is way better than it's alternatives. I say copilot has already won the initial age of coders using AI for their codes

**Comment by pedro15** [comment]
> > 
> 
> Nah, too late. As someone who was initially very interested about IntelliCode, I've switched to Github's copilot and am not going back to some experimental IntelliCode that has a lot of licencing and telemetry stuff involved in it. Plus, copilot is way better than it's alternatives. I say copilot has already won the initial age of coders using AI for their codes

Same, i'll be switching to copilot, it does not make sense to wait forever for intellicode, 
if you want to use intellicode you have to use VS community at least. Community is great, but i'm already used to the vscode workflow

**Comment by chirag127** [comment]
> > 
> 
> Nah, too late. As someone who was initially very interested about IntelliCode, I've switched to Github's copilot and am not going back to some experimental IntelliCode that has a lot of licencing and telemetry stuff involved in it. Plus, copilot is way better than it's alternatives. I say copilot has already won the initial age of coders using AI for their codes

well copilot is now paid , are you on your ?

**Comment by jamesthurley** [comment]
I notice in the [recent announcement](https://github.com/omnisharp/omnisharp-vscode/issues/5276) about the C# extension in VSCode they said:

> Utilizing LSP will allow us to bring innovative new features to the C# for VS Code extension. This includes making advanced capabilities available and, in some cases, closed-source experiences, such as IntelliCode.

So perhaps this may still come in the future.

**Comment by somedeveloperhappy** [comment]
with copilot out of the way, it would be an awesome timing for Intellicode to bomb the market for C# devs looking for a free AI helper. 
+ just please don't make it take over out jobs like they're doing with artists. thanks

**Comment by SupinePandora43** [comment]
> with copilot out of the way, it would be an awesome timing for Intellicode to bomb the market for C# devs looking for a free AI helper. 
> + just please don't make it take over out jobs like they're doing with artists. thanks

Intellicode has licensing quirks

**Comment by somedeveloper00** [comment]
> Intellicode has licensing quirks
any service that uses their own servers, most probably wants *your* data back as the fee. You can't expect a fully featured online server work for you without holding your data for their own sakes. 
So as for being allowed to share *our* data or not, it all depends on the team's tech lead & the terms of your agreements with your project. Since it's a new thing, there's probably no rules about them in most companies. ( it's just a pure guess with no proof )

**Comment by aradalvand** [comment]
Let me remind everyone that this is **the** most upvoted issue (closed or open) in the entire repository.

It's clear that the reason Microsoft has decided not to include C# support in this extension, and is still refusing to this day, is part of a larger policy that tries to make Visual Studio (the IDE) more desirable to .NET developers. This is also why VS Code (a Microsoft product) has generally better and more first-class support for the likes of TypeScript, and Python, than C# (which is also a Microsoft product!).

Please reconsider this policy. Trying to compel people to use Visual Studio instead of VS Code by refusing to enhance C# support in VS Code, is very questionable and shady. Also don't forget that Visual Studio has limited support on Mac and is not supported at all on Linux; so it can't be a proper replacement for VS Code, in addition to the fact that some people simply prefer VS Code, due its lightweight nature, and a variety of other reasons.

It's better for the greater good of the .NET/C# community (which is, once again, your own product) if you adopt a different approach and tried to make its ecosystem as healthy and as top-class as possible, which includes code editors and IDEs a developer can use.

**Comment by ayim** [comment]
Hello everyone, we are thrilled to announce the preview release of [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), a new Visual Studio Code extension that brings an improved editor-first C# development experience to Linux, macOS, and Windows.

Users' favourite IntelliCode features - specifically, starred IntelliSense ranking via a deep learning model that can rank custom classes & whole-line autocomplete model are now available for users of C# Dev Kit in VSCode via this extension: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp

For full details on this announcement, see this blogpost: https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/

cc: @timheuer

**Comment by timheuer** [comment]
> > Hello everyone, we are thrilled to announce the preview release of [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), a new Visual Studio Code extension that brings an improved editor-first C# development experience to Linux, macOS, and Windows.
> > Users' favourite IntelliCode features - specifically, starred IntelliSense ranking via a deep learning model that can rank custom classes & whole-line autocomplete model are now available for users of C# Dev Kit in VSCode via this extension: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp
> > For full details on this announcement, see this blogpost: https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/
> > cc: @timheuer
> 
> This Extension, it too heavy as Visual Studio 2022, it take too many ram and cpu 🤣🤣🤣 bad,i had to quickly revert to omnisharp version 1.x

Would love to see the report as a bug on the extension so we can look to see your experience.

**Comment by NCLnclNCL** [comment]
> > > Hello everyone, we are thrilled to announce the preview release of [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), a new Visual Studio Code extension that brings an improved editor-first C# development experience to Linux, macOS, and Windows.
> > > Users' favourite IntelliCode features - specifically, starred IntelliSense ranking via a deep learning model that can rank custom classes & whole-line autocomplete model are now available for users of C# Dev Kit in VSCode via this extension: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp
> > > For full details on this announcement, see this blogpost: https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/
> > > cc: @timheuer
> > 
> > 
> > This Extension, it too heavy as Visual Studio 2022, it take too many ram and cpu 🤣🤣🤣 bad,i had to quickly revert to omnisharp version 1.x
> 
> Would love to see the report as a bug on the extension so we can look to see your experience. https://github.com/dotnet/vscode-csharp

Yes, i too using lsp but it is light,
It is  this
Client lsp Extension
https://github.com/statiolake/vscode-csharp-ls
Or
https://github.com/vytautassurvila/vscode-csharp-ls
And lsp server 
https://github.com/razzmatazz/csharp-language-server
