### ISSUE TITLE
Intellicode does not offer recommendations in some argument completion scenarios

### ISSUE THREAD

**Issue by sujayvsarma** [MicrosoftDocs/intellicode#82]
In certain scenarios, IntelliCode seems to stumble and get tongue-tied. Here is an example. Type this code snippet:

```
using Newtonsoft.Json;
…

object obj = JsonConvert.SerializeObject<object>(jsonString, Formatting.Indented , 
```

When you hit the ",", there are two overloads that apply. One that requires the `JsonSerializerSettings` and the other that's looking for a list of `JsonConverter`s. However, IntelliCode gets confused and fails to suggest anything. 

Instead, you get to see **IntelliSense**'s suggestion for the JsonConverter<T>.

Now, go ahead and type in "new" (because you want the `JsonSerializerSettings`). Again, IntelliCode is silent and you see IntelliSense suggestion for `JsonSerializerSettings`.

**Comment by jkeech** [comment]
IntelliCode is not currently designed to give recommendations in 100% of scenarios. As an example, it will only offer suggestions when it is reasonably confident of the recommendations, which requires the model having seen enough training data of a similar pattern. This scenario is something that we should be able to handle in the future, but for now it's not expected to offer any recommendations.

In general, IntelliCode is expected to degrade gracefully when it does not have any recommendations for a given scenario. You should see the standard IntelliSense completion list without any starred items at the top, but you should not see any noticable errors or issues other than a lack of IntelliCode recommendations.

**Comment by sujayvsarma** [comment]
Yup, I was so caught up with seeing what IntelliCode does do that I forgot about the things it can't do (yet) and the gracefully-degrade scenarios. My bad :) What you (@jkeech) say is perfectly acceptable and reasonable. I would close this issue with that.
