### ISSUE TITLE
It can not work correctly with tensorflow

### ISSUE THREAD

**Issue by svod5306** [MicrosoftDocs/intellicode#83]
well,my python version is 3.6.5 64bit，and my tensorflow version is 1.13.1.
the simple code is:
import tensorflow as tf
but the intellicode can not auto show tf method after I typed tf.
It only can show if I write "import tensorflow.python as tf",but you know,this is not right.

**Comment by jkeech** [comment]
This is due to Microsoft/python-language-server#881. Once the issue is fixed in the language server and base intellisense shows up correctly for tensorflow, IntelliCode recommendations should show up as well.
