### ISSUE TITLE
Cant activate IntelliCode for python

### ISSUE THREAD

**Issue by zuozhiwen** [MicrosoftDocs/intellicode#87]
Extension error messages:

Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"c:\\Users\\DD\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.1.5\\IntellicodeModels\\88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by wenh06** [comment]
Try downgrade this extension by uninstalling it first and then choosing "Install Another Version..." Don't forget to disable auto updating extensions.

**Comment by jkeech** [comment]
This is an issue with the Python extension that was recently updated (Microsoft/vscode-python#5437). The Python extension owners are rolling out a fix, but in the mean time, you can work around it by installing an older version of the Python extension temporarily. The IntelliCode activation error for python files is a side-effect from the Python extension failing to load.
