### ISSUE TITLE
Autocomplete not work under some circumstance

### ISSUE THREAD

**Issue by futurehome** [MicrosoftDocs/intellicode#88]
Issue Type: <b>Bug</b>
In the code below, it can't autocomplete _finditer_ after _pattern_, actually, it doesn't show any suggestion after I input the '.' after _pattern_.

```
import re

sentense = """
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
"""

pattern = re.compile(r"(Mr|Ms|Mrs)\.?\s[A-Z]\w*")
matches = pattern.finditer(sentense)
for match in matches:
    print(match)

```

Extension version: 1.1.5
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (7.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jkeech** [comment]
I'm able to reproduce this. It looks like an issue with the Python language server since it's not returning any completions lists at all. I filed Microsoft/python-language-server#1015 for this issue.

**Comment by KongNan** [comment]
Me too...

![IntelliCodeX](https://user-images.githubusercontent.com/5051591/61098938-4964c780-a493-11e9-9a60-96b7602dfb7c.gif)
