### ISSUE TITLE
[VSCode] better guide for language activation failure?

### ISSUE THREAD

**Issue by Eskibear** [MicrosoftDocs/intellicode#89]
Currently when failing to activate for one language, it looks like:
![image](https://user-images.githubusercontent.com/2351748/56779830-5ddbe100-680f-11e9-8480-600752de3c34.png)

Imagine that I'm a TS/JS dev using IntelliCode extension, for some reason I want to open and view content of a .java/.py file, and then it pops up an **error** message box saying I should install something to enable IntelliCode.

The truth is IntelliCode extension is activated, but the enhanced-intellisense is not enable for the language, because the requirements are missing. IMO, it would be better if: 
- The message box is a info instead of an error, because there's no error from the user's perspective, it just doesn't have enhanced completion experience. 
- The saying is something like "You can install the LANG extension to acquire enhanced completion experience for LANG." For me as a user, it looks better, and not aggressive.

Moreover, it would be better to point users to the required extension directly, then they don't bother to search and find the right extension from so many candidates. Technically it's feasible as we already know the required extension id. 
<details>
  <summary>CLICK to see an example</summary>
<img src="https://user-images.githubusercontent.com/2351748/56780535-3f2b1980-6812-11e9-8f8f-fd7529df3adf.gif" />
</details>

Just my 2 cents, hope it helps.

**Product and Version** : VSCode
**OS Version**: any
**IntelliCode Extension Version**: 1.1.5
**Target Platform or Language**: any

**Comment by jkeech** [comment]
Thanks for the suggestions. I think these are good ideas, and we will implement them soon.

**Comment by jkeech** [comment]
Fixing in 1.1.6
