### ISSUE TITLE
Output Opens Automatically

### ISSUE THREAD

**Issue by DanielSokil** [MicrosoftDocs/intellicode#9]
**VS Code Version**: `1.26.1`
**OS Version** [macOS/Windows]: `Linux pop-os 4.15.0-33-generic`
**Visual Studio IntelliCode Extension Version**: `1.0.3`
**Python Extension Version**: `2018.7.1`
**Target Platform or Language** [e.g. Python]: `Python`

**Steps to Reproduce / Scenario:**
1.
Writing a forloop:
`for name in names`
The output shows up displaying errors:
![screenshot from 2018-08-26 00-52-23](https://user-images.githubusercontent.com/24403355/44624943-594ed980-a8ca-11e8-8b5f-e246d34e0121.png)

2.
When a Python file is open
Renaming the file name with cause Output to show up with errors.

How to stop the Output window from showing up?

Related to:
- https://github.com/Microsoft/vscode/issues/34221
- https://github.com/angular/vscode-ng-language-service/issues/187

**Comment by neilsustc** [comment]
@DanielSokil Did you solve it? I have tried the development build of Python extension but this issue still exists 🤔

**Comment by DanielSokil** [comment]
@neilsustc No, I still have this issue.

**Comment by DanielSokil** [comment]
Related to: https://github.com/angular/vscode-ng-language-service/pull/195/

**Comment by DanielSokil** [comment]
@neilsustc The only way to currently stop output from showing up is: `"vsintellicode.python.completionsEnabled": false` Disabling the Beta linter and using default.

**Comment by gewarren** [comment]
@jkeech Can you look at this issue?

**Comment by markw-t** [comment]
Hi @DanielSokil . We believe this may be a problem with the Python language service itself. Please can you raise an issue at https://github.com/Microsoft/python-language-server/issues/  if you are still seeing this behavior?
