### ISSUE TITLE
Docs says it's just for C#

### ISSUE THREAD

**Issue by patrikhuber** [MicrosoftDocs/intellicode#90]
This documentation says at the top:

> The IntelliCode extension for Visual Studio offers additional functionality for C# developers

I don't think that's true, blog posts and talks from MS advertise IntelliCode for C++ as well, and in fact IntelliCode is also installed with the C++ workload in VS 2019 Preview 2.
I'd guess this is an oversight and this documentation should state more supported languages than just C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 319e91fe-5e43-c02c-cc72-d0fd7b3b8fdc
* Version Independent ID: 7fbb0db9-0607-7893-abcc-708772453c65
* Content: [Frequently asked questions - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq)
* Content Source: [docs/faq.md](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/faq.md)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @markw-t
* Microsoft Alias: **mwthomas**

**Comment by jkeech** [comment]
Thanks! These docs are currently being rewritten; I’ll make sure this section is made clearer.

The intent of this answer was to say something along the lines of “Base models are available for all supported languages (C#, XAML, C++ in Visual Studio; and TS/JS, Python, and Java in VS Code), but C# has some additional features, including custom models, argument completion, and editorconfig generation.”

**Comment by patrikhuber** [comment]
I see!

Following from your sentence, the C++ model doesn't have "argument completion"? Sounds like quite an essential feature but of course depends on what exactly "argument completion" is.
Also following from your sentence, Python in VS is not supported, only Python in VS Code?

Would be really great to make that all much clearer.

**Comment by jkeech** [comment]
Yes, those statements are all correct. We plan to enable argument completion and custom models for other languages once we refine the models and the workflow for creating and managing custom models, but those are still preview features that we are piloting with a single language for now. The base models for all languages currently include only member completions (method, field, property).

**Comment by patrikhuber** [comment]
I see! Thanks for the clarification! Hope to see it on a more clear docs page in the future :-).
