### ISSUE TITLE
Privacy?

### ISSUE THREAD

**Issue by liamdawson** [MicrosoftDocs/intellicode#91]
What data does IntelliCode send from your machine, and when? I haven't found any clear indications on how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 319e91fe-5e43-c02c-cc72-d0fd7b3b8fdc
* Version Independent ID: 7fbb0db9-0607-7893-abcc-708772453c65
* Content: [Frequently asked questions - Visual Studio IntelliCode](https://docs.microsoft.com/en-us/visualstudio/intellicode/faq#feedback)
* Content Source: [docs/faq.md](https://github.com/MicrosoftDocs/intellicode/blob/master/docs/faq.md)
* Product: **visual-studio-family**
* Technology: **intellicode**
* GitHub Login: @markw-t
* Microsoft Alias: **mwthomas**

**Comment by jkeech** [comment]
Does this answer your question? https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio#telemetry

If you choose to do custom model training for C#, this provides more information specifically around what data is used during the custom model training process: https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#data-and-privacy.

**Comment by jkeech** [comment]
Closing this issue since it looks like those FAQ entries helped. If you still have questions, just let us know and we can re-open this issue.
