### ISSUE TITLE
Do not work with Remote Development

### ISSUE THREAD

**Issue by trobr** [MicrosoftDocs/intellicode#93]
**Product and Version** [VS/VSCode]:Version: 1.34.0-insider (user setup)
**OS Version** [macOS/Windows]:Windows_NT x64 10.0.17763
**Remote OS Version**: Ubuntu 16.04
**IntelliCode Extension Version**: 1.1.6
**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1.Open remote floder with Remote Development extension
2.VSIntelliCode can not download language server

the output window show this messgae:
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
```

![image](https://user-images.githubusercontent.com/40254133/57280719-e8f48b00-70db-11e9-8336-fa45395b9d22.png)

**Comment by vivlimmsft** [comment]
@trobr, is the Ubuntu 16.04 machine you're connecting to behind a firewall and/or does it require a proxy to access the internet?

If so, can you please check the value of `$HTTP_PROXY` from VSCode's integrated terminal?

If you are not behind a firewall/proxy, could you please try running this on the remote to see if it can reach the IntelliCode service?
```
$ curl https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/python/intellisense-members/output/latest
```

Our service should respond with a JSON object similar to the following:
```
ubuntu@ubuntu:~$ curl https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/python/intellisense-members/output/latest
{"model":{"id":"88630A1B4C077752096ECAA576B92C7D3FA1","friendlyName":"Base (Python)","language":"python","analyzer":"intellisense-members"},"output":{"id":"BC98A65409D042A99DDAF47DC30E1530","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","targetedInputIds":[],"version":1556898645147,"status":"OutputReady","trainingResults":{"displayClasses":[]},"blob":{"schema":"azureBlobStorage","name":"Output_88630A1B4C077752096ECAA576B92C7D3FA1_BC98A65409D042A99DDAF47DC30E1530","azureBlobStorage":{"readSasToken":"https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_BC98A65409D042A99DDAF47DC30E1530?sv=2018-03-28&sr=b&sig=2LeZIFA6mOArlTj%2FAb2rp6QOEm7RmcOrRx29slYyyvY%3D&se=2019-05-07T20%3A26%3A52Z&sp=r"}},"created":"2019-05-03T15:50:45.1474524Z","updated":"2019-05-03T15:50:45.6375847Z"}}ubuntu@ubuntu:~$ 
```

**Comment by trobr** [comment]
Thanks!My remote machine is behind a proxy,But whether I turn the proxy on or off, I get the same result.When I run this code in my remote machine:
```
curl https://prod.intellicode.vsengsaas.visualstudio.com/api/v1/model/common/python/intellisense-members/output/latest
```

I got this result:
```
{"model":{"id":"88630A1B4C077752096ECAA576B92C7D3FA1","friendlyName":"Base (Python)","language":"python","analyzer":"intellisense-members"},"output":{"id":"BC98A65409D042A99DDAF47DC30E1530","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","targetedInputIds":[],"version":1556898645147,"status":"OutputReady","trainingResults":{"displayClasses":[]},"blob":{"schema":"azureBlobStorage","name":"Output_88630A1B4C077752096ECAA576B92C7D3FA1_BC98A65409D042A99DDAF47DC30E1530","azureBlobStorage":{"readSasToken":"https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_BC98A65409D042A99DDAF47DC30E1530?sv=2018-03-28&sr=b&sig=UfAUL6QnjdySf7S5T8X5ezAnucrETvjH7bpWj%2BCybzA%3D&se=2019-05-08T03%3A27%3A02Z&sp=r"}},"created":"2019-05-03T15:50:45.1474524Z","updated":"2019-05-03T15:50:45.6375847Z"}}(pytorch)
```

![image](https://user-images.githubusercontent.com/40254133/57346629-d5036480-7181-11e9-9bd6-d21a5ddf9f98.png)


This issue seems to be caused by the fact that the  IntelliCode service can not download automatically in remote machine.

**Comment by vivlimmsft** [comment]
It seems that proxy settings are forwarded from local VSCode to the remote: https://github.com/microsoft/vscode-remote-release/issues/213. I was able to reproduce this by setting the `http.proxy` setting locally and connecting to a remote, after which the IntelliCode extension could no longer reach the service.

You should be able to work around this by adding your proxy config to the remote settings. That will override any proxy settings that are being sent from local VSCode.

![image](https://user-images.githubusercontent.com/27872315/57359228-094c3600-712c-11e9-8446-fcd61bc4bea4.png)

```
{
    "http.proxy": "http://127.0.0.1:8123"
}
```

Let me know if that works for you.

**Comment by trobr** [comment]
You are right! It‘s useful for me.
Thanks!

**Comment by vivlimmsft** [comment]
Great, I'm glad that worked for you. I updated the title to make it easier for others to find if they have the same issue.

**Comment by Winson-Huang** [comment]
it seems you use remote-ssh, in remote-wsl it seems a bit different. If proxy service is in windows, use 127.0.0.1 in remote setting will be helpless, see https://github.com/MicrosoftDocs/intellicode/issues/165#issuecomment-1094972469
