### ISSUE TITLE
Ability to customize model download / installation path

### ISSUE THREAD

**Issue by FruitieX** [MicrosoftDocs/intellicode#95]
**Product and Version** [VS/VSCode]: VSCode
**OS Version** [macOS/Windows]: Linux / NixOS
**IntelliCode Extension Version**: 1.1.6
**Target Platform or Language** [e.g. Node.js]: v10.2.0

Hi,

I'm using IntelliCode in a setup where VSCode + extensions are managed by my system's package manager. As such the IntelliCode extension will be installed in a read-only file system path.

I haven't come across any issues with any of the other VSCode extensions I'm using in this setup, but IntelliCode won't work as it tries (and fails) to store the IntelliCode models under the same read-only path as where the extension is installed.

If possible - and if it's an easy change, can you provide us with an extension setting inside VSCode which allows customizing the model download and installation path? This way the IntelliCode extension will work for the (admittedly small number :-)) of users who run a system-wide installation of VSCode + extensions like this, who could now set the model path pointing to somewhere in our home directory.

**Steps to Reproduce / Scenario:**

1. Install the extension in a path where users only have read access
2. Launch VSCode as an unprivileged user, observe the following error message pops up:

![Screenshot from 2019-05-10 09-02-54](https://user-images.githubusercontent.com/3673134/57505819-7e716400-7302-11e9-8f25-b3b26d8937ae.png)

**Comment by jkeech** [comment]
This should be pretty easy to do. I agree that the number of users in this scenario is probably small, but it seems like a reasonable change to make.

**Comment by jkeech** [comment]
When 1.1.7 is released (no date confirmed yet), there will be a new setting called `vsintellicode.modelDownloadPath` which you can use to override the folder that is used for model downloads. The default download path will remain in the extension install directory for now. Thanks for this suggestion!
