### ISSUE TITLE
Failed to download in China

### ISSUE THREAD

**Issue by CavalloneChen** [MicrosoftDocs/intellicode#99]
The intellicode extensions failed to work in mainland China due to network issues. Other MS products works fine. And this is a persistent issue.

**Comment by jkeech** [comment]
Can you please provide the logs that you see in the IntelliCode output window when the model download fails?

Also, can you try the troubleshooting steps at https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio-code#no-starred-suggestions, including making sure the network proxy support is enabled?

**Comment by catycaldwell** [comment]
@CavalloneChen - are you able to reproduce and share logs?

**Comment by ayim** [comment]
Now tracking in 102.
